LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/CCApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>CCApprovalStatus__c</fullName>
    <description>It depicts the Approval status for particular lead.</description>
    <inlineHelpText>Client Take-On Approval Status</inlineHelpText>
    <label>CC_Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <inlineHelpText>Country code of contact number</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code_Name</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Expertise_LT__c.field-meta.xml
<CustomField>
    <fullName>Expertise_LT__c</fullName>
    <label>Expertise</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/IL_ApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>IL_ApprovalRejectionRecommendation__c</fullName>
    <label>IL Approval / Rejection Recommendation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry_Leader__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which user has referred this lead.</description>
    <label>Industry Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads4</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/IndustryLeaderApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>IndustryLeaderApprovalStatus__c</fullName>
    <label>Industry Leader Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/IsLead__c.field-meta.xml
<CustomField>
    <fullName>IsLead__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Lead</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/OnNewStage__c.field-meta.xml
<CustomField>
    <fullName>OnNewStage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>On New Stage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/SMEG_LT__c.field-meta.xml
<CustomField>
    <fullName>SMEG_LT__c</fullName>
    <label>SMEG</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Country_Code_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Algeria (+213)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (+376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (+1264)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua &amp; Barbuda (+1268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia (+61)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (+1242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (+1246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (+1441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia Herzegovina (+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana (+267)</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil (+55)</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei (+673)</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria (+359)</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso (+226)</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi (+257)</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia (+855)</fullName>
    </customValue>
    <customValue>
        <fullName>India (+91)</fullName>
    </customValue>
    <masterLabel>Country Code Name</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/LeadSyncNameTest.cls
@isTest
public class LeadSyncNameTest {
	@isTest
    public static void invocableTest(){
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User u = new user();
        u.LastName = 'Testclassra Code';
        u.Email = 'test@test.com';
        u.Alias = 'Tcode';
        u.Username = 'testclasshhhy@test.com';
        u.CommunityNickname = 'test12';
        u.LocaleSidKey = 'en_US';
        u.TimeZoneSidKey = 'GMT';
        u.ProfileId = pro.Id;
        u.LanguageLocaleKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        insert u;
        
        Lead obj1 = new Lead();
        obj1.LastName = 'Test Test';
        obj1.FirstName = 'vijay';
        //obj1.IndustryLeaderApprovalStatus__c = 'Approved'; // Phase-1
        obj1.Status = 'Accept Client';
        //obj1.CCApprovalStatus__c = 'Approved'; //Phase-1
        obj1.CountryCode__c = 'India (+91)';
        obj1.OnNewStage__c = 2323;
        obj1.Expertise_LT__c = 'Human Capital Consulting';
        obj1.SMEG_LT__c = 'Cyber';
        obj1.Region__c = 'North';
       // obj1.IL_ApprovalRejectionRecommendation__c = 'fgnc'; //Phase-1
        obj1.Company = 'Cloud Analogy';
        obj1.Industry_Leader__c = u.Id;
        obj1.Industry__c = 'Banking';
        obj1.Email = 'test@gmail.com';
        obj1.IsLead__c = True;
        obj1.MobilePhone = '1234567891';
        obj1.Formerly_Known_As__c = 'Rajat';
        insert obj1;
        
        LeadSyncName.invocable(new List<Id>{obj1.Id});
        
    }
}