LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry_Business_Partner__c.field-meta.xml
<CustomField>
    <fullName>Industry_Business_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Business Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>New_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry_Leader__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which user has referred this lead.</description>
    <label>Industry Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads4</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/LeadSharingForNSLTest.cls
@isTest
private class LeadSharingForNSLTest {

    @isTest
    static void testLeadRecordSharingToNSL() {
        // Create a test user to represent the Industry Leader
        User industryLeaderUser = TestDataFactory.createUserRecord();
        insert industryLeaderUser;

        // Create a test lead record
        Lead testLead = new Lead(
            FirstName = 'Test',
            LastName = 'Lead',
            Company = 'Tata Communications',
            Industry_Leader__c = industryLeaderUser.Id,
            Industry__c ='Banking'
        );
        insert testLead;

        // Create a map of old Lead records for the test lead
        Map<Id, Lead> oldLeadMap = new Map<Id, Lead>{ testLead.Id => new Lead(Industry_Leader__c = null) };

        // Call the method from the main class
        Test.startTest();
        leadSharingForNSL.leadRecordSharingToNSL(new List<Id>{ testLead.Id }, oldLeadMap);
        Test.stopTest();
        
    }

    @isTest
    static void testLeadRecordSharingToSectorCordinator() {
        // Create a test user to represent the Industry Business Partner
        User businessPartnerUser = TestDataFactory.createUserRecord();
        businessPartnerUser.FirstName = 'Business';
        businessPartnerUser.LastName = 'Partner';
        
        insert businessPartnerUser;

        // Create a test lead record
        Lead testLead = new Lead(
            FirstName = 'Test',
            LastName = 'Lead',
            Industry_Business_Partner__c = businessPartnerUser.Id,
            Company ='test nsal'
        );
        insert testLead;

        // Create a map of old Lead records for the test lead
        Map<Id, Lead> oldLeadMap = new Map<Id, Lead>{ testLead.Id => new Lead(Industry_Business_Partner__c = null) };

        // Call the method from the main class
        Test.startTest();
        leadSharingForNSL.leadRecordSharingToSectorCordinator(new List<Id>{ testLead.Id }, oldLeadMap);
        Test.stopTest();

        
    }
}