LinKreta_POC_Repository/force-app/main/default/objects/Joint_Venture__c/Joint_Venture__c.object-meta.xml
<CustomObject>
    <label>Joint Venture</label>
    <nameField>
        <label>Joint Venture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Joint Ventures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Joint_Venture__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Venture</relationshipLabel>
    <relationshipName>Joint_Venture</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/JointVentureTriggerHelper.cls
/*************************** 
* @Name        JointVentureTriggerHelper  
* @Author      Ayushi Sethi
* @Date        27/07/2023
****************************** */

public class JointVentureTriggerHelper{
    //this method is creating Enquiry Joint Venture records whenever Joint Venture is created
    public static void createEnquiryJointVenture(List<Joint_Venture__c> jointVentures){
        //Start SFDC-[Phase-1]: code is added by Biplow sarkar | 03-04-2024
        /*
        Map<Id,List<Joint_Venture__c>> accountIdJointVentures = new Map<Id,List<Joint_Venture__c>>();
        for(Joint_Venture__c jointVenture : jointVentures){
            if(jointVenture.Client__c != null){
                if(!accountIdJointVentures.containsKey(jointVenture.Client__c)){
                     accountIdJointVentures.put(jointVenture.Client__c,new List<Joint_Venture__c>());
                }
                accountIdJointVentures.get(jointVenture.Client__c).add(jointVenture);               
            }
        }
        List<Opportunity> enquiries = new List<Opportunity>([SELECT Id,AccountId from Opportunity where AccountId IN : accountIdJointVentures.keySet()]);
        List<Enquiry_Joint_Venture__c> enquiryJointVentures = new List<Enquiry_Joint_Venture__c>();
        for(Opportunity enquiry: enquiries){
            String accountId = enquiry.AccountId;
            if(accountIdJointVentures.containsKey(accountId)){
                for(Joint_Venture__c jointVenture : accountIdJointVentures.get(enquiry.AccountId)){
                    enquiryJointVentures.add(new Enquiry_Joint_Venture__c(
                        Joint_Venture__c = jointVenture.Id,
                        Enquiry__c = enquiry.Id));               
                }
            }
            
        }
        system.debug('enquiryJointVentures.size() '+enquiryJointVentures.size());
        if(enquiryJointVentures.size() > 0)
        	INSERT enquiryJointVentures;
        */
        //End SFDC-[Phase-1]: code is added by Biplow sarkar | 03-04-2024
    }
}