LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>To store all the application exception We are using this Object. This will be helpful when an exception occurs in the future, background apex jobs, or flows.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Er-{0000000}</displayFormat>
        <label>Error Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/ErrorAPI__c.field-meta.xml
<CustomField>
    <fullName>ErrorAPI__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is useful for Showing the Detail Page through Dynamic Form</inlineHelpText>
    <label>Error/API</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <inlineHelpText>This is the brief description of the problem or situation involved.</inlineHelpText>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <inlineHelpText>The type of error occurred. Helpful in resolving it.</inlineHelpText>
    <label>Exception Type</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <inlineHelpText>The Name of Method/Function of the Artifact in which the exception has occurred.</inlineHelpText>
    <label>Method/Function Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/NameofArtifact__c.field-meta.xml
<CustomField>
    <fullName>NameofArtifact__c</fullName>
    <inlineHelpText>This Shows the Name of Apex Class, Flow , Apex Jobs In which exception occurred.</inlineHelpText>
    <label>Name of Artifact</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <inlineHelpText>Request JSON Body of the API callout.</inlineHelpText>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <inlineHelpText>Response JSON Body of the API callout.</inlineHelpText>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/SFDCRecordReference__c.field-meta.xml
<CustomField>
    <fullName>SFDCRecordReference__c</fullName>
    <inlineHelpText>The exception has occurred on this Record Id.</inlineHelpText>
    <label>SFDC Record Reference</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <inlineHelpText>During API callout of this End Point URL we are receiving the exception.</inlineHelpText>
    <label>URL</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/ErrorLogCreater_cls.cls
/* 
     Written By: Bhanwar Singh
     Created Date: 15-03-23
     Last Modified By : 
     Last Modified Date : 15-03-23
     Description : This class is used to create the Error Log For all the Exception occurred in the System.
     Variable Used : - 
      debugMessages : - List of Messages Recieved From Flow 
      className :- Apex Class Name in which exception occurred 
      methodName : - Apex Method/ Function Name in which exception occurred
      recordReference : - Record Id on which error has occurred
      requestBody : - Request Body sent from apex class
      responseBody : - Response recived by API callout
      endPointURL : - API callout url
*/
public without sharing  class ErrorLogCreater_cls {
    // This Method is used for Exception occurred in Flow
    
    /**
    * @description 
    * @author Biplow Sarkar | 16-08-2023 
    * @param debugMessages 
    **/
    @InvocableMethod(label='Log Debug Message' description='Outputs messages to the debug log')
    public static void flowDebugLogger (List<String> debugMessages) {
        try{
            List<ErrorLog__c> errorList = new List<ErrorLog__c>();
            for(String message : debugMessages){
                ErrorLog__c err = new ErrorLog__c();
                err.ExceptionMessage__c = message;
                err.ErrorAPI__c = true;
                errorList.add(err);
            } 
            System.debug('Limits  ');
            insert errorList;
        }
        Catch(Exception e){
            ErrorLogCreater_cls.apexDebugLogger(e, 'ErrorLog' , 'flowDebugLogger' , '' );
        }
    }

    /**
    * @description | This Method is used for all exception occurred in Apex Class except Apex class having API callout
    * @author Biplow Sarkar | 13-06-2023 
    * @param e 
    * @param className 
    * @param methodName 
    * @param recordReference 
    **/
    public static void apexDebugLogger(Exception e, String className , String methodName , String recordReference ){
        try{
            ErrorLog__c err = new ErrorLog__c();
            err.NameofArtifact__c = className;
            err.ExceptionMessage__c = 'Error Message: '+ e.getMessage()+' | Stack Trace: '+ e.getStackTraceString(); //SFDC-[U_224]: code is added by Biplow sarkar | 19-06-2023
            err.ExceptionType__c = e.getTypeName();
            err.MethodName__c = methodName;
            if(!String.isEmpty(recordReference)) {
             err.SFDCRecordReference__c = recordReference;
            }
            err.ErrorAPI__c = true;
            insert err;
        }
        Catch(Exception ex){
            System.debug('Error: ErrorLog>>apexDebugLogger>>'+ex);
        }
    }

    /**
    * @description This Method is used for all exception occurred in Apex Class with API callout
    * @author Biplow Sarkar | 16-08-2023 
    * @param ex 
    * @param className 
    * @param methodName 
    * @param recordReference 
    * @param requestBody 
    * @param responseBody 
    * @param endPointURL 
    **/
    public static void apexDebugLoggerForAPICallout(Exception ex, String className , String methodName , String recordReference , String requestBody , String responseBody, String endPointURL){
        try{
            ErrorLog__c err = new ErrorLog__c();
            List<Attachment> attachmentList = new List<Attachment>();
            err.NameofArtifact__c = className;
            if(ex !=null){
                err.ExceptionMessage__c = 'Error Message: '+ ex.getMessage()+' | Stack Trace: '+ ex.getStackTraceString(); 
                err.ExceptionType__c = ex.getTypeName();
            } 
            err.Service_Name__c = methodName;
            err.MethodName__c = methodName;
            err.SFDCRecordReference__c = recordReference;
            /*  if(requestBody.length() > 131072){
                requestBody = requestBody.substring(0, 131070);
            }
            if(responseBody.length() > 131072){
                responseBody = responseBody.substring(0, 131070);
            } */
           // err.RequestBody__c = requestBody;
           // err.Response_Body__c = responseBody;
            err.URL__c = endPointURL;
            err.ErrorAPI__c = false;
            insert err;
            
            if(String.isNotEmpty(requestBody)){
                Attachment attachment = new Attachment();
                attachment.Body = Blob.valueOf(requestBody);
                attachment.Name = String.valueOf('request.txt');
                attachment.ParentId = err.Id; 
                attachmentList.add(attachment);
            }
           
            if(String.isNotEmpty(responseBody)){
                Attachment attachment = new Attachment();
                attachment.Body = Blob.valueOf(responseBody);
                attachment.Name = String.valueOf('response.txt');
                attachment.ParentId = err.Id; 
                attachmentList.add(attachment);
            }
            
            if(attachmentList.size()>0){
                insert attachmentList;
            }

        }
        Catch(Exception e){
         ErrorLogCreater_cls.apexDebugLogger(e, 'ErrorLog' , 'apexDebugLoggerForAPICallout' , recordReference );
        }
    }
    
}