LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>To store all the application exception We are using this Object. This will be helpful when an exception occurs in the future, background apex jobs, or flows.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Er-{0000000}</displayFormat>
        <label>Error Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/ErrorAPI__c.field-meta.xml
<CustomField>
    <fullName>ErrorAPI__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is useful for Showing the Detail Page through Dynamic Form</inlineHelpText>
    <label>Error/API</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <inlineHelpText>This is the brief description of the problem or situation involved.</inlineHelpText>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <inlineHelpText>The type of error occurred. Helpful in resolving it.</inlineHelpText>
    <label>Exception Type</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <inlineHelpText>The Name of Method/Function of the Artifact in which the exception has occurred.</inlineHelpText>
    <label>Method/Function Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/NameofArtifact__c.field-meta.xml
<CustomField>
    <fullName>NameofArtifact__c</fullName>
    <inlineHelpText>This Shows the Name of Apex Class, Flow , Apex Jobs In which exception occurred.</inlineHelpText>
    <label>Name of Artifact</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ErrorLog__c/fields/SFDCRecordReference__c.field-meta.xml
<CustomField>
    <fullName>SFDCRecordReference__c</fullName>
    <inlineHelpText>The exception has occurred on this Record Id.</inlineHelpText>
    <label>SFDC Record Reference</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Successor_User__c.field-meta.xml
<CustomField>
    <fullName>Successor_User__c</fullName>
    <label>Successor User</label>
    <relationshipName>Successor_User</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User_Exit_Object_Mapping__mdt/User_Exit_Object_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>User Exit Object Mapping</label>
    <pluralLabel>User Exit Object Mapping</pluralLabel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/User_Exit_Object_Mapping__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User_Exit_Object_Mapping__mdt/fields/WHERE_Condition__c.field-meta.xml
<CustomField>
    <fullName>WHERE_Condition__c</fullName>
    <label>WHERE Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/UserExit_Batch.cls
/*
Name		:	UserExit_Batch
Author		:	Arpit vijayvergiya @ Techmatrix
Date		:	25 Sept 2023
Description	:	Transfer ownership of Records from the employee leaving the company to different Employee
Last Modified By : Suraj Kumar 27 Oct 2023
*/
global class UserExit_Batch implements Database.Batchable<sObject>, Database.Stateful {
    global Integer sequence;
    global User_Exit_Object_Mapping__mdt userExitMapping;
    global User objUser;
    global UserExit_Batch(User objUser){
        this.sequence = 1;
        this.objUser = objUser;
        this.userExitMapping = [SELECT Id,Sequence__c, Object_API_Name__c, Field_API_Name__c, WHERE_Condition__c FROM User_Exit_Object_Mapping__mdt WHERE Sequence__c =: this.sequence];
    }
    
    global UserExit_Batch(Integer seq,User_Exit_Object_Mapping__mdt userExitMapping, User objUser){
        this.sequence = seq;
        this.userExitMapping = userExitMapping;
        this.objUser = objUser;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('start method');
        System.debug('UE-----> '+this.userExitMapping);

        String Dynamicquery = 'Select id,'+this.userExitMapping.Field_API_Name__c +
            ' FROM '+this.userExitMapping.Object_API_name__c + ' WHERE '+ this.userExitMapping.Field_API_Name__c +' = '+'\''+String.escapeSingleQuotes(this.objUser.Id)+'\'' ;

        if(String.isNotBlank(this.userExitMapping.WHERE_Condition__c)){
            System.debug('this.userExitMapping --> ' + this.userExitMapping);
            Dynamicquery += ' AND ' + this.userExitMapping.WHERE_Condition__c;
        }
        
        System.debug('Dynamicquery --> ' + Dynamicquery);
        return Database.getQueryLocator(Dynamicquery );
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        System.debug('scope : ' + scope);
        String errorValue;
        List<ErrorLog__c> errorLogList =new List<ErrorLog__c>();
        try{
        List<sObject> UpdateList = new List<Sobject>();
        for(Sobject objRec : scope){
            objRec.put(this.userExitMapping.Field_API_Name__c, this.objUser.Successor_User__c);
            UpdateList.add(objRec);
        }
        if(UpdateList.size()>0){
            System.debug('items to update : ' + updateList);
            Database.SaveResult[] srList = Database.update(UpdateList, false);
            for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                    // This condition will be executed for successful records and will fetch
                    // the ids of successful records
                    System.debug('Successfully updated: ' + sr.getId());
                } else {
                    
                    // This condition will be executed for failed records
                    Database.Error objErr = sr.getErrors()[0];
                    System.debug('The following error has occurred.');
                    System.debug(': Message ' + objErr.getMessage());
                    System.debug('object field which are affected by the error:' 
                                 + objErr.getFields());
                    ErrorLog__c err = new ErrorLog__c();
                    err.NameofArtifact__c = 'UserExit_Batch';
                    err.ExceptionMessage__c = 'Error Message: '+ objErr.getMessage()+' | Fields: '+objErr.getFields();
                    //err.ExceptionType__c = objErr.getTypeName();
                    err.MethodName__c = 'execute';
                    err.SFDCRecordReference__c =String.valueOf(sr.getId()) ;
                    err.ErrorAPI__c = true;
                    errorLogList.add(err);
                }
            }
            insert errorLogList;
        } 
        }
        catch(Exception e){
           System.debug('Exception Error'+e.getMessage());
        }
    }
    global void finish(Database.BatchableContext BC) {
        this.Sequence +=1;
        List<User_Exit_Object_Mapping__mdt> lstOfUserExitMapping = [SELECT Id,Sequence__c, Object_API_Name__c, Field_API_Name__c, WHERE_Condition__c FROM User_Exit_Object_Mapping__mdt WHERE Sequence__c =: this.sequence];
        if(lstOfUserExitMapping.size() > 0){
           Database.executeBatch(new UserExit_Batch(this.Sequence,lstOfUserExitMapping[0],this.objUser)); 
        }
        //Database.executeBatch(new RecursiveBatch(this.Sequence));
        
    }
    
}