LinKreta_POC_Repository/force-app/main/default/objects/WCGT_Master__c/WCGT_Master__c.object-meta.xml
<CustomObject>
    <label>WCGT Master</label>
    <nameField>
        <displayFormat>WCGT-{0000}</displayFormat>
        <label>WCGT Master Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WCGT Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/WCGT_Master__c/fields/Para_Desc__c.field-meta.xml
<CustomField>
    <fullName>Para_Desc__c</fullName>
    <label>Para Desc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/WCGT_Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>WCGT Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Type</fullName>
            </value>
            <value>
                <fullName>Entity Type</fullName>
            </value>
            <value>
                <fullName>Tot Revenue</fullName>
            </value>
            <value>
                <fullName>Tot Emp No</fullName>
            </value>
            <value>
                <fullName>Rel Office</fullName>
            </value>
            <value>
                <fullName>Country HQ</fullName>
            </value>
            <value>
                <fullName>Sector</fullName>
            </value>
            <value>
                <fullName>Sub-Sector</fullName>
            </value>
            <value>
                <fullName>Category CX GX</fullName>
            </value>
            <value>
                <fullName>CountryId</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
            <value>
                <fullName>Sub Industry</fullName>
            </value>
            <value>
                <fullName>StateId</fullName>
            </value>
            <value>
                <fullName>Corridor</fullName>
            </value>
            <value>
                <fullName>Country Corridor</fullName>
            </value>
            <value>
                <fullName>Enquiry Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/WCGTMasterServiceTest.cls
/*Author Name :  Muskan Soni
*/
@istest
public class WCGTMasterServiceTest {
    @testSetup
    public static void testData(){
        WCGT_Master__c wcgtObj = new WCGT_Master__c();
        wcgtObj.Type__c ='Client Type';
        wcgtObj.Para_Desc__c='80.0-90.0';
        insert wcgtObj;
        
        WCGT_Master__c wcgtObj1 = new WCGT_Master__c();
        wcgtObj1.Type__c ='Client Type';
        wcgtObj1.Para_Desc__c='80.0-70.0';
        insert wcgtObj1;
        
    }
    
    @istest
    public static void test(){
        list <WCGT_Master__c> wcgtList =[select id,Type__c,name,Para_Desc__c from WCGT_Master__c];
        set<String> wgtValuesSet = new set <String>();
        map <String,String> wgtMap = new map<String,String>();
        for(WCGT_Master__c obj : wcgtList){
            wgtMap.put(obj.Type__c,obj.Para_Desc__c);
            wgtValuesSet.add(obj.Para_Desc__c);
        }
        WCGTMasterService.getWCGTRecord(wcgtList[0].Para_Desc__c,wcgtList[0].Type__c);
        WCGTMasterService.getWCGTRecord(wgtValuesSet);
        WCGTMasterService.getWCGTValueMap(wgtValuesSet);
        WCGTMasterService.getWCGTIdByMap(wgtMap);
    }
     @istest
    public static void test1(){
        list <WCGT_Master__c> wcgtList =[select id,Type__c,name,Para_Desc__c from WCGT_Master__c where Para_Desc__c='80.0-70.0' ];
        set<String> wgtValuesSet = new set <String>();
        wgtValuesSet.add('');
        WCGTMasterService.getWCGTRecord('','');
        WCGTMasterService.getWCGTValueMap(wgtValuesSet);
       WCGTMasterService.getWCGTId('80.0',wcgtList[0].Type__c);
    }
    //Phase-1 Rakesh
    @istest
    public static void test2(){
        list <WCGT_Master__c> wcgtList =[select id,Type__c,name,Para_Desc__c from WCGT_Master__c where Para_Desc__c='80.0-70.0' ];
        wcgtList[0].Para_Desc__c = 'above';
        wcgtList[0].Type__c = '';
        update wcgtList;
        set<String> wgtValuesSet = new set <String>();
        wgtValuesSet.add('');
        map <String,String> wgtMap = new map<String,String>();
        for(WCGT_Master__c obj : wcgtList){
            wgtMap.put(obj.Type__c,obj.Para_Desc__c);
            wgtValuesSet.add(obj.Para_Desc__c);
        }
        WCGTMasterService.getWCGTIdByMap(wgtMap);
        WCGTMasterService.getWCGTRecord('','');
        WCGTMasterService.getWCGTValueMap(wgtValuesSet);
       WCGTMasterService.getWCGTId('80.0',wcgtList[0].Type__c);
    }

}