LinKreta_POC_Repository/force-app/main/default/objects/OrgAvailabilityMonitor__c/OrgAvailabilityMonitor__c.object-meta.xml
<CustomObject>
    <description>This Custom Object is created to store the Availability Monitoring URLs for various Portfolio/Program/Features</description>
    <label>OrgAvailabilityMonitor</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgAvailabilityMonitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/OrgAvailabilityMonitor__c/fields/Feature_Name__c.field-meta.xml
<CustomField>
    <fullName>Feature_Name__c</fullName>
    <label>Feature Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/OrgAvailabilityMonitor__c/fields/Monitoring_URL__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_URL__c</fullName>
    <label>Monitoring URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/OrgAvailabilityMonitor__c/fields/Portfolio_Name__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Name__c</fullName>
    <label>Portfolio Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/OrgAvailabilityMonitorTest.cls
@isTest
private with sharing class OrgAvailabilityMonitorTest {

    @isTest static void testGetOrgAvailabilityMonitors() {

        // Create some test data
        List<OrgAvailabilityMonitor__c> orgAvailabilityMonitors = new List<OrgAvailabilityMonitor__c>();

        for (Integer i = 0; i < 10; i++) {
            orgAvailabilityMonitors.add(new OrgAvailabilityMonitor__c(Feature_Name__c = 'Feature Name: ' + i, 
                                                                        Monitoring_URL__c = 'Monitoring_URL_' + i + '.html', 
                                                                        Name = 'Program Name ' + i, 
                                                                        Portfolio_Name__c = 'Portfolio Name ' + i));
        }

        insert orgAvailabilityMonitors;

        // Invoke the method to test
        List<OrgAvailabilityMonitor__c> result = OrgAvailabilityMonitor.getOrgAvailabilityMonitors();

        // Verify the result
        System.assertEquals(10, result.size(), 'The number of Org Availability Monitors should be 10');

        for (Integer i = 0; i < 10; i++) {
            System.assertEquals(orgAvailabilityMonitors[i].Id, result[i].Id, 'The OrgAvailabilityMonitor Id should match');
            System.assertEquals(orgAvailabilityMonitors[i].Feature_Name__c, result[i].Feature_Name__c, 'The Feature_Name__c should match');
            System.assertEquals(orgAvailabilityMonitors[i].Monitoring_URL__c, result[i].Monitoring_URL__c, 'The Monitoring_URL__c should match');
            System.assertEquals(orgAvailabilityMonitors[i].Name, result[i].Name, 'The Program Name should match');
            System.assertEquals(orgAvailabilityMonitors[i].Portfolio_Name__c, result[i].Portfolio_Name__c, 'The Portfolio_Name__c should match');
        }
    }
}