LinKreta_POC_Repository/force-app/main/default/objects/Client_News__c/Client_News__c.object-meta.xml
<CustomObject>
    <label>Client News</label>
    <nameField>
        <label>Client News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Client_News__c/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <label>Alert</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_News__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client News</relationshipLabel>
    <relationshipName>Client_Newss</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_News__c/fields/convictedDirectors__c.field-meta.xml
<CustomField>
    <fullName>convictedDirectors__c</fullName>
    <label>Convicted Directors</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_News__c/fields/ExternalDataSource__c.field-meta.xml
<CustomField>
    <fullName>ExternalDataSource__c</fullName>
    <description>Record creation method</description>
    <label>External Data Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>CapIQ</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_News__c/fields/IQ_KEY_DEV_HEADLINE__c.field-meta.xml
<CustomField>
    <fullName>IQ_KEY_DEV_HEADLINE__c</fullName>
    <label>IQ_KEY_DEV_HEADLINE</label>
    <length>500</length>
    <type>Html</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_News__c/fields/IQ_KEY_DEV_TYPE__c.field-meta.xml
<CustomField>
    <fullName>IQ_KEY_DEV_TYPE__c</fullName>
    <label>IQ_KEY_DEV_TYPE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_News__c/fields/Key_Development_Date__c.field-meta.xml
<CustomField>
    <fullName>Key_Development_Date__c</fullName>
    <label>Key Development Date</label>
    <type>Date</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_News__c/fields/remarks_details__c.field-meta.xml
<CustomField>
    <fullName>remarks_details__c</fullName>
    <label>Remarks/details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_News__c/fields/severity__c.field-meta.xml
<CustomField>
    <fullName>severity__c</fullName>
    <label>Severity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/KeyAlertAndDevForClietControllerTest.cls
@isTest
private class KeyAlertAndDevForClietControllerTest {
     @testSetup static void testData(){
        User userRecord = TestDataFactory.createUserRecord();
        insert userRecord;
        
        Account accRecord  = TestDataFactory.createAccountRecordDetailed();
        insert accRecord;
         
         Client_News__c client_newsObj = new Client_News__c(
	Name = 'M&A Transaction Announcements',
	IQ_KEY_DEV_HEADLINE__c = 'Crompton Greaves Consumer Electricals Limited (NSEI:CROMPTON) entered into a scheme of arrangement to acquire the remaining 19% stake in Butterfly Gandhimathi Appliances Limited (BSE:517421)',
	IQ_KEY_DEV_TYPE__c = 'M&A Transaction Announcements',
	Key_Development_Date__c = system.today(),
	Client__c = accRecord.Id,
	ExternalDataSource__c = 'CapIQ');
 insert client_newsObj;
         
    }
    @isTest
    static void testGetClientNews() {
        
        List<Client_News__c> clientNewsList = [SELECT Id, Name ,Client__c, IQ_KEY_DEV_HEADLINE__c,IQ_KEY_DEV_TYPE__c,Key_Development_Date__c,Alert__c, Case_Number__c,convictedDirectors__c,remarks_details__c,severity__c From Client_News__c];
        String recordId = clientNewsList[0].Client__c;
        List<Client_News__c> lstclientNews = KeyAlertAndDevelopmentForClietController.getClientNews(recordId);
        KeyAlertAndDevelopmentForClietController KeyAlertAndDevelopmentForClietControllerObj = new KeyAlertAndDevelopmentForClietController();
        
     //   System.assertEquals(1, lstCase.size());
    }
}