LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Client Account</fullName>
                <default>true</default>
                <label>Client Account</label>
            </value>
            <value>
                <fullName>Apex Chambers</fullName>
                <isActive>false</isActive>
                <label>Apex Chambers</label>
            </value>
            <value>
                <fullName>Bilateral Chamber</fullName>
                <isActive>false</isActive>
                <label>Bilateral Chamber</label>
            </value>
            <value>
                <fullName>Existing Client</fullName>
                <isActive>false</isActive>
                <label>Existing Client</label>
            </value>
            <value>
                <fullName>Key Account - CX</fullName>
                <isActive>false</isActive>
                <label>Key Account - CX</label>
            </value>
            <value>
                <fullName>Key Account - GX</fullName>
                <isActive>false</isActive>
                <label>Key Account - GX</label>
            </value>
            <value>
                <fullName>New Client</fullName>
                <isActive>false</isActive>
                <label>New Client</label>
            </value>
            <value>
                <fullName>Non Key Client</fullName>
                <isActive>false</isActive>
                <label>Non Key Client</label>
            </value>
            <value>
                <fullName>Regional &amp; Other Chamber</fullName>
                <isActive>false</isActive>
                <label>Regional &amp; Other Chamber</label>
            </value>
            <value>
                <fullName>Sectoral Chamber</fullName>
                <isActive>false</isActive>
                <label>Sectoral Chamber</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Account_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Client_Account_Sub_Category__c</fullName>
    <label>Client Account Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Young CSL</fullName>
            </value>
            <value>
                <fullName>Client Account</fullName>
            </value>
            <value>
                <fullName>Former Key account</fullName>
                <isActive>false</isActive>
                <label>Former Key account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Category__c.field-meta.xml
<CustomField>
    <fullName>Client_Category__c</fullName>
    <label>Account Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GX - Platinum</fullName>
            </value>
            <value>
                <fullName>GX - Gold</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
                <isActive>false</isActive>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Non Key Account</fullName>
                <isActive>false</isActive>
                <label>Non Key Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_reason_if_inactive__c.field-meta.xml
<CustomField>
    <fullName>Client_reason_if_inactive__c</fullName>
    <label>Client reason (if inactive)</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/ClientStatus__c.field-meta.xml
<CustomField>
    <fullName>ClientStatus__c</fullName>
    <description>This field will describe the status of Client.</description>
    <inlineHelpText>This field will describe the status of Client.</inlineHelpText>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/CoCSL__c.field-meta.xml
<CustomField>
    <fullName>CoCSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Domestic_Ultimate_Owner__c.field-meta.xml
<CustomField>
    <fullName>Domestic_Ultimate_Owner__c</fullName>
    <label>Domestic Ultimate Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Entity_Type_Master__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Type</label>
    <referenceTo>Entity_Type_Master__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Global_Ultimate_Owner__c.field-meta.xml
<CustomField>
    <fullName>Global_Ultimate_Owner__c</fullName>
    <label>Global Ultimate Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Key_Account_360__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_360__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Key Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GT Client Groups</relationshipLabel>
    <relationshipName>Clients2</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/LegalEntityType__c.field-meta.xml
<CustomField>
    <fullName>LegalEntityType__c</fullName>
    <label>Legal Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public Listed</fullName>
            </value>
            <value>
                <fullName>Pvt. Listed</fullName>
            </value>
            <value>
                <fullName>Public Not Listed</fullName>
            </value>
            <value>
                <fullName>Pvt. Not Listed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Entity_Type_Master__c/Entity_Type_Master__c.object-meta.xml
<CustomObject>
    <label>Entity Type Master</label>
    <nameField>
        <label>Entity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Type Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/classes/SendEmailOnFieldUpdate.cls
/*
* @Name: SendEmailToCTM
* @Author: Bhavishya Basantwani
* @Description: This class is used for Send Email and Notification on Field Update of Client.
* @Date: 31-July-23
*/
public class SendEmailOnFieldUpdate {
    
    @InvocableMethod()
    public Static void FieldUpdate(List<ActionRequest> getInfo){
        system.debug('getInfo'+getInfo);
        system.debug('innn');
        List<String> fieldChanges = new List<String>();
        // Checking For Fields Not Equal To prior record and collect thier Label 
        if(getInfo[0].PriorRecord.Name != getInfo[0].PresentRecord.Name){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Name');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        
        if(getInfo[0].PriorRecord.ParentId != getInfo[0].PresentRecord.ParentId){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('ParentId');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.GT_Client_Group__c != getInfo[0].PresentRecord.GT_Client_Group__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('GT_Client_Group__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.Key_Account_360__c != getInfo[0].PresentRecord.Key_Account_360__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Key_Account_360__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.CSL__c != getInfo[0].PresentRecord.CSL__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('CSL__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.CoCSL__c != getInfo[0].PresentRecord.CoCSL__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('CoCSL__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.Client_reason_if_inactive__c != getInfo[0].PresentRecord.Client_reason_if_inactive__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Client_reason_if_inactive__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.LegalEntityType__c != getInfo[0].PresentRecord.LegalEntityType__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('LegalEntityType__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.Domestic_Ultimate_Owner__c != getInfo[0].PresentRecord.Domestic_Ultimate_Owner__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Domestic_Ultimate_Owner__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.Global_Ultimate_Owner__c != getInfo[0].PresentRecord.Global_Ultimate_Owner__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Global_Ultimate_Owner__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.Client_Category__c != getInfo[0].PresentRecord.Client_Category__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Client_Category__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        // if(getInfo[0].PriorRecord.GSTIN__c != getInfo[0].PresentRecord.GSTIN__c){
        //     SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('GSTIN__c');
        //     fieldChanges.add(field.getDescribe().getLabel());
        // }
        if(getInfo[0].PriorRecord.Client_Account_Sub_Category__c != getInfo[0].PresentRecord.Client_Account_Sub_Category__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Client_Account_Sub_Category__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.AccountType__c != getInfo[0].PresentRecord.AccountType__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Client_Category__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.ClientStatus__c != getInfo[0].PresentRecord.ClientStatus__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('ClientStatus__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        if(getInfo[0].PriorRecord.Entity_Type_Master__c != getInfo[0].PresentRecord.Entity_Type_Master__c){
            SObjectField field = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Entity_Type_Master__c');
            fieldChanges.add(field.getDescribe().getLabel());
        }
        // String FinalfieldChangesString ;
        string fieldChangesString;
        set<String> setOfIds = new set<String>();
        set<String> activeUserIds = new set<String>();
        system.debug('fieldchange'+fieldChanges);
        if(fieldChanges.size()>0){
            String notificationTypeApiName = 'NewClientOwnerChanged';
            // Added by Rajat for Email Template related changes
            Map<Id,String> mapUserIdWithName = new Map<Id,String>();
            List<User> userList = [SELECT ID,Name FROM USER WHERE isActive = true AND ID IN: getInfo[0].RecipentId];
            if(userList.size() > 0){
                for(User usr : userList){
                    mapUserIdWithName.put(usr.Id,usr.Name);
                }
            }
            List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
            Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(getInfo[0].TemlateId, getInfo[0].recipentid[0],  getInfo[0].PriorRecord.Id);
            for(ActionRequest accReqObj : getInfo){
                For(integer i=0 ; i<accReqObj.RecipentId.size(); i++){
                    Messaging.SingleEmailMessage objMail = new Messaging.SingleEmailMessage();
                    string[] to = new string[] {accReqObj.EmailAddress[i]};
                    objMail.setToAddresses(to);
                    String body = mail.getHtmlBody();
                    String Subject = mail.getSubject();
                    fieldChangesString = string.join(fieldChanges,',');
                    body = body.replace('{fields.name}',fieldChangesString);
                    if(mapUserIdWithName.containsKey(accReqObj.RecipentId[i])){
                        body = body.replace('[Name]',mapUserIdWithName.get(accReqObj.RecipentId[i]));
                    }
                    objMail.setHtmlBody(body);
                    objMail.setSubject(Subject);
                    List<OrgWideEmailAddress> orgWideEmails =  [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE DisplayName = 'Linkreta' LIMIT 1];
                    if(orgWideEmails != null){
                        objMail.setOrgWideEmailAddressId(orgWideEmails[0].Id);
                    }
                    objMail.setSaveAsActivity(false);
                    emailList.add(objMail);
                    setOfIds.add(accReqObj.recipentid[i]);
                }
            }
            
            Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList);
            system.debug('resultsresults'+results);
            
            CustomNotificationType notificationType = 
                [SELECT Id, DeveloperName 
                 FROM CustomNotificationType 
                 WHERE DeveloperName='NewClientOwnerChanged'];
            
            String NotificationAndTitle = 'There has been a change in the '+ fieldChangesString + ' for ' + getInfo[0].PriorRecord.Name;
            Messaging.CustomNotification notification = new Messaging.CustomNotification();
            
            // Set the contents for the notification
            notification.setTitle(NotificationAndTitle);
            notification.setBody(NotificationAndTitle);
            
            // Set the notification type and target
            notification.setNotificationTypeId(notificationType.Id);
            notification.setTargetId(getInfo[0].PriorRecord.Id);
            
            // Actually send the notification


            for (User userObj : [SELECT Id, Name, isActive FROM User WHERE isActive = true AND Id IN : setOfIds]) {
                activeUserIds.add(userObj.Id);
            }
            
            if (activeUserIds != null && activeUserIds.size() > 0) {
                System.debug('activeUserIds : ' + activeUserIds);
                notification.send(activeUserIds);
            }
            
            
        }
    }
    
    public class ActionRequest{
        @InvocableVariable
        public string TemlateId;
        @InvocableVariable
        public List<string> RecipentId;
        @InvocableVariable
        public List<string> EmailAddress;
        @InvocableVariable
        public string UserName;
        @InvocableVariable
        public Account PriorRecord;
        @InvocableVariable
        public Account PresentRecord;    
    }
}