LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Client Account</fullName>
                <default>true</default>
                <label>Client Account</label>
            </value>
            <value>
                <fullName>Apex Chambers</fullName>
                <isActive>false</isActive>
                <label>Apex Chambers</label>
            </value>
            <value>
                <fullName>Bilateral Chamber</fullName>
                <isActive>false</isActive>
                <label>Bilateral Chamber</label>
            </value>
            <value>
                <fullName>Existing Client</fullName>
                <isActive>false</isActive>
                <label>Existing Client</label>
            </value>
            <value>
                <fullName>Key Account - CX</fullName>
                <isActive>false</isActive>
                <label>Key Account - CX</label>
            </value>
            <value>
                <fullName>Key Account - GX</fullName>
                <isActive>false</isActive>
                <label>Key Account - GX</label>
            </value>
            <value>
                <fullName>New Client</fullName>
                <isActive>false</isActive>
                <label>New Client</label>
            </value>
            <value>
                <fullName>Non Key Client</fullName>
                <isActive>false</isActive>
                <label>Non Key Client</label>
            </value>
            <value>
                <fullName>Regional &amp; Other Chamber</fullName>
                <isActive>false</isActive>
                <label>Regional &amp; Other Chamber</label>
            </value>
            <value>
                <fullName>Sectoral Chamber</fullName>
                <isActive>false</isActive>
                <label>Sectoral Chamber</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Channel_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_Type__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audit Client</fullName>
                <label>Channel 1</label>
            </value>
            <value>
                <fullName>Non audit client</fullName>
                <label>Channel 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Category__c.field-meta.xml
<CustomField>
    <fullName>Client_Category__c</fullName>
    <label>Account Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GX - Platinum</fullName>
            </value>
            <value>
                <fullName>GX - Gold</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
                <isActive>false</isActive>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Non Key Account</fullName>
                <isActive>false</isActive>
                <label>Non Key Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_reason_if_inactive__c.field-meta.xml
<CustomField>
    <fullName>Client_reason_if_inactive__c</fullName>
    <label>Client reason (if inactive)</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Category__c</fullName>
    <label>Key Account Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GX - Platinum</fullName>
            </value>
            <value>
                <fullName>GX - Gold</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
                <isActive>false</isActive>
                <label>CX</label>
            </value>
            <value>
                <fullName>Client Account</fullName>
                <isActive>false</isActive>
                <label>Client Account</label>
            </value>
            <value>
                <fullName>Formal Key account</fullName>
                <isActive>false</isActive>
                <label>Formal Key account</label>
            </value>
            <value>
                <fullName>Sub Category</fullName>
                <isActive>false</isActive>
                <label>Sub Category</label>
            </value>
            <value>
                <fullName>Young CSL</fullName>
                <isActive>false</isActive>
                <label>Young CSL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/ClientStatus__c.field-meta.xml
<CustomField>
    <fullName>ClientStatus__c</fullName>
    <description>This field will describe the status of Client.</description>
    <inlineHelpText>This field will describe the status of Client.</inlineHelpText>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/CoCSL__c.field-meta.xml
<CustomField>
    <fullName>CoCSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Key_Account_360__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_360__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Key Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GT Client Groups</relationshipLabel>
    <relationshipName>Clients2</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Mid Market</fullName>
            </value>
            <value>
                <fullName>PIE Audit</fullName>
            </value>
            <value>
                <fullName>Channels - GCC</fullName>
            </value>
            <value>
                <fullName>Channels - Law Firms</fullName>
            </value>
            <value>
                <fullName>Channels - OPC</fullName>
            </value>
            <value>
                <fullName>Channels - PE/VC</fullName>
            </value>
            <value>
                <fullName>Digital Natives</fullName>
            </value>
            <value>
                <fullName>Large Corporates</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
                <isActive>false</isActive>
                <label>Channel</label>
            </value>
            <value>
                <fullName>DGC</fullName>
                <isActive>false</isActive>
                <label>DGC</label>
            </value>
            <value>
                <fullName>Large Corporate</fullName>
                <isActive>false</isActive>
                <label>Large Corporate</label>
            </value>
            <value>
                <fullName>Large Private</fullName>
                <isActive>false</isActive>
                <label>Large Private</label>
            </value>
            <value>
                <fullName>Largest Listed</fullName>
                <isActive>false</isActive>
                <label>Largest Listed</label>
            </value>
            <value>
                <fullName>Listed</fullName>
                <isActive>false</isActive>
                <label>Listed</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>PE Fund</fullName>
                <isActive>false</isActive>
                <label>PE Fund</label>
            </value>
            <value>
                <fullName>PE Investee</fullName>
                <isActive>false</isActive>
                <label>PE Investee</label>
            </value>
            <value>
                <fullName>S M Private</fullName>
                <isActive>false</isActive>
                <label>S M Private</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/classes/ClientByGtClientGroupTest.cls
/*
* @Name: ClientByGtClientGroupTest
* @Author: Bhavishya Basantwani
* @Date: 9-dec-23 
*/

@isTest
public class ClientByGtClientGroupTest {
    @testSetup static void dataCreation() {
        Id clientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        system.debug('clientRecordTypeId'+clientRecordTypeId);
        Id gtCLientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GT Client Group').getRecordTypeId();        
        Id KeyAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Key Account').getRecordTypeId();
        
        
        Account KeyAcc = TestDataFactory.createAccountRecord();
        KeyAcc.RecordTypeId = KeyAccountRecordTypeId;
        // KeyAcc.Client_Category__c = 'Key Account - GX';
        // KeyAcc.Client_Sub_Category__c = 'Gx - Gold';
        KeyAcc.Channel_Type__c ='Audit Client';
        KeyAcc.Segment__c = 'Government';
        KeyAcc.Industry__c ='Agriculture';
        insert KeyAcc;
        
        AccountTeamMember CTMFifth = TestDataFactory.createAccountTeamMember(KeyAcc.Id);
        CTMFifth.TeamMemberRole = 'Key Account – CSL';
        CTMFifth.ContactAccessLevel = 'Read';
        CTMFifth.CaseAccessLevel = 'Edit';
        CTMFifth.OpportunityAccessLevel ='Edit';
        CTMFifth.AccountAccessLevel = 'Read';
        insert CTMFifth;
        
        Account GtAcc = TestDataFactory.createAccountRecord();
        GtAcc.RecordTypeId = gtCLientRecordTypeId;
        GtAcc.Key_Account_360__c = KeyAcc.Id;
        insert GtAcc;
        
        Account GtAcc1 = TestDataFactory.createAccountRecord();
        GtAcc1.Name = 'Name22';
        GtAcc1.RecordTypeId = gtCLientRecordTypeId;
        GtAcc.Key_Account_360__c = KeyAcc.Id;
        insert GtAcc1;
        
        Id UserId = UserInfo.getUserId() ;
        
        Account acc = TestDataFactory.createAccountRecord();
        
        acc.RecordTypeId = clientRecordTypeId;
        //acc.CSL__c = UserId;
        //acc.CoCSL__c = UserId;
        //acc.GSTIN__c = '00900';
        acc.Client_reason_if_inactive__c = 'testtttttt';
        acc.ClientStatus__c = 'Inactive';
        acc.GT_Client_Group__c = GtAcc.Id;
        acc.ClientAddress__City__s = 'Jaipur';
        acc.ClientAddress__CountryCode__s = 'IN';
        acc.ClientAddress__PostalCode__s = '789'; 
        acc.ClientAddress__StateCode__s = 'AS';
        acc.ClientAddress__Street__s = 'test,test';
        
        
        //acc.AccountType__c = 'Key Account';
        
        insert acc;
        
        Account acc1 = TestDataFactory.createAccountRecord();
        acc1.Name = 'Name44';
        acc1.RecordTypeId = clientRecordTypeId;
        acc1.CSL__c = UserId;
        acc1.CoCSL__c = UserId;
        //acc1.GSTIN__c = '0090067788';
        acc1.Client_reason_if_inactive__c = 'test';
        //acc1.GSTIN__c = '12345';
        acc1.ClientStatus__c = 'Active';
        acc1.GT_Client_Group__c = GtAcc1.Id;
        acc1.ClientAddress__City__s = 'Jaipur';
        acc1.ClientAddress__CountryCode__s = 'IN';
        acc1.ClientAddress__PostalCode__s = '789'; 
        acc1.ClientAddress__StateCode__s = 'AS';
        acc1.ClientAddress__Street__s = 'test,test';
        //acc1.AccountType__c = 'Key Account';
        
        insert acc1;
        
        /*  AccountTeamMember CTMFirst = TestDataFactory.createAccountTeamMember(acc.Id);
AccountTeamMember CTMSeond = TestDataFactory.createAccountTeamMember(acc.Id);
CTMseond.TeamMemberRole = 'Solution Expert';


insert CTMFirst;
insert CTMSeond;*/
    }
    
    @isTest static void getRecordTest() {
        Id clientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        system.debug('clientRecordTypeId'+clientRecordTypeId);
        Id gtCLientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GT Client Group').getRecordTypeId();        
        Id KeyAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Key Account').getRecordTypeId();
        
        List<Account> listOfAccountKey =  [SELECT Id,Name FROM Account Where RecordTypeId =:  KeyAccountRecordTypeId];
        List<Account> listOfAccountGtClient =  [SELECT Id,Name FROM Account Where RecordTypeId =: gtCLientRecordTypeId ];
        
       Map<String,List<Account>> MapOfClients =  ClientByGtClientGroup.getRecord(listOfAccountKey[0].Id);
       List<Account> listOfReturnAccount =  ClientByGtClientGroup.getRecordFilter(listOfAccountKey[0].Id,listOfAccountGtClient[0].Name);
        
        System.assertEquals(1 , MapOfClients.Size() , 'successfull');
        System.assertEquals(1 , listOfAccountKey.Size() , 'successfull');
    }
    
    
}