LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Client Account</fullName>
                <default>true</default>
                <label>Client Account</label>
            </value>
            <value>
                <fullName>Apex Chambers</fullName>
                <isActive>false</isActive>
                <label>Apex Chambers</label>
            </value>
            <value>
                <fullName>Bilateral Chamber</fullName>
                <isActive>false</isActive>
                <label>Bilateral Chamber</label>
            </value>
            <value>
                <fullName>Existing Client</fullName>
                <isActive>false</isActive>
                <label>Existing Client</label>
            </value>
            <value>
                <fullName>Key Account - CX</fullName>
                <isActive>false</isActive>
                <label>Key Account - CX</label>
            </value>
            <value>
                <fullName>Key Account - GX</fullName>
                <isActive>false</isActive>
                <label>Key Account - GX</label>
            </value>
            <value>
                <fullName>New Client</fullName>
                <isActive>false</isActive>
                <label>New Client</label>
            </value>
            <value>
                <fullName>Non Key Client</fullName>
                <isActive>false</isActive>
                <label>Non Key Client</label>
            </value>
            <value>
                <fullName>Regional &amp; Other Chamber</fullName>
                <isActive>false</isActive>
                <label>Regional &amp; Other Chamber</label>
            </value>
            <value>
                <fullName>Sectoral Chamber</fullName>
                <isActive>false</isActive>
                <label>Sectoral Chamber</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Pick_Record__c.field-meta.xml
<CustomField>
    <fullName>Pick_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pick Record</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/RelationshipOffice__c.field-meta.xml
<CustomField>
    <fullName>RelationshipOffice__c</fullName>
    <label>Relationship Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GT_Bengaluru</fullName>
            </value>
            <value>
                <fullName>GT_Bhopal</fullName>
            </value>
            <value>
                <fullName>GT_Chennai</fullName>
            </value>
            <value>
                <fullName>GT_Delhi</fullName>
            </value>
            <value>
                <fullName>GT_Hyderabad</fullName>
            </value>
            <value>
                <fullName>GT_Lucknow</fullName>
            </value>
            <value>
                <fullName>GT_Mumbai</fullName>
            </value>
            <value>
                <fullName>GT_Noida</fullName>
            </value>
            <value>
                <fullName>GT_One</fullName>
            </value>
            <value>
                <fullName>GT_Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Key_Account.recordType-meta.xml
<RecordType>
    <fullName>Key_Account</fullName>
    <active>true</active>
    <label>Key Account</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/BOD_Flag__c.field-meta.xml
<CustomField>
    <fullName>BOD_Flag__c</fullName>
    <label>BOD Flag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Client_Contact_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact_Record_Type__c</fullName>
    <description>This field contains record type of associated client record.</description>
    <label>Client Contact Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Linkedin_URL__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_URL__c</fullName>
    <label>Linkedin URL</label>
    <type>Url</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Pick_Record__c.field-meta.xml
<CustomField>
    <fullName>Pick_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pick Record</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/RelationshipOffice__c.field-meta.xml
<CustomField>
    <fullName>RelationshipOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Office</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/SendEmailFromFlowTest.cls
@isTest
public class SendEmailFromFlowTest {
	@isTest
    public static void sendEmailTest(){
        
        Account keyAccount =TestDataFactory.createAccountRecord();
        keyAccount.Name ='testKey Account team';
        keyAccount.RecordTypeId =   Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ConstantUtility.KEY_ACCOUNT).getRecordTypeId();
        keyAccount.AccountType__c ='Key Client';
        keyAccount.Status__c='Active';
        insert keyAccount;
        
        Contact contactRecord = TestDataFactory.createContact();
        contactRecord.FirstName = 'test facontactsfa';
        contactRecord.LastName = 'test contact';
        contactRecord.AccountId = keyAccount.Id;
        contactRecord.Linkedin_URL__c = 'www.google.com';
        contactRecord.MobilePhone = '9876543210';
        contactRecord.Email = 'test@gmail.com';
        contactRecord.Designation__c = 'CEO';
        contactRecord.Salutation = 'Mr.';
        contactRecord.pi__campaign__c = 'Pratham campaign';
        contactRecord.Client_Location__City__s = 'TEST';
        contactRecord.Client_Location__CountryCode__s = 'US';
        contactRecord.Client_Location__PostalCode__s = '121002';
        contactRecord.Client_Location__StateCode__s = 'AL';
        contactRecord.Client_Location__Street__s = 'Test, street';
        contactRecord.Pick_Record__c = false;
        contactRecord.BOD_Flag__c = 'NO';
        contactRecord.Client_Contact_Record_Type__c = 'Client';
     //   contactRecord.RelationshipOffice__c = locationRecord.Id;
        insert contactRecord;
        
        // Create a test EmailTemplate
        EmailTemplate validEmailTemplate;
            System.runAs(new User(Id = UserInfo.getUserId())) {
                validEmailTemplate  = new EmailTemplate();
                validEmailTemplate.isActive = true;
                validEmailTemplate.Name = 'Email_Test_Template';
                validEmailTemplate.DeveloperName = 'Email_Test_Template';
                validEmailTemplate.TemplateType = 'Text';
                validEmailTemplate.FolderId = UserInfo.getUserId();
                
                UPsert validEmailTemplate;
            }
       // Job_TestDataFactory.Wrapper enquiryAndJob = Job_TestDataFactory.createJob();
        SendEmailFromFlow.InputWrapper inputWrapper = new SendEmailFromFlow.InputWrapper();
        inputWrapper.recipientIds = new List<Id>{UserInfo.getUserId()};
        inputWrapper.emailTemplateName = 'Email_Test_Template';
        inputWrapper.whatId = contactRecord.Id; 
        List<SendEmailFromFlow.InputWrapper> inputWrappers = new List<SendEmailFromFlow.InputWrapper>{
            inputWrapper
        };
        // Call the sendEmails method
        Test.startTest();
        SendEmailFromFlow emailObj = new SendEmailFromFlow();
        SendEmailFromFlow.sendEmails(inputWrappers);
        SendEmailFromFlow.getContact();
       /* try{
            SendEmailFromFlow.deleteContact(contactRecord.Id);
        	
        }catch(Exception e){
            
        }*/
        Test.stopTest();
    }
}