LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Account_Plan_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Status__c</fullName>
    <label>Account Plan Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending NSL Approval</fullName>
            </value>
            <value>
                <fullName>NSL Approved</fullName>
            </value>
            <value>
                <fullName>NSL Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Client Account</fullName>
                <default>true</default>
                <label>Client Account</label>
            </value>
            <value>
                <fullName>Apex Chambers</fullName>
                <isActive>false</isActive>
                <label>Apex Chambers</label>
            </value>
            <value>
                <fullName>Bilateral Chamber</fullName>
                <isActive>false</isActive>
                <label>Bilateral Chamber</label>
            </value>
            <value>
                <fullName>Existing Client</fullName>
                <isActive>false</isActive>
                <label>Existing Client</label>
            </value>
            <value>
                <fullName>Key Account - CX</fullName>
                <isActive>false</isActive>
                <label>Key Account - CX</label>
            </value>
            <value>
                <fullName>Key Account - GX</fullName>
                <isActive>false</isActive>
                <label>Key Account - GX</label>
            </value>
            <value>
                <fullName>New Client</fullName>
                <isActive>false</isActive>
                <label>New Client</label>
            </value>
            <value>
                <fullName>Non Key Client</fullName>
                <isActive>false</isActive>
                <label>Non Key Client</label>
            </value>
            <value>
                <fullName>Regional &amp; Other Chamber</fullName>
                <isActive>false</isActive>
                <label>Regional &amp; Other Chamber</label>
            </value>
            <value>
                <fullName>Sectoral Chamber</fullName>
                <isActive>false</isActive>
                <label>Sectoral Chamber</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_Corridor__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Chambers.recordType-meta.xml
<RecordType>
    <fullName>Chambers</fullName>
    <active>false</active>
    <label>Chambers</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Industry_Leader__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Sub_Industry__c.field-meta.xml
<CustomField>
    <fullName>Sub_Industry__c</fullName>
    <formula>TEXT(Account.SubIndustry__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub-Industry</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ExpertisePL__c/ExpertisePL__c.object-meta.xml
<CustomObject>
    <description>This object is part of the custom functionality for managing the dependency between the 3 Picklists on the Lead object namely Solution (Single Picklist), Expertise (Multi Picklist) and Sub Expertise (Multi Picklist). It stores the List of Values (LOV) configured for the field named Expertise.</description>
    <label>Expertise (PL)</label>
    <nameField>
        <displayFormat>EX - {000000}</displayFormat>
        <label>Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expertise (PL)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/ExpertisePL__c/fields/LOV__c.field-meta.xml
<CustomField>
    <fullName>LOV__c</fullName>
    <description>This stores the List of Value added to the field named Expertise (Expertise__c) on the Lead object.</description>
    <label>LOV</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ExpertisePL__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <description>This stores and represents the dependency between the Solution (Controlling) field and the Expertise (Controlled) field.</description>
    <label>Solution</label>
    <referenceTo>SolutionPL__c</referenceTo>
    <relationshipLabel>Expertise</relationshipLabel>
    <relationshipName>Expertise</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Industry_Leader_Mapping__c/Industry_Leader_Mapping__c.object-meta.xml
<CustomObject>
    <label>Industry Leader Mapping</label>
    <nameField>
        <label>Industry Leader Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Leader Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Industry_Leader_Mapping__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Industry_Leader_Mapping__c/fields/Industry_Business_Partner__c.field-meta.xml
<CustomField>
    <fullName>Industry_Business_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Business Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Industry_Leader_Mappings1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Industry_Leader_Mapping__c/fields/Industry_Leader__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Industry_Leader_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SME_PL__c/SME_PL__c.object-meta.xml
<CustomObject>
    <label>SME(PL)</label>
    <nameField>
        <displayFormat>SME-{000000}</displayFormat>
        <label>SME(PL) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SME(PL)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/SME_PL__c/fields/LOV__c.field-meta.xml
<CustomField>
    <fullName>LOV__c</fullName>
    <label>LOV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SME_PL__c/fields/Sub_Expertise_PL__c.field-meta.xml
<CustomField>
    <fullName>Sub_Expertise_PL__c</fullName>
    <label>Sub Expertise (PL)</label>
    <referenceTo>SubExpertisePL__c</referenceTo>
    <relationshipLabel>SME(PL)</relationshipLabel>
    <relationshipName>SME_PL</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SolutionPL__c/SolutionPL__c.object-meta.xml
<CustomObject>
    <description>This object is part of the custom functionality for managing the dependency between the 3 Picklists on the Lead object namely Solution (Single Picklist), Expertise (Multi Picklist) and Sub Expertise (Multi Picklist). It stores the List of Values (LOV) configured for the field named Solution.</description>
    <label>Solution (PL)</label>
    <nameField>
        <displayFormat>SN - {000000000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solutions (PL)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/SolutionPL__c/fields/LOV__c.field-meta.xml
<CustomField>
    <fullName>LOV__c</fullName>
    <description>This stores the List of Value added to the field named Solution (Solution__c) on the Lead object.</description>
    <label>LOV</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Sub_Industry__c/Sub_Industry__c.object-meta.xml
<CustomObject>
    <label>Sub Industry</label>
    <nameField>
        <displayFormat>SUBI-{0000}</displayFormat>
        <label>Sub Industry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Industries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Sub_Industry__c/fields/Industry_Leader_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Leader Mapping</label>
    <referenceTo>Industry_Leader_Mapping__c</referenceTo>
    <relationshipLabel>Sub Industries</relationshipLabel>
    <relationshipName>Sub_Industries</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Sub_Industry__c/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SubExpertisePL__c/SubExpertisePL__c.object-meta.xml
<CustomObject>
    <description>This object is part of the custom functionality for managing the dependency between the 3 Picklists on the Lead object namely Solution (Single Picklist), Expertise (Multi Picklist) and Sub Expertise (Multi Picklist). It stores the List of Values (LOV) configured for the field named Sub Expertise.</description>
    <label>Sub Expertise (PL)</label>
    <nameField>
        <displayFormat>SE - {000000}</displayFormat>
        <label>Sub Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Expertise (PL)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/SubExpertisePL__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <description>This stores and represents the dependency between the Expertise (Controlling) field and Sub Expertise (Controlled) field.</description>
    <label>Expertise</label>
    <referenceTo>ExpertisePL__c</referenceTo>
    <relationshipLabel>Sub Expertise</relationshipLabel>
    <relationshipName>Sub_Expertise</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SubExpertisePL__c/fields/LOV__c.field-meta.xml
<CustomField>
    <fullName>LOV__c</fullName>
    <description>This stores the List of Value added to the field named Sub Expertise (SubExpertise__c) on the Lead object.</description>
    <label>LOV</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SubExpertisePL__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <formula>Expertise__r.SolutionLOV__c</formula>
    <label>Solution</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Corridor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Israel Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Japan Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United States Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>East Africa Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>GCC &amp; ME Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Germany Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <isActive>false</isActive>
        <label>Others</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk</label>
    </customValue>
    <customValue>
        <fullName>China</fullName>
        <isActive>false</isActive>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>Europe-Germany</fullName>
        <isActive>false</isActive>
        <label>Europe-Germany</label>
    </customValue>
    <customValue>
        <fullName>GCE &amp; ME</fullName>
        <isActive>false</isActive>
        <label>GCE &amp; ME</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk)</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk)</label>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
        <isActive>false</isActive>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <masterLabel>Corridor</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/DependancySectorWithSolutionTest.cls
@isTest
private class DependancySectorWithSolutionTest {
    
    @isTest
    static void testPicklistValues() {
     //   SolutionPL__c solutionRecord=new SolutionPl__c(LOV__c = 'NA');
     //   Insert solutionRecord;
        
     //   ExpertisePL__c expertiseRecord=new ExpertisePL__c(Solution__c = solutionRecord.Id, LOV__c = 'NA');
     //   Insert expertiseRecord;
        
     //   SubExpertisePL__c subExpertiseRecord=new SubExpertisePL__c(LOV__c = 'NA', Expertise__c = expertiseRecord.Id);
     //   Insert subExpertiseRecord;
        
     //   SME_PL__c smeLURecord = new SME_PL__c(Sub_Expertise_PL__c = subExpertiseRecord.Id);
     //   INSERT smeLURecord;
     //   Industry_Leader_Mapping__c testSector = new Industry_Leader_Mapping__c(
     //       Name = 'Test Sector'
            // Add other required fields as needed
     //   );
     //   insert testSector;
     /*   
        Sub_Industry__c testSubIndustry1 = new Sub_Industry__c(
            
            Industry_Leader_Mapping__c = testSector.Id,
            SubIndustry__c = 'Agricultural products'
        );
        Sub_Industry__c testSubIndustry2 = new Sub_Industry__c(
            
            Industry_Leader_Mapping__c = testSector.Id,
            SubIndustry__c = 'Agricultural products'
        );
        insert new List<Sub_Industry__c>{testSubIndustry1, testSubIndustry2};
        */
        User userRecord = TestDataFactory.createUserRecord();
        UserRecord.Username = 'test1@GTUser.com';
		insert userRecord;
        Industry_Leader_Mapping__c ILMapping = new Industry_Leader_Mapping__c();
        ILMapping.Name = 'Agriculture';
        ILMapping.Industry_Business_Partner__c = userRecord.Id;
        ILMapping.Industry_Leader__c = userRecord.Id;
        ILMapping.Industry__c = 'Agriculture';
		insert ILMapping;
        Sub_Industry__c objSubIndustry = new Sub_Industry__c(Industry_Leader_Mapping__c = ILMapping.Id, SubIndustry__c = 'Agricultural products');
        insert objSubIndustry;
        //SELECT Id, Name, Industry_Leader__c, Industry_Business_Partner__c, (SELECT Id, SubIndustry__c FROM Sub_Industries__r) FROM Industry_Leader_Mapping__c WHERE Name =: Sector LIMIT 1];
        
         Account accountObj = new Account(
            Name = 'BLUEBERRY',
            Website = 'www.googl.com',
            CurrencyIsoCode = 'INR',
            AccountType__c = 'Client Account',
            Corridor__c = 'Australia Corridor',
           // Account_Plan_Status__c = 'Draft',
            // Sector__c = 'Auto & Auto Components',
            ClientStatus__c = 'Active',
            Account_Record_Type__c = 'Bill To Client',
            ClientAddress__Street__s = 'test,test',
            ClientAddress__City__s = 'Jaipur',
            ClientAddress__PostalCode__s = '789',
            ClientAddress__CountryCode__s = 'IN',
            ClientAddress__StateCode__s = 'CT',
            DUOAddress__CountryCode__s = 'IN',
            //HQAddressGUO__CountryCode__s = 'IN',
            ShareCapitalInCr__c = 1233,
            Client_s_Headquarter__CountryCode__s = 'US',
            // Sub_Sector__c = 'Auto & Auto Components',
            Company_HQ__CountryCode__s = 'IN',
            Total_No_of_employees__c = '45',
            capIQId__c = 'IQ570461896',
            Total_Revenue__c = 123,
            Country_Corridor__c = 'Australia',
            External_Database_Source__c = 'CapIQ',
            Status__c = 'Active',
            Entity_Type__c = 'Foreign Co.- only foreign operations');
        insert accountObj;

		Contact contactRecord = TestDataFactory.createContact();
       
        contactRecord.AccountId = accountObj.Id;
        contactRecord.Linkedin_URL__c = 'www.google.com';
        contactRecord.MobilePhone = '2233445566';
        contactRecord.Email = 'test@gmail.com';
        contactRecord.Designation__c = 'CEO';
        contactRecord.Salutation = 'Mr.';
        contactRecord.pi__campaign__c = 'Pratham campaign';
        contactRecord.Client_Location__City__s = 'TEST';
        contactRecord.Client_Location__CountryCode__s = 'US';
        contactRecord.Client_Location__PostalCode__s = '121002';
        contactRecord.Client_Location__StateCode__s = 'AL';
        contactRecord.Client_Location__Street__s = 'Test, street';
        contactRecord.Pick_Record__c = false;
        contactRecord.is_Address_filled__c  = false;
        contactRecord.IsPardot__c = '';
        insert contactRecord;
               
            
            // Call the PicklistValues method
        Test.StartTest();
        List<dependancySectorWithSolution.PiclistWrapperClass> result = dependancySectorWithSolution.PicklistValues('Agriculture');
        List<dependancySectorWithSolution.PiclistWrapperClass> result1 = dependancySectorWithSolution.newClientSourcePicklistValues();
        List<dependancySectorWithSolution.PiclistWrapperClass> result2 = dependancySectorWithSolution.fetchAccount('Client Referral');
        List<dependancySectorWithSolution.PiclistWrapperClass> result3 = dependancySectorWithSolution.fetchAccount('Chambers');
        List<dependancySectorWithSolution.PiclistWrapperClass> result4 = dependancySectorWithSolution.fetchAccount('Channels and Alliances');
        List<dependancySectorWithSolution.PiclistWrapperClass> result5 = dependancySectorWithSolution.fetchContact(accountObj.Id);
        Test.StopTest();
        
        
        System.debug('result'+result);
        // Perform assertions
        System.assertEquals(1, result.size(), 'Result should not be empty');
        // Add more assertions as needed based on your specific requirements
        
        
    }
}