LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Client Account</fullName>
                <default>true</default>
                <label>Client Account</label>
            </value>
            <value>
                <fullName>Apex Chambers</fullName>
                <isActive>false</isActive>
                <label>Apex Chambers</label>
            </value>
            <value>
                <fullName>Bilateral Chamber</fullName>
                <isActive>false</isActive>
                <label>Bilateral Chamber</label>
            </value>
            <value>
                <fullName>Existing Client</fullName>
                <isActive>false</isActive>
                <label>Existing Client</label>
            </value>
            <value>
                <fullName>Key Account - CX</fullName>
                <isActive>false</isActive>
                <label>Key Account - CX</label>
            </value>
            <value>
                <fullName>Key Account - GX</fullName>
                <isActive>false</isActive>
                <label>Key Account - GX</label>
            </value>
            <value>
                <fullName>New Client</fullName>
                <isActive>false</isActive>
                <label>New Client</label>
            </value>
            <value>
                <fullName>Non Key Client</fullName>
                <isActive>false</isActive>
                <label>Non Key Client</label>
            </value>
            <value>
                <fullName>Regional &amp; Other Chamber</fullName>
                <isActive>false</isActive>
                <label>Regional &amp; Other Chamber</label>
            </value>
            <value>
                <fullName>Sectoral Chamber</fullName>
                <isActive>false</isActive>
                <label>Sectoral Chamber</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_Corridor__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Country_Corridor__c.field-meta.xml
<CustomField>
    <fullName>Country_Corridor__c</fullName>
    <label>Country HQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Domestic_Ultimate_Owner__c.field-meta.xml
<CustomField>
    <fullName>Domestic_Ultimate_Owner__c</fullName>
    <label>Domestic Ultimate Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Artificial juridical person</fullName>
            </value>
            <value>
                <fullName>Association of persons</fullName>
            </value>
            <value>
                <fullName>Banking Company</fullName>
            </value>
            <value>
                <fullName>Body of Individuals</fullName>
            </value>
            <value>
                <fullName>Co-operative Society</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Public Ltd.</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Public Ltd. by Guarantee</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Public Ltd.-Listed India</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Public Ltd. - Listed India &amp; overseas</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Public Ltd. - PSU</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Pvt. Ltd.</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Pvt. Ltd. by Guarantee</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Pvt. Ltd. - subsidiary of Foreign Co.</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Pvt. Ltd. - subsidiary of Public Ltd. Co.</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Pvt. Unlimited Liability</fullName>
            </value>
            <value>
                <fullName>Domestic Co. - Section 25</fullName>
            </value>
            <value>
                <fullName>Foreign Co.- Grant Thornton member entity</fullName>
            </value>
            <value>
                <fullName>Foreign Co. - Indian Branch</fullName>
            </value>
            <value>
                <fullName>Foreign Co. - Indian Liaison</fullName>
            </value>
            <value>
                <fullName>Foreign Co. - Indian Project</fullName>
            </value>
            <value>
                <fullName>Foreign Co.- only foreign operations</fullName>
            </value>
            <value>
                <fullName>Foreign Co -Listed non-US</fullName>
            </value>
            <value>
                <fullName>Foreign Co -Listed US</fullName>
            </value>
            <value>
                <fullName>Foreign company unlisted</fullName>
            </value>
            <value>
                <fullName>Government Authority</fullName>
            </value>
            <value>
                <fullName>Government – Foreign</fullName>
            </value>
            <value>
                <fullName>Government – Indian</fullName>
            </value>
            <value>
                <fullName>Hindu Undivided Family</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Entity_Type_Master__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Type</label>
    <referenceTo>Entity_Type_Master__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Global_Ultimate_Owner__c.field-meta.xml
<CustomField>
    <fullName>Global_Ultimate_Owner__c</fullName>
    <label>Global Ultimate Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/goog_alert__Google_Alert_URL__c.field-meta.xml
<CustomField>
    <fullName>goog_alert__Google_Alert_URL__c</fullName>
    <label>Google Alert URL</label>
    <type>Url</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Key_Account_Category__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_Category__c</fullName>
    <formula>IF( RecordType.DeveloperName = &apos;Client&apos;, TEXT(GT_Client_Group__r.Key_Account_360__r.Client_Category__c), IF(RecordType.DeveloperName = &apos;GT_Client_Group&apos;,  TEXT( Key_Account_360__r.Client_Category__c ), NULL))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key Account Category</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Key_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_Id__c</fullName>
    <formula>CASESAFEID(GT_Client_Group__r.Key_Account_360__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key Account Id</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Pan_No__c.field-meta.xml
<CustomField>
    <fullName>Pan_No__c</fullName>
    <label>Pan No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/ShareCapitalInCr__c.field-meta.xml
<CustomField>
    <fullName>ShareCapitalInCr__c</fullName>
    <label>Paid up Share Capital</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Total_Employees__c.field-meta.xml
<CustomField>
    <fullName>Total_Employees__c</fullName>
    <label>Total Employees</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-10</fullName>
            </value>
            <value>
                <fullName>11-50</fullName>
            </value>
            <value>
                <fullName>51-100</fullName>
            </value>
            <value>
                <fullName>251-500</fullName>
            </value>
            <value>
                <fullName>500-1000</fullName>
            </value>
            <value>
                <fullName>1000 above</fullName>
            </value>
            <value>
                <fullName>101 - 250</fullName>
            </value>
            <value>
                <fullName>101-500</fullName>
                <isActive>false</isActive>
                <label>101-500</label>
            </value>
            <value>
                <fullName>Above 500</fullName>
                <isActive>false</isActive>
                <label>Above 500</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Total_No_of_employees__c.field-meta.xml
<CustomField>
    <fullName>Total_No_of_employees__c</fullName>
    <label>Total No of employees</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Entity_Type_Master__c/Entity_Type_Master__c.object-meta.xml
<CustomObject>
    <label>Entity Type Master</label>
    <nameField>
        <label>Entity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Type Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Corridor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Israel Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Japan Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United States Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>East Africa Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>GCC &amp; ME Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Germany Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <isActive>false</isActive>
        <label>Others</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk</label>
    </customValue>
    <customValue>
        <fullName>China</fullName>
        <isActive>false</isActive>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>Europe-Germany</fullName>
        <isActive>false</isActive>
        <label>Europe-Germany</label>
    </customValue>
    <customValue>
        <fullName>GCE &amp; ME</fullName>
        <isActive>false</isActive>
        <label>GCE &amp; ME</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk)</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk)</label>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
        <isActive>false</isActive>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <masterLabel>Corridor</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Antilles</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Ascension Island</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>Corridor Country</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/CheckRequiredFields.cls
/*
* @Name: CheckRequiredField
* @Author: Bhavishya Basantwani
* @Date: 1-september-23 (this class is used for making field Required before Ds Approval )
*/

public class CheckRequiredFields {
    
    @InvocableMethod()
    public Static List<String> requiredField(List<ID> AccountIdList){
        system.debug('innn');
        
        Id clientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        system.debug('clientRecordTypeId'+clientRecordTypeId);
        boolean CoCSL = False;
        boolean CSL = False;
        boolean youngCSL = False;
        String reuiredFields = '';
        List<String> blankFields = new List<String>();
        List<String> returnStringList = new List<String>();
        Map<String,String> mapOfFields = new Map<String,String>();
        
        List<Account> accountNewList = [select Id,name,RecordTypeId,Key_Account_Id__c , GT_Client_Group__c ,AccountType__c ,Website,Entity_Type__c,Country_Corridor__c,Key_Account__c,	
                                        SubIndustry__c,	Industry__c,Pan_No__c ,	Status__c, 	Corridor__c,Total_Employees__c,Key_Account_Category__c,
                                        BillingCity,BillingCountry, BillingStreet, BillingState,BillingPostalCode,ShareCapitalInCr__c,goog_alert__Google_Alert_URL__c,Entity_Type_Master__c,Domestic_Ultimate_Owner__c,Global_Ultimate_Owner__c,
                                        Total_Revenue__c,Total_No_of_employees__c,ClientAddress__Street__s,ClientAddress__City__s,ClientAddress__StateCode__s,ClientAddress__PostalCode__s,ClientAddress__CountryCode__s from Account where Id =: AccountIdList];
        
        //Fill Map with Field api name and with Label
        for(Account iterACC : accountNewList){
            if(( iterACC.Status__c == 'Pending Verification' && (iterACC.RecordTypeId == clientRecordTypeId ))){
                system.debug('Inn hendler');
                
                mapOfFields.put('GT_Client_Group__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('GT_Client_Group__c').getDescribe().getLabel());
                mapOfFields.put('goog_alert__Google_Alert_URL__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('goog_alert__Google_Alert_URL__c').getDescribe().getLabel());
                mapOfFields.put('Website',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Website').getDescribe().getLabel());
                //mapOfFields.put('Entity_Type_Master__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Entity_Type_Master__c').getDescribe().getLabel());
                mapOfFields.put('Total_Revenue__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Total_Revenue__c').getDescribe().getLabel());
                mapOfFields.put('Country_Corridor__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Country_Corridor__c').getDescribe().getLabel());
                mapOfFields.put('Industry__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Industry__c').getDescribe().getLabel());
                mapOfFields.put('Pan_No__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Pan_No__c').getDescribe().getLabel());
                mapOfFields.put('Status__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Status__c').getDescribe().getLabel());
                mapOfFields.put('Corridor__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Corridor__c').getDescribe().getLabel());
                mapOfFields.put('Total_No_of_employees__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Total_No_of_employees__c').getDescribe().getLabel());
                mapOfFields.put('ShareCapitalInCr__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('ShareCapitalInCr__c').getDescribe().getLabel());
                // mapOfFields.put('Key_Account_Category__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Key_Account_Category__c').getDescribe().getLabel());
                //mapOfFields.put('Client_s_Headquarter__City__s',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Client_s_Headquarter__City__s').getDescribe().getLabel());
                // mapOfFields.put('Client_s_Headquarter__PostalCode__s',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Client_s_Headquarter__PostalCode__s').getDescribe().getLabel());
                // mapOfFields.put('Client_s_Headquarter__StateCode__s',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Client_s_Headquarter__StateCode__s').getDescribe().getLabel());
                //mapOfFields.put('Client_s_Headquarter__Street__s',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Client_s_Headquarter__Street__s').getDescribe().getLabel());
                mapOfFields.put('SubIndustry__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('SubIndustry__c').getDescribe().getLabel());
                mapOfFields.put('ClientAddress__CountryCode__s',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('ClientAddress__CountryCode__s').getDescribe().getLabel());
                mapOfFields.put('ClientAddress__PostalCode__s',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('ClientAddress__PostalCode__s').getDescribe().getLabel());
                mapOfFields.put('ClientAddress__StateCode__s',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('ClientAddress__StateCode__s').getDescribe().getLabel());
                mapOfFields.put('ClientAddress__City__s',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('ClientAddress__City__s').getDescribe().getLabel());
                mapOfFields.put('ClientAddress__Street__s',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('ClientAddress__Street__s').getDescribe().getLabel());
                mapOfFields.put('Domestic_Ultimate_Owner__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Domestic_Ultimate_Owner__c').getDescribe().getLabel());
                mapOfFields.put('Global_Ultimate_Owner__c',Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Global_Ultimate_Owner__c').getDescribe().getLabel());
            }
        }
        Map<Id,Account> MapOfAccount = new  Map<Id,Account>();
        Map<Account,List<AccountTeamMember>> MapOfListOfCTM = new Map<Account,List<AccountTeamMember>>();
        List<AccountTeamMember> ListOFCTM = [select id,TeamMemberRole,AccountId from AccountTeamMember where AccountId IN:  accountNewList];
        
        //fill Map With AccountId and Account Record
        For(Account acc : accountNewList){
            if(!MapOfAccount.containsKey(acc.Id)){
                MapOfAccount.put(acc.Id,acc);
            }
        }        
        
        
        //Fill map with Account and Its Associated CLient Team Member
        
        for(AccountTeamMember objCTM : ListOFCTM) {
            if(MapOfAccount.ContainsKey(objCTM.AccountId)){
                Account accRec = MapOfAccount.get(objCTM.AccountId);
                if(MapOfListOfCTM.containsKey(accRec)){
                    MapOfListOfCTM.get(accRec).add(objCTM);
                }
                else{
                    MapOfListOfCTM.put(accRec,new List<AccountTeamMember>{objCTM});
                }
            }
        }
        
        
        
        
        // Check Reuired Field is not null and Client Team Member is added or not with some Required Conditions
        for(Account objMapList : accountNewList){
            if(( objMapList.Status__c == 'Pending Verification' && (objMapList.RecordTypeId == clientRecordTypeId ))){
                
                for(String objMap : mapOfFields.keySet()){
                    
                    if(objMapList.get(objMap) == null){
                        blankFields.add(mapOfFields.get(objMap));
                    }
                }
                
                if(objMapList.Key_Account__c == true){
                    
                    if(objMapList.Key_Account_Category__c == null){
                        blankFields.add(Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Key_Account_Category__c').getDescribe().getLabel());
                    }
                    if(MapOfListOfCTM.containskey(objMapList)){
                        List<AccountTeamMember> CTMList = MapOfListOfCTM.get(objMapList);
                        
                        
                        for(AccountTeamMember CTM : CTMList)
                        {
                            
                            if(CTM.TeamMemberRole == 'Key Account – CSL')
                            {
                                CSL = true;
                            }
                            /*  if(CTM.TeamMemberRole == 'Key Account – Co-CSL')
{
CoCSL  = true;
}
*/
                        }
                        
                        /*if(CoCSL == False){
blankFields.add('Key Account – Co-CSL');
}*/
                        if(CSL == False){
                            blankFields.add('Key Account – CSL');
                        }
                    }
                    else{
                        // blankFields.add('Key Account – Co-CSL');
                        blankFields.add('Key Account – CSL');  
                        
                        //string fieldsShowString = string.join(blankFields,'  |  ');
                        //String finalString = 'Please update '  +  fieldsShowString + ' before approving';
                        //objMapList.addError(finalString);
                    }
                }
                /* else{
if(MapOfListOfCTM.containskey(objMapList)){
List<AccountTeamMember> CTMList = MapOfListOfCTM.get(objMapList);


for(AccountTeamMember CTM : CTMList)
{
if(CTM.TeamMemberRole == 'Young CSL')
{
youngCSL  = true;
}
}

if(youngCSL == False){
blankFields.add('Young CSL');
}
}

else{

blankFields.add('Young CSL');

// string fieldsShowString = string.join(blankFields,'  |  ');
// String finalString = 'Please update '  +  fieldsShowString + ' before approving';
// objMapList.addError(finalString);
}
} */
                
                // addError if Any field is null and CLient Team Member is not added (Field List = blankFields)
                if(blankFields.size()>0){
                    system.debug('inside add error');
                    //string fieldsShowString = string.join(blankFields,'  |  ');
                    //String finalString = 'Please update '  +  fieldsShowString + ' before approving';
                    //objMapList.addError(finalString);
                    
                    for(String val : blankFields)
                    {
                        reuiredFields = reuiredFields + '* ' +val +  '\n' ;
                    }
                    returnStringList.add(reuiredFields);
                    
                }
                
            }
        }
        
        return returnStringList; 
    }
    
}