LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Client Account</fullName>
                <default>true</default>
                <label>Client Account</label>
            </value>
            <value>
                <fullName>Apex Chambers</fullName>
                <isActive>false</isActive>
                <label>Apex Chambers</label>
            </value>
            <value>
                <fullName>Bilateral Chamber</fullName>
                <isActive>false</isActive>
                <label>Bilateral Chamber</label>
            </value>
            <value>
                <fullName>Existing Client</fullName>
                <isActive>false</isActive>
                <label>Existing Client</label>
            </value>
            <value>
                <fullName>Key Account - CX</fullName>
                <isActive>false</isActive>
                <label>Key Account - CX</label>
            </value>
            <value>
                <fullName>Key Account - GX</fullName>
                <isActive>false</isActive>
                <label>Key Account - GX</label>
            </value>
            <value>
                <fullName>New Client</fullName>
                <isActive>false</isActive>
                <label>New Client</label>
            </value>
            <value>
                <fullName>Non Key Client</fullName>
                <isActive>false</isActive>
                <label>Non Key Client</label>
            </value>
            <value>
                <fullName>Regional &amp; Other Chamber</fullName>
                <isActive>false</isActive>
                <label>Regional &amp; Other Chamber</label>
            </value>
            <value>
                <fullName>Sectoral Chamber</fullName>
                <isActive>false</isActive>
                <label>Sectoral Chamber</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Key_Account_360__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_360__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Key Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GT Client Groups</relationshipLabel>
    <relationshipName>Clients2</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/GT_Client_Group.recordType-meta.xml
<RecordType>
    <fullName>GT_Client_Group</fullName>
    <active>true</active>
    <label>GT Client Group</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Key_Account.recordType-meta.xml
<RecordType>
    <fullName>Key_Account</fullName>
    <active>true</active>
    <label>Key Account</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/classes/AccountTeamMemberTriggerHelperTest.cls
@isTest
public class AccountTeamMemberTriggerHelperTest {
    
    @isTest static void testUpdate() {
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+RandomId; 
        User testUser=new User(firstname = 'ABC', 
                         lastName = 'XYZ', 
                         email = uniqueName + '@test' + orgId + '.org', 
                         Username = uniqueName + '@test' + orgId + '.org', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = uniqueName.substring(18, 23), 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US', 
                         ProfileId = pf.Id
                        ); 
        insert testUser;
        


        Account keyAccount =TestDataFactory.createAccountRecord();
        keyAccount.Name ='testKey Account team';
        keyAccount.RecordTypeId =   Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ConstantUtility.KEY_ACCOUNT).getRecordTypeId();
        keyAccount.AccountType__c ='Key Client';
        keyAccount.Status__c='Active';
        insert keyAccount;
        
        /* Start : Commented by Rakesh Kumar for Phase-1    
     * 9/4/24
        IntegratedEnquiry__c integratedEnquiryRecord = TestDataFactory.createIntegratedEnquiryRecord();
        integratedEnquiryRecord.Client__c= keyAccount.Id;
        Insert integratedEnquiryRecord;
 End : : Commented by Rakesh Kumar for Phase-1  
*/

       
       
        List<AccountTeamMember> accountTeamMemberList =new List<AccountTeamMember>();
        
        AccountTeamMember coCSL = TestDataFactory.createAccountTeamMember(keyAccount.Id);
        coCSL.TeamMemberRole = 'Relationship Leader';
        coCSL.CaseAccessLevel = 'Read';
        coCSL.ContactAccessLevel = 'Read';
        coCSL.OpportunityAccessLevel = 'Edit';
        coCSL.userId =testUser.Id;
        accountTeamMemberList.add(coCSL);

        AccountTeamMember coyoungCSL = TestDataFactory.createAccountTeamMember(keyAccount.Id);
        coyoungCSL.TeamMemberRole = 'Young CSL';
        coyoungCSL.CaseAccessLevel = 'Read';
        coyoungCSL.ContactAccessLevel = 'Read';
        coyoungCSL.OpportunityAccessLevel = 'Edit';
        coyoungCSL.userId =testUser.Id;
        coyoungCSL.AccountId = keyAccount.Id;
        accountTeamMemberList.add(coyoungCSL);
       
        AccountTeamMember CTMFirst = TestDataFactory.createAccountTeamMember(keyAccount.Id);
        CTMFirst.TeamMemberRole = 'Key Account – CSL';
        CTMFirst.CaseAccessLevel = 'Read';
        CTMFirst.ContactAccessLevel = 'Read';
        CTMFirst.OpportunityAccessLevel = 'Edit';
        accountTeamMemberList.add(CTMFirst);
        insert accountTeamMemberList;

        
        
        Account gtClientGroupAccoount = TestDataFactory.createAccountRecord();
        gtClientGroupAccoount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('GT_Client_Group').getRecordTypeId();
        gtClientGroupAccoount.Key_Account_360__c =keyAccount.Id; 
        gtClientGroupAccoount.Name ='TEst gt yy';
        insert gtClientGroupAccoount ;

        AccountTeamMember solutionOBJ = TestDataFactory.createAccountTeamMember(gtClientGroupAccoount.Id);
            solutionOBJ.TeamMemberRole = 'Solution Expert';
            solutionOBJ.CaseAccessLevel = 'Read';
            solutionOBJ.ContactAccessLevel = 'Read';
            solutionOBJ.OpportunityAccessLevel = 'Edit';
            solutionOBJ.userId =UserInfo.getUserId();
            insert solutionOBJ;
        
       AccountShare share = new AccountShare();
       share.AccountId =keyAccount.Id;
       share.OpportunityAccessLevel ='Edit';
       share.RowCause ='Manual';
       share.UserOrGroupId =testUser.Id;
       share.AccountAccessLevel ='Edit';
        insert share;

        Test.startTest();
        //AccountTeamMember accTeam =[SELECT Id FROM AccountTeamMember LIMIT 1];
        coCSL.TeamMemberRole='Key Account – Co-CSL';
        update coCSL;

       // AccountTeamMember accTeam1 =[SELECT Id FROM AccountTeamMember WHERE TeamMemberRole = 'Young CSL' LIMIT 1];
        delete coyoungCSL;
        Test.stopTest();
        
        

        
            



        
    }
    
    /*@isTest static void testUpdate() {
        Test.startTest();
        AccountTeamMember accTeam =[SELECT Id FROM AccountTeamMember LIMIT 1];
        accTeam.TeamMemberRole='Key Account – Co-CSL';
        update accTeam;
        Test.stopTest();
    }
    @isTest static void testDelete() {
        Test.startTest();
        AccountTeamMember accTeam =[SELECT Id FROM AccountTeamMember WHERE TeamMemberRole = 'Young CSL' LIMIT 1];
        delete accTeam;
        Test.StopTest();
    }*/
    @isTest static void testData1() {
        Test.startTest();
        Account objAccount = TestDataFactory.createAccountRecord();
        objAccount.Status__c = 'Active';
        objAccount.AccountType__c ='Key Client';
        insert objAccount;
        objAccount.AccountType__c ='Key Client';
        update objAccount;
        /* Start : Commented by Rakesh Kumar for Phase-1    
     * 9/4/24
        IntegratedEnquiry__c objIE =TestDataFactory.createIntegratedEnquiryRecord();
        insert objIE;        
        Opportunity testEnquiry = TestDataFactory.createEnquiryRec(objAccount.Id, objIE.Id);
        insert testEnquiry;
        
        OpportunityTeamMember opp =new OpportunityTeamMember ();
        opp.TeamMemberRole = 'Young CSL';
        //opp.CaseAccessLevel = 'Read';
        //opp.ContactAccessLevel = 'Read';
        //opp.popportunityId =testEnquiry.Id;op
        opp.OpportunityId = testEnquiry.Id;
        opp.UserId =UserInfo.getUserId();
        insert opp;
 End : : Commented by Rakesh Kumar for Phase-1  
*/
        AccountTeamMember coyoungCSL = TestDataFactory.createAccountTeamMember(objAccount.Id);
        coyoungCSL.TeamMemberRole = 'Young CSL';
        coyoungCSL.CaseAccessLevel = 'Read';
        coyoungCSL.ContactAccessLevel = 'Read';
        coyoungCSL.OpportunityAccessLevel = 'Edit';
        insert coyoungCSL;
        delete coyoungCSL;

        

        Test.stopTest();

    
    }
    
    
}