LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/capIQId__c.field-meta.xml
<CustomField>
    <fullName>capIQId__c</fullName>
    <label>capIQId</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/External_Database_Source__c.field-meta.xml
<CustomField>
    <fullName>External_Database_Source__c</fullName>
    <label>External Database Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Null</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
            <value>
                <fullName>CapIQ</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>None of them</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/IsClientGTMemberFirm__c.field-meta.xml
<CustomField>
    <fullName>IsClientGTMemberFirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Client GT Member Firm</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/ExpertiseMaster__c/ExpertiseMaster__c.object-meta.xml
<CustomObject>
    <label>Expertise Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expertise Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/ExpertiseMaster__c/fields/LOV_Id__c.field-meta.xml
<CustomField>
    <fullName>LOV_Id__c</fullName>
    <description>Expertise</description>
    <externalId>true</externalId>
    <label>LOV Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ExpertiseMaster__c/fields/Mid__c.field-meta.xml
<CustomField>
    <fullName>Mid__c</fullName>
    <description>Expertise MID</description>
    <label>Mid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Enquiry Prioritization</inlineHelpText>
    <label>Prospect Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Hot</fullName>
                <default>true</default>
                <label>Hot</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <inlineHelpText>Country code of contact number</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code_Name</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/External_Database_Source__c.field-meta.xml
<CustomField>
    <fullName>External_Database_Source__c</fullName>
    <label>External Database Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CapIQ</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry_Leader__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which user has referred this lead.</description>
    <label>Industry Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads4</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/MCA_ID__c.field-meta.xml
<CustomField>
    <fullName>MCA_ID__c</fullName>
    <label>MCA ID</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Country_Code_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Algeria (+213)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (+376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (+1264)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua &amp; Barbuda (+1268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia (+61)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (+1242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (+1246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (+1441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia Herzegovina (+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana (+267)</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil (+55)</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei (+673)</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria (+359)</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso (+226)</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi (+257)</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia (+855)</fullName>
    </customValue>
    <customValue>
        <fullName>India (+91)</fullName>
    </customValue>
    <masterLabel>Country Code Name</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/CreateleadHelperTest.cls
@isTest
public class CreateleadHelperTest {
    
    @isTest
    public static void testCreateLeadMethod(){
        
        User user = TestDataFactory.createUserRecord();
        insert user;
        List<string> expertiseMasterId = new List<string>();
        ExpertiseMaster__c expertisemasterObj = new ExpertiseMaster__c(
            Name = 'Advisory',
            CurrencyIsoCode = 'INR',
            Mid__c = 'ADV',
            LOV_Id__c = 'SL000009');
        insert expertisemasterObj;
        expertiseMasterId.add(expertisemasterObj.Id);
        System.debug('expertiseMasterId-->'+expertiseMasterId);
        
        Lead leadObj1 = TestDataFactory.createLeadRecord();
        leadObj1.FirstName = 'Test';
        leadObj1.Email = 'Test@gmail.com';
        leadObj1.MobilePhone = '9999999999';
        leadObj1.LastName = 'TMC';
        leadObj1.Industry__c = 'Agriculture';
        leadObj1.Industry_Leader__c = user.Id;
        leadObj1.OwnerId = user.Id;
        leadObj1.Category__c = 'Hot';
        leadObj1.Status = 'Client Take-On PreWork';
        leadObj1.Company = 'TMC';
        leadObj1.CountryCode__c ='India (+91)';
        leadObj1.MobilePhone = '1234567891';
      //  leadObj1.capIQId__c = '1234';
      //  leadObj1.MCA_ID__c = '1234';
        leadObj1.External_Database_Source__c = 'CapIQ';
        
        //Database.SaveResult lsr = Database.insert(leadObj1,false);
        //Insert leadObj1;
        String str = JSON.serialize(leadObj1); 
       
        Account internationalAccount = new Account(Name = leadObj1.Company , IsClientGTMemberFirm__c = true);
        insert internationalAccount; 
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new LeadTriggerHandlerMockOutTest());
        CreateleadHelper.Createlead(str,expertiseMasterId);
        CreateleadHelper.findDuplicateAccount(leadObj1.Company);
        Test.stopTest();
    }
   
    @isTest
    public static void testCreateLeadMethod1(){
        
        User user = TestDataFactory.createUserRecord();
        user.LastName = 'Testclassra Code';
        insert user;
        
        List<string> expertiseMasterId = new List<string>();
        ExpertiseMaster__c expertisemasterObj = new ExpertiseMaster__c(
            Name = 'Advisory',
            CurrencyIsoCode = 'INR',
            Mid__c = 'ADV',
            LOV_Id__c = 'SL000009');
        insert expertisemasterObj;
        expertiseMasterId.add(expertisemasterObj.Id);
        
        Lead leadObj = TestDataFactory.createLeadRecord();
        leadObj.LastName = 'TMC';
        leadObj.Industry__c = 'Agriculture';
        leadObj.Industry_Leader__c = user.Id;
        leadObj.OwnerId = user.Id;
        leadObj.Category__c = 'Hot';
        leadObj.Status = 'Client Take-On PreWork';
        leadObj.Company = 'TMC';
        leadObj.CountryCode__c ='India (+91)';
        leadObj.Email = 'test@gmail.com';
        leadObj.MobilePhone = '1234567891';
        
        Database.SaveResult lsr = Database.insert(leadObj,false);
        String str = JSON.serialize(lsr); 
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new LeadTriggerHandlerMockOutTest());
        CreateleadHelper.Createlead(str,expertiseMasterId);
        CreateleadHelper.findDuplicateAccount(leadObj.Company);
        Test.stopTest();
    }

}