LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Channel_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_Type__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audit Client</fullName>
                <label>Channel 1</label>
            </value>
            <value>
                <fullName>Non audit client</fullName>
                <label>Channel 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Category__c.field-meta.xml
<CustomField>
    <fullName>Client_Category__c</fullName>
    <label>Account Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GX - Platinum</fullName>
            </value>
            <value>
                <fullName>GX - Gold</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
                <isActive>false</isActive>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Non Key Account</fullName>
                <isActive>false</isActive>
                <label>Non Key Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_reason_if_inactive__c.field-meta.xml
<CustomField>
    <fullName>Client_reason_if_inactive__c</fullName>
    <label>Client reason (if inactive)</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Category__c</fullName>
    <label>Key Account Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GX - Platinum</fullName>
            </value>
            <value>
                <fullName>GX - Gold</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
                <isActive>false</isActive>
                <label>CX</label>
            </value>
            <value>
                <fullName>Client Account</fullName>
                <isActive>false</isActive>
                <label>Client Account</label>
            </value>
            <value>
                <fullName>Formal Key account</fullName>
                <isActive>false</isActive>
                <label>Formal Key account</label>
            </value>
            <value>
                <fullName>Sub Category</fullName>
                <isActive>false</isActive>
                <label>Sub Category</label>
            </value>
            <value>
                <fullName>Young CSL</fullName>
                <isActive>false</isActive>
                <label>Young CSL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/ClientStatus__c.field-meta.xml
<CustomField>
    <fullName>ClientStatus__c</fullName>
    <description>This field will describe the status of Client.</description>
    <inlineHelpText>This field will describe the status of Client.</inlineHelpText>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/CoCSL__c.field-meta.xml
<CustomField>
    <fullName>CoCSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Key_Account_360__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_360__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Key Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GT Client Groups</relationshipLabel>
    <relationshipName>Clients2</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Mid Market</fullName>
            </value>
            <value>
                <fullName>PIE Audit</fullName>
            </value>
            <value>
                <fullName>Channels - GCC</fullName>
            </value>
            <value>
                <fullName>Channels - Law Firms</fullName>
            </value>
            <value>
                <fullName>Channels - OPC</fullName>
            </value>
            <value>
                <fullName>Channels - PE/VC</fullName>
            </value>
            <value>
                <fullName>Digital Natives</fullName>
            </value>
            <value>
                <fullName>Large Corporates</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
                <isActive>false</isActive>
                <label>Channel</label>
            </value>
            <value>
                <fullName>DGC</fullName>
                <isActive>false</isActive>
                <label>DGC</label>
            </value>
            <value>
                <fullName>Large Corporate</fullName>
                <isActive>false</isActive>
                <label>Large Corporate</label>
            </value>
            <value>
                <fullName>Large Private</fullName>
                <isActive>false</isActive>
                <label>Large Private</label>
            </value>
            <value>
                <fullName>Largest Listed</fullName>
                <isActive>false</isActive>
                <label>Largest Listed</label>
            </value>
            <value>
                <fullName>Listed</fullName>
                <isActive>false</isActive>
                <label>Listed</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>PE Fund</fullName>
                <isActive>false</isActive>
                <label>PE Fund</label>
            </value>
            <value>
                <fullName>PE Investee</fullName>
                <isActive>false</isActive>
                <label>PE Investee</label>
            </value>
            <value>
                <fullName>S M Private</fullName>
                <isActive>false</isActive>
                <label>S M Private</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/classes/SendEmailToCTMTest.cls
/*
@isTest
public class SendEmailToCTMTest {
    
    @testSetup static void dataCreation() {
        
        Account acc = TestDataFactory.createAccountRecord();
        insert acc;
        
        AccountTeamMember CTMfirst = TestDataFactory.createAccountTeamMember(acc.Id);
        AccountTeamMember CTMseond = TestDataFactory.createAccountTeamMember(acc.Id);
        CTMseond.TeamMemberRole = 'Solution Expert';
        
        
        insert CTMfirst;
        insert CTMseond;
        
        
        
    }
    
    
    @isTest static void sendEmail() {
        List<String> ListOfUserName = new List<String>();
        List<Id> ListOfRecepientsIds = new List<Id>();
        List<String> ListOfEmailAddress = new List<String>();
        List<String> ListOfRecId = new List<String>();
        List<String> ListOfTeamRole = new List<String>();
        List<String> ListOfRelatedRec = new List<String>();
        List<AccountTeamMember> CTMList =[SELECT Id,AccountId,UserId,TeamMemberRole FROM AccountTeamMember];
        List<Account> listOfAccount =  [SELECT Id,Name FROM Account] ;
        
        for(Account acc : listOfAccount){
            ListOfRecId.add(acc.Id);
            ListOfRelatedRec.add(acc.Name);
        }
        
        for(AccountTeamMember CTM : CTMList){
            ListOfRecepientsIds.add(CTM.UserId);
            ListOfEmailAddress.add('bhavi@gmail.com');
            ListOfUserName.add('Bhavi Basant');
            ListOfTeamRole.add(CTM.TeamMemberRole);
        }
        
        EmailTemplate TemplateObj = [select Id,Name from EmailTemplate where DeveloperName =: 'Template_For_Associated_Client_With_Key_Account'];
        List<SendEmailToCTM.ActionRequest> listOfResp = new List<SendEmailToCTM.ActionRequest>();
        SendEmailToCTM.ActionRequest ResObj = new SendEmailToCTM.ActionRequest();
        ResObj.EmailAddress = ListOfEmailAddress;
        ResObj.RecipentId = ListOfRecepientsIds;
        ResObj.UserName = ListOfUserName;
        ResObj.TemlateId = TemplateObj.Id;
        ResObj.RecId = ListOfRecId;
        ResObj.TeamRole = ListOfTeamRole;
        ResObj.RelatedRecName = ListOfRelatedRec;
        listOfResp.add(ResObj);
        
        SendEmailToCTM.MailToCixTeam(listOfResp);
        
        System.assertEquals('bhavi@gmail.com', ListOfEmailAddress[0] , 'Successfull');
    }
    
} 




* @Name: SendEmailToCTMTest
* @Author: Bhavishya Basantwani
* @Date: 9-dec-23 
*/
@isTest
public class SendEmailToCTMTest {
    
    @testSetup static void dataCreation() {
        
        Id clientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        system.debug('clientRecordTypeId'+clientRecordTypeId);
        Id gtCLientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GT Client Group').getRecordTypeId();        
        Id KeyAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Key Account').getRecordTypeId();
        
        Account KeyAcc = TestDataFactory.createAccountRecord();
        KeyAcc.RecordTypeId = KeyAccountRecordTypeId;
        KeyAcc.Client_Category__c = 'GX - Platinum';
        KeyAcc.Client_Sub_Category__c = 'Gx - Gold';
        KeyAcc.Channel_Type__c ='Audit Client';
        KeyAcc.Segment__c = 'Government';
        KeyAcc.Industry__c ='Agriculture';
        insert KeyAcc;
        
        AccountTeamMember CTMFifth = TestDataFactory.createAccountTeamMember(KeyAcc.Id);
        CTMFifth.TeamMemberRole = 'Key Account – CSL';
        CTMFifth.ContactAccessLevel = 'Read';
        CTMFifth.CaseAccessLevel = 'Edit';
        CTMFifth.OpportunityAccessLevel ='Edit';
        CTMFifth.AccountAccessLevel = 'Read';
        insert CTMFifth;
        
         AccountTeamMember CTMSeven = TestDataFactory.createAccountTeamMember(KeyAcc.Id);
        CTMSeven.TeamMemberRole = 'Key Account – Co-CSL';
        CTMSeven.ContactAccessLevel = 'Read';
        CTMSeven.CaseAccessLevel = 'Edit';
        CTMSeven.OpportunityAccessLevel = 'Edit';
        CTMSeven.AccountAccessLevel = 'Read';
        
        
        
        Account GtAcc = TestDataFactory.createAccountRecord();
        GtAcc.Name = 'Name44';
        GtAcc.RecordTypeId = gtCLientRecordTypeId;
        GtAcc.Key_Account_360__c = KeyAcc.Id;
        insert GtAcc;
        
        Account GtAcc1 = TestDataFactory.createAccountRecord();
        GtAcc1.Name = 'Shree ji';
        GtAcc1.RecordTypeId = gtCLientRecordTypeId;
        insert GtAcc1;
        
        Id UserId = UserInfo.getUserId() ;
        
        Account acc = TestDataFactory.createAccountRecord();
        
        acc.RecordTypeId = clientRecordTypeId;
        acc.Name = 'Ram radhe';
        //acc.CSL__c = UserId;
        //acc.CoCSL__c = UserId;
       // acc.GSTIN__c = '00900';
        acc.Client_reason_if_inactive__c = 'testtttttt';
        acc.ClientStatus__c = 'Inactive';
        acc.GT_Client_Group__c = GtAcc.Id;
        acc.ClientAddress__City__s = 'Jaipur';
        acc.ClientAddress__CountryCode__s = 'IN';
        acc.ClientAddress__PostalCode__s = '789'; 
        acc.ClientAddress__StateCode__s = 'AS';
        acc.ClientAddress__Street__s = 'test,test';
        
        insert acc;
        
       
        
        
        
        
    }
    
    
    @isTest static void sendEmail() {
        
        Id KeyAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Key Account').getRecordTypeId();
        List<String> ListOfUserName = new List<String>();
        List<Id> ListOfRecepientsIds = new List<Id>();
        List<String> ListOfEmailAddress = new List<String>();
        List<String> ListOfRecId = new List<String>();
        List<String> ListOfTeamRole = new List<String>();
        List<String> ListOfRelatedRec = new List<String>();
        List<AccountTeamMember> CTMList =[SELECT Id,AccountId,UserId,TeamMemberRole FROM AccountTeamMember ];
        system.debug('CTMList'+CTMList);
        List<Account> listOfAccount =  [SELECT Id,Name FROM Account where recordType.Id =: KeyAccountRecordTypeId];
        
        for(Account acc : listOfAccount){
            ListOfRecId.add(acc.Id);
            ListOfRelatedRec.add(acc.Name);
        }
        
        	ListOfRecepientsIds.add(UserInfo.getUserId());
            ListOfEmailAddress.add('bhavi@gmail.com');
            ListOfUserName.add('Bhavi Basant');
            ListOfTeamRole.add('Solution Expert'); 
        
       /* for(AccountTeamMember CTM : CTMList){
            ListOfRecepientsIds.add(CTM.UserId);
            ListOfEmailAddress.add('bhavi@gmail.com');
            ListOfUserName.add('Bhavi Basant');
            ListOfTeamRole.add(CTM.TeamMemberRole);
        }*/
        
        EmailTemplate TemplateObj = [select Id,Name from EmailTemplate where DeveloperName =: 'Template_For_Associated_Client_With_Key_Account'];
        List<SendEmailToCTM.ActionRequest> listOfResp = new List<SendEmailToCTM.ActionRequest>();
        SendEmailToCTM.ActionRequest ResObj = new SendEmailToCTM.ActionRequest();
        ResObj.EmailAddress = ListOfEmailAddress;
        ResObj.RecipentId = ListOfRecepientsIds;
        ResObj.UserName = ListOfUserName;
        ResObj.TemlateId = TemplateObj.Id;
        ResObj.RecId = ListOfRecId;
        ResObj.TeamRole = ListOfTeamRole;
        ResObj.RelatedRecName = ListOfRelatedRec;
        listOfResp.add(ResObj);
        
        SendEmailToCTM.MailToCixTeam(listOfResp);
        
        System.assertEquals('bhavi@gmail.com', ListOfEmailAddress[0] , 'Successfull');
    }
    
}