LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Channel_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_Type__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audit Client</fullName>
                <label>Channel 1</label>
            </value>
            <value>
                <fullName>Non audit client</fullName>
                <label>Channel 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Category__c.field-meta.xml
<CustomField>
    <fullName>Client_Category__c</fullName>
    <label>Account Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GX - Platinum</fullName>
            </value>
            <value>
                <fullName>GX - Gold</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
                <isActive>false</isActive>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Non Key Account</fullName>
                <isActive>false</isActive>
                <label>Non Key Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Category__c</fullName>
    <label>Key Account Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GX - Platinum</fullName>
            </value>
            <value>
                <fullName>GX - Gold</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
                <isActive>false</isActive>
                <label>CX</label>
            </value>
            <value>
                <fullName>Client Account</fullName>
                <isActive>false</isActive>
                <label>Client Account</label>
            </value>
            <value>
                <fullName>Formal Key account</fullName>
                <isActive>false</isActive>
                <label>Formal Key account</label>
            </value>
            <value>
                <fullName>Sub Category</fullName>
                <isActive>false</isActive>
                <label>Sub Category</label>
            </value>
            <value>
                <fullName>Young CSL</fullName>
                <isActive>false</isActive>
                <label>Young CSL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Mid Market</fullName>
            </value>
            <value>
                <fullName>PIE Audit</fullName>
            </value>
            <value>
                <fullName>Channels - GCC</fullName>
            </value>
            <value>
                <fullName>Channels - Law Firms</fullName>
            </value>
            <value>
                <fullName>Channels - OPC</fullName>
            </value>
            <value>
                <fullName>Channels - PE/VC</fullName>
            </value>
            <value>
                <fullName>Digital Natives</fullName>
            </value>
            <value>
                <fullName>Large Corporates</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
                <isActive>false</isActive>
                <label>Channel</label>
            </value>
            <value>
                <fullName>DGC</fullName>
                <isActive>false</isActive>
                <label>DGC</label>
            </value>
            <value>
                <fullName>Large Corporate</fullName>
                <isActive>false</isActive>
                <label>Large Corporate</label>
            </value>
            <value>
                <fullName>Large Private</fullName>
                <isActive>false</isActive>
                <label>Large Private</label>
            </value>
            <value>
                <fullName>Largest Listed</fullName>
                <isActive>false</isActive>
                <label>Largest Listed</label>
            </value>
            <value>
                <fullName>Listed</fullName>
                <isActive>false</isActive>
                <label>Listed</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>PE Fund</fullName>
                <isActive>false</isActive>
                <label>PE Fund</label>
            </value>
            <value>
                <fullName>PE Investee</fullName>
                <isActive>false</isActive>
                <label>PE Investee</label>
            </value>
            <value>
                <fullName>S M Private</fullName>
                <isActive>false</isActive>
                <label>S M Private</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/classes/DuplicateRemoveTest.cls
/*
* @Name: DuplicateRemoveTest
* @Author: Bhavishya Basantwani
* @Date: 9-dec-23 
*/
@isTest
public class DuplicateRemoveTest {
    
    @testSetup static void dataCreation() {
        Id KeyAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Key Account').getRecordTypeId();
        
        
        Account KeyAcc = TestDataFactory.createAccountRecord();
        KeyAcc.Name = 'Test';
        KeyAcc.RecordTypeId = KeyAccountRecordTypeId;
        KeyAcc.Client_Category__c = 'GX - Platinum';
        KeyAcc.Client_Sub_Category__c = 'Gx - Gold';
        KeyAcc.Channel_Type__c ='Audit Client';
        KeyAcc.Segment__c = 'Government';
        KeyAcc.Industry__c ='Agriculture';
        insert KeyAcc;
        
        Account KeyAcc1 = TestDataFactory.createAccountRecord();
        KeyAcc1.Name = 'Test1';
        KeyAcc1.RecordTypeId = KeyAccountRecordTypeId;
        KeyAcc1.Client_Category__c = 'GX - Platinum';
        KeyAcc1.Client_Sub_Category__c = 'Gx - Gold';
        KeyAcc1.Channel_Type__c ='Audit Client';
        KeyAcc1.Segment__c = 'Mid Market';
        KeyAcc1.Industry__c ='Agriculture';
        insert KeyAcc1;
        
        Account KeyAcc2 = TestDataFactory.createAccountRecord();
        KeyAcc2.Name = 'Test2';
        KeyAcc2.RecordTypeId = KeyAccountRecordTypeId;
        KeyAcc2.Client_Category__c = 'GX - Platinum';
        KeyAcc2.Client_Sub_Category__c = 'Gx - Gold';
        KeyAcc2.Channel_Type__c ='Audit Client';
        KeyAcc2.Segment__c = 'Digital Natives';
        KeyAcc2.Industry__c ='Agriculture';
        insert KeyAcc2;
        
    }
    
    @isTest static void RemovetEST() {
        List<Account> listOfAccount =  [SELECT Id,Name,segment__c FROM Account];
        
        List<DuplicateRemove.ActionRequest> listOfResp = new List<DuplicateRemove.ActionRequest>();
        DuplicateRemove.ActionRequest ResObj = new DuplicateRemove.ActionRequest();
        ResObj.ListOfRecords = listOfAccount;
        ResObj.NameOfFields = 'Id,Name,Segment__c';
        ResObj.NameOfObject = 'Account';
        ResObj.respectiveField = 'Segment__c';
        
        listOfResp.add(ResObj);
        List<DuplicateRemove.ActionResponce> listOfreturnString = DuplicateRemove.Remove(listOfResp);
        System.assertEquals(3 , listOfreturnString[0].ListObj.size() , 'successfull');
        System.assertEquals(3 , listOfAccount.size() , 'successfull');
    }
}