LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Channel_and_Alliance_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_and_Alliance_Type__c</fullName>
    <label>Channel and Alliance Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Member Firms Leaders</fullName>
            </value>
            <value>
                <fullName>NEDs &amp; ACs</fullName>
            </value>
            <value>
                <fullName>PEVC</fullName>
            </value>
            <value>
                <fullName>BO &amp; family office</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>GCC</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Academia</fullName>
            </value>
            <value>
                <fullName>Regulators</fullName>
            </value>
            <value>
                <fullName>CIO CDO CISO</fullName>
            </value>
            <value>
                <fullName>CHRO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>CMO</fullName>
            </value>
            <value>
                <fullName>Chambers</fullName>
            </value>
            <value>
                <fullName>Tech Alliances</fullName>
            </value>
            <value>
                <fullName>CA Firms</fullName>
            </value>
            <value>
                <fullName>Specialised Advisory Firms</fullName>
            </value>
            <value>
                <fullName>PMOs</fullName>
            </value>
            <value>
                <fullName>ASSOCHAM</fullName>
            </value>
            <value>
                <fullName>ANZ India Business Chamber</fullName>
            </value>
            <value>
                <fullName>Retailers Association of India</fullName>
            </value>
            <value>
                <fullName>EBG Federation</fullName>
            </value>
            <value>
                <fullName>Mahratta Chamber of Commerce Industries and Agriculture (MCCIA)</fullName>
            </value>
            <value>
                <fullName>FICCI</fullName>
            </value>
            <value>
                <fullName>ICC - Kolkata</fullName>
            </value>
            <value>
                <fullName>AMCHAM</fullName>
            </value>
            <value>
                <fullName>SEPC</fullName>
            </value>
            <value>
                <fullName>Indo-Japan Chamber of Commerce &amp; Industry</fullName>
            </value>
            <value>
                <fullName>INDO-AMERICAN CHAMBER OF COMMERCE Delhi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Chambers.recordType-meta.xml
<RecordType>
    <fullName>Chambers</fullName>
    <active>false</active>
    <label>Chambers</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Channel_and_Alliance_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_and_Alliance_Type__c</fullName>
    <description>This field contains the value of &quot;Channel and Alliance Type&quot; field of associated account.</description>
    <formula>TEXT( Account.Channel_and_Alliance_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel and Alliance Type</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Industry_Leader__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Sub_Industry__c.field-meta.xml
<CustomField>
    <fullName>Sub_Industry__c</fullName>
    <formula>TEXT(Account.SubIndustry__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub-Industry</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Industry_Leader_Mapping__c/Industry_Leader_Mapping__c.object-meta.xml
<CustomObject>
    <label>Industry Leader Mapping</label>
    <nameField>
        <label>Industry Leader Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Leader Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Industry_Leader_Mapping__c/fields/Industry_Business_Partner__c.field-meta.xml
<CustomField>
    <fullName>Industry_Business_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Business Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Industry_Leader_Mappings1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Industry_Leader_Mapping__c/fields/Industry_Leader__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Industry_Leader_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/LeadSource_For_LWC__mdt/LeadSource_For_LWC__mdt.object-meta.xml
<CustomObject>
    <label>LeadSource For LWC</label>
    <pluralLabel>LeadSource For LWC</pluralLabel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/LeadSource_For_LWC__mdt/fields/New_Client_Source__c.field-meta.xml
<CustomField>
    <fullName>New_Client_Source__c</fullName>
    <label>New Client Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Sub_Industry__c/Sub_Industry__c.object-meta.xml
<CustomObject>
    <label>Sub Industry</label>
    <nameField>
        <displayFormat>SUBI-{0000}</displayFormat>
        <label>Sub Industry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Industries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Sub_Industry__c/fields/Industry_Leader_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Leader Mapping</label>
    <referenceTo>Industry_Leader_Mapping__c</referenceTo>
    <relationshipLabel>Sub Industries</relationshipLabel>
    <relationshipName>Sub_Industries</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Sub_Industry__c/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/dependancySectorWithSolution.cls
public with sharing class dependancySectorWithSolution {
    @AuraEnabled(cacheable=true)
    public static List<PiclistWrapperClass> PicklistValues(String Sector){
        List<PiclistWrapperClass> wrapperList = new List<PiclistWrapperClass>();
        Industry_Leader_Mapping__c sectorSolution = [SELECT Id, Name, Industry_Leader__c, Industry_Business_Partner__c, (SELECT Id, SubIndustry__c FROM Sub_Industries__r) FROM Industry_Leader_Mapping__c WHERE Name =: Sector LIMIT 1];
        List<String> ListOfSolution = new List<String>();
        if(sectorSolution.Sub_Industries__r != null && ! sectorSolution.Sub_Industries__r.isEmpty()){
            for(Sub_Industry__c iter: sectorSolution.Sub_Industries__r) {
                ListOfSolution.add(iter.SubIndustry__c);
                
                PiclistWrapperClass pwc = new PiclistWrapperClass();
                pwc.picklistvalue = iter.SubIndustry__c;
                pwc.picklistlabel=  iter.SubIndustry__c;
                wrapperList.add(pwc);
            }
        } 
        System.debug('wrapperList'+wrapperList);
        
        return wrapperList;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<PiclistWrapperClass> newClientSourcePicklistValues(){
        List<PiclistWrapperClass> wrapperList = new List<PiclistWrapperClass>();
        List<LeadSource_For_LWC__mdt> leadSource = [select New_Client_Source__c from LeadSource_For_LWC__mdt ORDER BY New_Client_Source__c asc];
        List<String> ListOfSolution = new List<String>();
        
        for(LeadSource_For_LWC__mdt res : leadSource) {
            
            PiclistWrapperClass pwc = new PiclistWrapperClass();
            pwc.picklistvalue = res.New_Client_Source__c;
            pwc.picklistlabel=  res.New_Client_Source__c;
            wrapperList.add(pwc);
        }
        System.debug('wrapperList'+wrapperList);
        
        return wrapperList;
    }
    
    //Gaurav Kumar (16-Sep-2023)
    @AuraEnabled(cacheable=true)
    public static List<PiclistWrapperClass> fetchAccount(String allianceType){
        System.debug('allianceType :'+allianceType);
        String dynamicValue;
        if(allianceType == 'Chambers'){
            String recordType = 'Channels and Alliances';
            String CType = 'Chamber';
            dynamicValue = 'WHERE RecordType.Name=\''+recordType+'\'';
            dynamicValue = dynamicValue+' AND Type=\''+CType+'\'';
            //dynamicValue = dynamicValue+' AND Channel_and_Alliance_Type__c=\''+allianceType+'\'';
        }
        else if(allianceType == 'Client Referral'){
            String recordType = 'Client';
            String CType = 'Channel';
            dynamicValue = 'WHERE RecordType.Name=\''+recordType+'\'';
            //dynamicValue = dynamicValue+' AND Type=\''+CType+'\'';
            //dynamicValue = dynamicValue+' AND Channel_and_Alliance_Type__c=\''+allianceType+'\'';
        }
        else{
            String recordType = 'Channels and Alliances';
            String CType = 'Channel';
            dynamicValue = 'WHERE RecordType.Name=\''+recordType+'\'';
            dynamicValue = dynamicValue+' AND Type=\''+CType+'\'';
            dynamicValue = dynamicValue+' AND Channel_and_Alliance_Type__c=\''+allianceType+'\'';
        }
        
        List<PiclistWrapperClass> wrapperList = new List<PiclistWrapperClass>();
        System.debug('Query :'+dynamicValue);
        String query = 'SELECT Id,Name, RecordType.Name,Type,Channel_and_Alliance_Type__c,(select id,Name,AccountId from contacts) FROM Account '+dynamicValue;
        List<Account> accList = database.query(query);
        System.debug('Result :'+accList);
        for(Account acc : accList){
            PiclistWrapperClass pwc = new PiclistWrapperClass();
            pwc.picklistvalue = acc.Name;
            pwc.recordId=  acc.Id;
            wrapperList.add(pwc);
            System.debug('Record Type Name :'+acc.RecordType.Name);
        }
        
        return wrapperList;
    }
    
    //Gaurav Kumar (16-Sep-2023)
    @AuraEnabled(cacheable=true)
    public static List<PiclistWrapperClass> fetchContact(String accountId){
        String dynamicValue = ' WHERE AccountId=\''+accountId+'\'';        
        List<PiclistWrapperClass> wrapperList = new List<PiclistWrapperClass>();
        System.debug('Id :'+accountId);
        String query = 'SELECT Id,Name,AccountId from Contact'+dynamicValue;
        List<Contact> conList = database.query(query);
        System.debug('Result :'+conList);
        for(Contact con : conList){
            PiclistWrapperClass pwc = new PiclistWrapperClass();
            pwc.picklistvalue = con.Name;
            pwc.recordId=  con.Id;
            wrapperList.add(pwc);
        }
        
        return wrapperList;
    }
    
    
    public class PiclistWrapperClass{
        @AuraEnabled public String picklistvalue;
        @AuraEnabled public String picklistlabel;
        @AuraEnabled public String recordId;//Gaurav Kumar (16-Sep-2023)
    }
}