LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Channel_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_Type__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audit Client</fullName>
                <label>Channel 1</label>
            </value>
            <value>
                <fullName>Non audit client</fullName>
                <label>Channel 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Category__c.field-meta.xml
<CustomField>
    <fullName>Client_Category__c</fullName>
    <label>Account Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GX - Platinum</fullName>
            </value>
            <value>
                <fullName>GX - Gold</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
                <isActive>false</isActive>
                <label>Key Account</label>
            </value>
            <value>
                <fullName>Non Key Account</fullName>
                <isActive>false</isActive>
                <label>Non Key Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_reason_if_inactive__c.field-meta.xml
<CustomField>
    <fullName>Client_reason_if_inactive__c</fullName>
    <label>Client reason (if inactive)</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Client_Sub_Category__c</fullName>
    <label>Key Account Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GX - Platinum</fullName>
            </value>
            <value>
                <fullName>GX - Gold</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
                <isActive>false</isActive>
                <label>CX</label>
            </value>
            <value>
                <fullName>Client Account</fullName>
                <isActive>false</isActive>
                <label>Client Account</label>
            </value>
            <value>
                <fullName>Formal Key account</fullName>
                <isActive>false</isActive>
                <label>Formal Key account</label>
            </value>
            <value>
                <fullName>Sub Category</fullName>
                <isActive>false</isActive>
                <label>Sub Category</label>
            </value>
            <value>
                <fullName>Young CSL</fullName>
                <isActive>false</isActive>
                <label>Young CSL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/ClientStatus__c.field-meta.xml
<CustomField>
    <fullName>ClientStatus__c</fullName>
    <description>This field will describe the status of Client.</description>
    <inlineHelpText>This field will describe the status of Client.</inlineHelpText>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Key_Account_360__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_360__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Key Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GT Client Groups</relationshipLabel>
    <relationshipName>Clients2</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Mid Market</fullName>
            </value>
            <value>
                <fullName>PIE Audit</fullName>
            </value>
            <value>
                <fullName>Channels - GCC</fullName>
            </value>
            <value>
                <fullName>Channels - Law Firms</fullName>
            </value>
            <value>
                <fullName>Channels - OPC</fullName>
            </value>
            <value>
                <fullName>Channels - PE/VC</fullName>
            </value>
            <value>
                <fullName>Digital Natives</fullName>
            </value>
            <value>
                <fullName>Large Corporates</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
                <isActive>false</isActive>
                <label>Channel</label>
            </value>
            <value>
                <fullName>DGC</fullName>
                <isActive>false</isActive>
                <label>DGC</label>
            </value>
            <value>
                <fullName>Large Corporate</fullName>
                <isActive>false</isActive>
                <label>Large Corporate</label>
            </value>
            <value>
                <fullName>Large Private</fullName>
                <isActive>false</isActive>
                <label>Large Private</label>
            </value>
            <value>
                <fullName>Largest Listed</fullName>
                <isActive>false</isActive>
                <label>Largest Listed</label>
            </value>
            <value>
                <fullName>Listed</fullName>
                <isActive>false</isActive>
                <label>Listed</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>PE Fund</fullName>
                <isActive>false</isActive>
                <label>PE Fund</label>
            </value>
            <value>
                <fullName>PE Investee</fullName>
                <isActive>false</isActive>
                <label>PE Investee</label>
            </value>
            <value>
                <fullName>S M Private</fullName>
                <isActive>false</isActive>
                <label>S M Private</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/Client_Contact_Relationship_Team__c.object-meta.xml
<CustomObject>
    <label>Client Contact Relationship Team</label>
    <nameField>
        <displayFormat>CCRT-{0000}</displayFormat>
        <label>Client Contact Relationship Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Contact Relationship Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <description>This field contains access level of Client Contact.</description>
    <label>Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Read/Write</fullName>
            </value>
            <value>
                <fullName>Inherited by Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <formula>TEXT(Account.Segment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
        <isActive>false</isActive>
        <label>Government</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/SendNotificationToCTMTest.cls
/*
* @Name: SendNotificationToCTMTest
* @Author: Bhavishya Basantwani
* @Description: This class is used for Send Email and Notification To Client Team Member.
* @Date: 28-July-23
*/
@isTest
public class SendNotificationToCTMTest {
    
    @testSetup static void dataCreation() {
        
        
        Id KeyAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Key Account').getRecordTypeId();
        Id clientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        Id gtCLientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GT Client Group').getRecordTypeId();    
        
        
        Account KeyAcc = TestDataFactory.createAccountRecord();
        KeyAcc.Name = 'Test';
        KeyAcc.RecordTypeId = KeyAccountRecordTypeId;
        KeyAcc.Client_Category__c = 'GX - Platinum';
        KeyAcc.Client_Sub_Category__c = 'Gx - Gold';
        KeyAcc.Channel_Type__c ='Audit Client';
        KeyAcc.Segment__c = 'Government';
        KeyAcc.Industry__c ='Agriculture';
        insert KeyAcc;
        
        Account KeyAcc1 = TestDataFactory.createAccountRecord();
        KeyAcc1.Name = 'Test1';
        KeyAcc1.RecordTypeId = KeyAccountRecordTypeId;
        KeyAcc1.Client_Category__c = 'GX - Platinum';
        KeyAcc1.Client_Sub_Category__c = 'Gx - Gold';
        KeyAcc1.Channel_Type__c ='Audit Client';
        KeyAcc1.Segment__c = 'Government';
        KeyAcc1.Industry__c ='Agriculture';
        insert KeyAcc1;
        
        Account KeyAcc2 = TestDataFactory.createAccountRecord();
        KeyAcc2.Name = 'Test2';
        KeyAcc2.RecordTypeId = KeyAccountRecordTypeId;
        KeyAcc2.Client_Category__c = 'GX - Platinum';
        KeyAcc2.Client_Sub_Category__c = 'Gx - Gold';
        KeyAcc2.Channel_Type__c ='Audit Client';
        KeyAcc2.Segment__c = 'Government';
        KeyAcc2.Industry__c ='Agriculture';
        insert KeyAcc2;
        
        Contact con = TestDataFactory.createContactRecord();
        con.AccountId = KeyAcc.Id;
        con.Client_Location__Street__s = 'test,test';
        con.Client_Location__City__s  ='test';
        con.Client_Location__PostalCode__s = '12345';
        con.Client_Location__StateCode__s = 'CT';
        con.Client_Location__CountryCode__s = 'IN';
        insert con;
        Test.StartTest();
        Client_Contact_Relationship_Team__c RelationshipTeam = TestDataFactory.createClientContactRelationshipTeam(con.Id);
        RelationshipTeam.Access__c = 'Read Only';
        insert RelationshipTeam;
        
        AccountTeamMember CTMFirst = TestDataFactory.createAccountTeamMember(KeyAcc.Id);
        CTMFirst.TeamMemberRole = 'Key Account – CSL';
        CTMFirst.ContactAccessLevel = 'Read';
        CTMFirst.CaseAccessLevel = 'Edit'; 
        CTMFirst.OpportunityAccessLevel = 'Edit';
        CTMFirst.AccountAccessLevel = 'Read';
        AccountTeamMember CTMSeond = TestDataFactory.createAccountTeamMember(KeyAcc.Id);
        CTMseond.TeamMemberRole = 'Solution Expert';
        CTMseond.TeamMemberRole = 'Solution Expert';
        CTMseond.ContactAccessLevel = 'Read';
        CTMseond.CaseAccessLevel = 'Edit';
        CTMseond.OpportunityAccessLevel = 'Edit';
        CTMseond.AccountAccessLevel = 'Read';
        
        
        insert CTMFirst;
       // insert CTMSeond;
        
        
        Account GtAcc = TestDataFactory.createAccountRecord();
        GtAcc.RecordTypeId = gtCLientRecordTypeId;
        GtAcc.Key_Account_360__c = KeyAcc.Id;
        insert GtAcc;
        
        Account acc = TestDataFactory.createAccountRecord();
        acc.RecordTypeId = clientRecordTypeId;
        //acc.GSTIN__c = '00900';
        acc.Client_reason_if_inactive__c = 'testtttttt';
        acc.ClientStatus__c = 'Inactive';
        acc.GT_Client_Group__c = GtAcc.Id;
        acc.ClientAddress__Street__s = 'test,test';
        acc.ClientAddress__City__s ='test';
        acc.ClientAddress__PostalCode__s ='12345';
        acc.ClientAddress__StateCode__s ='CT' ;
        acc.ClientAddress__CountryCode__s =  'IN';
        
        insert acc;
        
        AccountTeamMember CTMFifth = TestDataFactory.createAccountTeamMember(acc.Id);
        CTMFifth.TeamMemberRole = 'Solution Expert';
        CTMFifth.TeamMemberRole = 'Solution Expert';
        CTMFifth.ContactAccessLevel = 'Read';
        CTMFifth.CaseAccessLevel = 'Edit';
        CTMFifth.OpportunityAccessLevel = 'Edit';
        CTMFifth.AccountAccessLevel = 'Read';
        
        
      //  insert CTMFifth;
        
        Contact con1 = TestDataFactory.createContactRecord();
        con1.FirstName = 'name44';
        con1.LastName = '55';
        con1.AccountId = KeyAcc.Id;
        con1.Client_Location__Street__s = 'test,test';
        con1.Client_Location__City__s  ='test';
        con1.Client_Location__PostalCode__s = '12345';
        con1.Client_Location__StateCode__s = 'CT';
        con1.Client_Location__CountryCode__s = 'IN';
        insert con1;
        
        Client_Contact_Relationship_Team__c RelationshipTeam1 = TestDataFactory.createClientContactRelationshipTeam(con1.Id);
        RelationshipTeam1.Access__c = 'Read Only';
        insert RelationshipTeam1;
        
        
        AccountTeamMember CTMThird = TestDataFactory.createAccountTeamMember(KeyAcc1.Id);
         CTMThird.TeamMemberRole = 'Key Account – CSL';
        CTMThird.ContactAccessLevel = 'Read';
        CTMThird.CaseAccessLevel = 'Edit'; 
        CTMThird.OpportunityAccessLevel = 'Edit';
        CTMThird.AccountAccessLevel = 'Read';
        AccountTeamMember CTMForth = TestDataFactory.createAccountTeamMember(KeyAcc1.Id);
        CTMForth.TeamMemberRole = 'Solution Expert';
        CTMForth.ContactAccessLevel = 'Read';
        CTMForth.CaseAccessLevel = 'Edit'; 
        CTMForth.OpportunityAccessLevel = 'Edit';
        CTMForth.AccountAccessLevel = 'Read';
        
        
        insert CTMThird;
       // insert CTMForth;
      Test.StopTest();
    }
    
    @isTest static void sendCustomNotificationToCTMTest() {
        Id KeyAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Key Account').getRecordTypeId();
        List<Account> listOfAccount =  [SELECT Id,Name FROM Account Where RecordTypeId =:  KeyAccountRecordTypeId];
        List<SendNotificationToCTM.ActionRequest> listOfResp = new List<SendNotificationToCTM.ActionRequest>();
        List<Id> ListOfRecIds = new List<Id>();
        For(Account acc : listOfAccount){
            ListOfRecIds.add(acc.Id);
        }
        Test.StartTest();
        SendNotificationToCTM.ActionRequest ResObj = new SendNotificationToCTM.ActionRequest();
        ResObj.RecId = ListOfRecIds;
        
        listOfResp.add(ResObj);
        
        SendNotificationToCTM.sendCustomNotificationToCTM(listOfResp);
      //  Test.StopTest();
        System.assertEquals(3 , listOfAccount.size() , 'successfull');
        Test.StopTest();
    }
}