LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/Client_Contact_Relationship_Team__c.object-meta.xml
<CustomObject>
    <label>Client Contact Relationship Team</label>
    <nameField>
        <displayFormat>CCRT-{0000}</displayFormat>
        <label>Client Contact Relationship Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Contact Relationship Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Contact Relationship Team</relationshipLabel>
    <relationshipName>Client_Contact_Relationship_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>This field contains the role of Client Contact Relationship Team member.</description>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Record Creator</fullName>
            </value>
            <value>
                <fullName>Key Account – CSL</fullName>
            </value>
            <value>
                <fullName>Key Account – Co-CSL</fullName>
            </value>
            <value>
                <fullName>NSL</fullName>
                <label>Industry Leader</label>
            </value>
            <value>
                <fullName>Young CSL</fullName>
            </value>
            <value>
                <fullName>Segment Leader</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
                <isActive>false</isActive>
                <label>Campaign Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Contact_Relationship_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains information of &quot;Client Contact&quot; of the new client on conversion of which contact record is created.</description>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/SendNotificationToRealtionshipTeam.cls
/*
* @Name: SendNotificationToRealtionshipTeam
* @Author: Bhavishya Basantwani
* @Description: This class is used for Send Notifcation to Client Contact Relationship Team.
* @Date: 14th-september-23
*/
public class SendNotificationToRealtionshipTeam {
    @InvocableMethod()
    public static void SendNotification(List<ActionRequest> getInfo){
       
       /* Set<String> setOfContactIds = new Set<String>(getInfo[0].ContactIds);
        
        List<Contact> ContactList = [SELECT Id,Name FROM Contact WHERE Id IN :setOfContactIds];
        
         Map<Id,Contact> MapOfContact = new Map<Id,Contact>();
        
        for(Contact con : ContactList){
            If(!MapOfContact.containsKey(con.Id)){
                MapOfContact.put(con.Id,con);
            }
        }
        
        
        Map<Id,Set<Client_Contact_Relationship_Team__c>> MapOfRelationTeam = new Map<Id,Set<Client_Contact_Relationship_Team__c>>();
        
        List<Client_Contact_Relationship_Team__c> listOfRealtionshipTeam = [SELECT Id,Name,Role__c,User__c,Client_Contact__c FROM Client_Contact_Relationship_Team__c WHERE Client_Contact__c =: setOfContactIds];
        
        for(Client_Contact_Relationship_Team__c Team : listOfRealtionshipTeam){
            if(MapOfRelationTeam.containsKey(Team.Client_Contact__c)){
                MapOfRelationTeam.get(Team.Client_Contact__c).add(Team);
            }
            else{
                MapOfRelationTeam.put(Team.Client_Contact__c,new set<Client_Contact_Relationship_Team__c>{Team});
            }
        }
        
        
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        //For(integer i=0 ; i<mapOfAccount.RecId.size(); i++){
        Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(getInfo[0].TemplateId, UserInfo.getUserId() ,listOfRealtionshipTeam[0].Client_Contact__c );
        String baseUrl = URL.getOrgDomainURL().toExternalForm();
		system.debug('baseUrl'+baseUrl);
        String Link;                                          
        For(Id key : MapOfRelationTeam.keySet()){
            
            // notifcation
            String bodyAndTitle ;
            Messaging.CustomNotification notification = new Messaging.CustomNotification();
            
            Contact ConObj = MapOfContact.get(key);
            
            set<String> SetOfUserId = new set<String>();
            Set<Client_Contact_Relationship_Team__c> varRelationshipTeam = MapOfRelationTeam.get(key);
            for(Client_Contact_Relationship_Team__c Team : varRelationshipTeam){
                SetOfUserId.add(Team.User__c);
            }
            
            if(getInfo[0].NotificationType == 'Association'){
                bodyAndTitle = 'The contact ' + ConObj.Name + ' has been associated with the Key Account '+ getInfo[0].RelatedRecName[0] +'.';
            }
            else{
                bodyAndTitle = 'The contact ' + ConObj.Name + ' has been deassociated with the Key Account '+ getInfo[0].RelatedRecName[0] +'.';
            }
            
            notification.setTitle(bodyAndTitle);
            notification.setBody(bodyAndTitle);
            
            // Set the notification type and target
            notification.setNotificationTypeId(getInfo[0].CustomNotification);
            notification.setTargetId(key);
            
            notification.send(SetOfUserId);
            
            // Email 
             Messaging.SingleEmailMessage ObjMail = new Messaging.SingleEmailMessage();
            String body = mail.getHtmlBody();
            if(body.contains('{Object.Link}')){
                    
                    Link = baseUrl + '/' + key;
                    system.debug('Link>>>'+Link);
                    body = body.replace('{Object.Link}',Link);
                    system.debug('Link>>>'+Link);
                }
            If(body.contains('{Object.Name}')){
                body = body.replace('{Object.Name}',ConObj.Name);
            }
            if(body.contains('{Account.Name}')){
                    body = body.replace('{Account.Name}',getInfo[0].RelatedRecName[0]);
                }
            List<String> sendingTo = new List<String>(SetOfUserId);
            //sendingTo.addAll(SetOfUserId);
            ObjMail.setSaveAsActivity(false);
            ObjMail.setTargetObjectId(UserInfo.getUserId());
            ObjMail.setTreatTargetObjectAsRecipient(false);
            ObjMail.setToAddresses(sendingTo);
          	objMail.setHtmlBody(body);
            emailList.add(ObjMail);
            
        }
         Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList); */
    }
    
    public class ActionRequest{
        @InvocableVariable
        public List<string> RelatedRecName; 
        @InvocableVariable
        public List<string> ContactIds; 
        @InvocableVariable
        public Id CustomNotification;
        @InvocableVariable
        public String NotificationType;
        @InvocableVariable
        public String TemplateId;
        @InvocableVariable
        public List<string> UserName;
        
    }
}