LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/Client_Contact_Relationship_Team__c.object-meta.xml
<CustomObject>
    <label>Client Contact Relationship Team</label>
    <nameField>
        <displayFormat>CCRT-{0000}</displayFormat>
        <label>Client Contact Relationship Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Contact Relationship Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Contact Relationship Team</relationshipLabel>
    <relationshipName>Client_Contact_Relationship_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Contact_Relationship_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains information of &quot;Client Contact&quot; of the new client on conversion of which contact record is created.</description>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/is_Address_filled__c.field-meta.xml
<CustomField>
    <fullName>is_Address_filled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is Address filled?</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Last_Activity_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Activity_Date_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>This field contains the Date and Time when the last time activity done on Client Contact.</description>
    <label>Last Activity Date Time</label>
    <type>DateTime</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/Batch_SendContactDuplicateReportTest.cls
@isTest
public class Batch_SendContactDuplicateReportTest {
    @isTest
    public static void testSendEmailToClientAndContactTeam() {
        // Create test data
        Account testAccount = new Account(Name = 'Test Account');
        testAccount.is_Address_filled__c = false;
        insert testAccount;
        
        User testUser = TestDataFactory.createUserRecord();
        insert testUser;
        
        Contact testContact = TestDataFactory.createContact();
        testContact.is_Address_filled__c = false;
        testContact.AccountId = testAccount.Id;
        testContact.Last_Activity_Date_Time__c = System.today() - 31;
        insert testContact;
        
        Client_Contact_Relationship_Team__c testRelationshipTeam = TestDataFactory.createContactTeam(UserInfo.getUserId());
        testRelationshipTeam.Client_Contact__c = testContact.Id;
        testRelationshipTeam.User__c = testUser.Id;
        insert testRelationshipTeam;
        System.debug('testRelationshipTeam -->' + testRelationshipTeam);
        
        Test.startTest();
        
        //Batch_SendContactDuplicateReportHandler.sendEmailToClientAndContactTeam(new List<Contact>{testContact}, new List<String> emailRecipients);
        
        // Start the batch execution
        
        System.debug('contacts in test --> ' + [SELECT Id, AccountId, Last_Activity_Date_Time__c FROM Contact WHERE AccountId != null AND Last_Activity_Date_Time__c = LAST_N_DAYS : 30]);
        Batch_SendContactDuplicateReport objBatchClass = new Batch_SendContactDuplicateReport();
        Database.executeBatch(objBatchClass);
        
        String cronExp = '0 0 9 * * ?'; 
        ScheduleContactDuplicateReportBatch objScheduleClass = new ScheduleContactDuplicateReportBatch();
        String jobId = System.schedule('Test Schedule', cronExp, objScheduleClass);
        
        Test.stopTest();
        
        
    }
    
    @isTest
    static void testQuery() {
        Test.startTest();
        
        String query = Batch_SendContactDuplicateReportHandler.getQuery();
        
        Test.stopTest();
        
        
    }
}