LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_Corridor__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Country_Corridor__c.field-meta.xml
<CustomField>
    <fullName>Country_Corridor__c</fullName>
    <label>Country HQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/DS_Team_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DS_Team_Approval_Status__c</fullName>
    <label>DS Team Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending with DS</fullName>
            </value>
            <value>
                <fullName>DS Approved</fullName>
            </value>
            <value>
                <fullName>DS Rejected</fullName>
            </value>
            <value>
                <fullName>DS Rework required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status_DS_Team_Remark_Status__c.field-meta.xml
<CustomField>
    <fullName>Status_DS_Team_Remark_Status__c</fullName>
    <label>Status ( DS Team Remark Status)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/GT_Client_Group.recordType-meta.xml
<RecordType>
    <fullName>GT_Client_Group</fullName>
    <active>true</active>
    <label>GT Client Group</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Key_Account.recordType-meta.xml
<RecordType>
    <fullName>Key_Account</fullName>
    <active>true</active>
    <label>Key Account</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Corridor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Israel Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Japan Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United States Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>East Africa Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>GCC &amp; ME Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Germany Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <isActive>false</isActive>
        <label>Others</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk</label>
    </customValue>
    <customValue>
        <fullName>China</fullName>
        <isActive>false</isActive>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>Europe-Germany</fullName>
        <isActive>false</isActive>
        <label>Europe-Germany</label>
    </customValue>
    <customValue>
        <fullName>GCE &amp; ME</fullName>
        <isActive>false</isActive>
        <label>GCE &amp; ME</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk)</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk)</label>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
        <isActive>false</isActive>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <masterLabel>Corridor</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Antilles</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Ascension Island</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>Corridor Country</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/AccountSyncToWCGTBatchTest.cls
/* Author : Muskan Soni
 *  Created Date: 8/11/2023
 * Class : AccountSyncToWCGTBatch
*/
@istest
public class AccountSyncToWCGTBatchTest {
   @istest
    public static void AccountSyncToWCGTBatchTest(){
         Test.setMock(HttpCalloutMock.class, new SalesforceToWCGTMockCallout());
        Account gtClientGroupAccoount = TestDataFactory.createAccountRecord();
        gtClientGroupAccoount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('GT_Client_Group').getRecordTypeId();
        insert gtClientGroupAccoount ;
        
        Account keyAccoount = TestDataFactory.createAccountRecord();
        keyAccoount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Key_Account').getRecordTypeId();
        //insert keyAccoount ;
        
        List<Account> accList = new List<Account>();
        for(integer i=0;i<40;i++){
            Account acc = TestDataFactory.createAccountRecord();
            acc.Country_Corridor__c = 'Afghanistan';
            acc.Corridor__c ='NA';
            acc.Status_DS_Team_Remark_Status__c = 'Pending';
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Client').getRecordTypeId();
            acc.DS_Team_Approval_Status__c ='Pending with DS';
            acc.GT_Client_Group__c = gtClientGroupAccoount.Id;
            acc.Website ='WWW.google.com';
            acc.Industry__c ='Sports';
            acc.SubIndustry__c ='Fitness facilities';
            accList.add(acc);
        }
        insert accList;
        List<Account> accList2 = new List<Account>();
        Set <Id> accIDSet = new Set <Id> ();
        for(Account accObj :accList){
            Account acc = new Account(Id = accObj.Id,DS_Team_Approval_Status__c ='DS Approved');
            accIDSet.add(accObj.Id);
            accList2.add(acc);
        }
        //update accList2;
        
        Database.executeBatch(new AccountSyncToWCGTBatch(accIDSet,'Update'),40);
    }
}