LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_Corridor__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Country_Corridor__c.field-meta.xml
<CustomField>
    <fullName>Country_Corridor__c</fullName>
    <label>Country HQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/DS_Team_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DS_Team_Approval_Status__c</fullName>
    <label>DS Team Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending with DS</fullName>
            </value>
            <value>
                <fullName>DS Approved</fullName>
            </value>
            <value>
                <fullName>DS Rejected</fullName>
            </value>
            <value>
                <fullName>DS Rework required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Pick_Record__c.field-meta.xml
<CustomField>
    <fullName>Pick_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pick Record</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/RelationshipOffice__c.field-meta.xml
<CustomField>
    <fullName>RelationshipOffice__c</fullName>
    <label>Relationship Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GT_Bengaluru</fullName>
            </value>
            <value>
                <fullName>GT_Bhopal</fullName>
            </value>
            <value>
                <fullName>GT_Chennai</fullName>
            </value>
            <value>
                <fullName>GT_Delhi</fullName>
            </value>
            <value>
                <fullName>GT_Hyderabad</fullName>
            </value>
            <value>
                <fullName>GT_Lucknow</fullName>
            </value>
            <value>
                <fullName>GT_Mumbai</fullName>
            </value>
            <value>
                <fullName>GT_Noida</fullName>
            </value>
            <value>
                <fullName>GT_One</fullName>
            </value>
            <value>
                <fullName>GT_Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status_DS_Team_Remark_Status__c.field-meta.xml
<CustomField>
    <fullName>Status_DS_Team_Remark_Status__c</fullName>
    <label>Status ( DS Team Remark Status)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Country_Corridor__c.field-meta.xml
<CustomField>
    <fullName>Country_Corridor__c</fullName>
    <formula>TEXT( Account.Country_Corridor__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Corridor</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/is_Address_filled__c.field-meta.xml
<CustomField>
    <fullName>is_Address_filled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is Address filled?</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Linkedin_URL__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_URL__c</fullName>
    <label>Linkedin URL</label>
    <type>Url</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Pick_Record__c.field-meta.xml
<CustomField>
    <fullName>Pick_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pick Record</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT (Account.Gx_Platinum_Gx_Gold_Cx__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/RelationshipOffice__c.field-meta.xml
<CustomField>
    <fullName>RelationshipOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Office</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/DepthOfRelationship__c/DepthOfRelationship__c.object-meta.xml
<CustomObject>
    <label>Depth Of Relationship</label>
    <nameField>
        <label>Depth Of Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depth Of Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Location__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <externalId>true</externalId>
    <label>Location Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Base Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Corridor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Israel Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Japan Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United States Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>East Africa Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>GCC &amp; ME Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Germany Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <isActive>false</isActive>
        <label>Others</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk</label>
    </customValue>
    <customValue>
        <fullName>China</fullName>
        <isActive>false</isActive>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>Europe-Germany</fullName>
        <isActive>false</isActive>
        <label>Europe-Germany</label>
    </customValue>
    <customValue>
        <fullName>GCE &amp; ME</fullName>
        <isActive>false</isActive>
        <label>GCE &amp; ME</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk)</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk)</label>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
        <isActive>false</isActive>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <masterLabel>Corridor</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Antilles</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Ascension Island</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <masterLabel>Corridor Country</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/ContactServiceTest.cls
@isTest
public class ContactServiceTest {
    
    @testSetup 
    static void dataCreation() {
        Account acc = TestDataFactory.createAccountRecord();
        acc.Country_Corridor__c = 'Australia';
        acc.Corridor__c ='Australia Corridor';
        acc.Status_DS_Team_Remark_Status__c = 'Pending';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Client').getRecordTypeId();
        acc.DS_Team_Approval_Status__c ='DS Approved';
        acc.Website ='WWW.google.com';
        acc.Status__c ='Active';
        acc.is_Address_filled__c = false;
        insert acc;
        
        User user = TestDataFactory.createUserRecord();
        insert user;
        /* Start : Commented by Rakesh Kumar for Phase-1    
* 9/4/24
Location__c locationRecord = new Location__c();
locationRecord.Region__c = 'WEST';
locationRecord.Location_Id__c = 'LC000021';
insert locationRecord;  
End : Commented by Rakesh Kumar for Phase-1  
*/ 
        Campaign campaign = TestDataFactory.createCampaign();    
        insert campaign;
        
        Contact contactRecord = TestDataFactory.createContact();
        contactRecord.AccountId = acc.Id;
        contactRecord.Linkedin_URL__c = 'www.google.com';
        contactRecord.MobilePhone = '2233445566';
        contactRecord.Email = 'test@gmail.com';
        contactRecord.Designation__c = 'CEO';
        contactRecord.Salutation = 'Mr.';
        contactRecord.pi__campaign__c = 'Pratham campaign';
        contactRecord.Client_Location__City__s = 'TEST';
        contactRecord.Client_Location__CountryCode__s = 'US';
        contactRecord.Client_Location__PostalCode__s = '121002';
        contactRecord.Client_Location__StateCode__s = 'AL';
        contactRecord.Client_Location__Street__s = 'Test, street';
        contactRecord.OwnerId = user.Id;
        // contactRecord.RelationshipOffice__c = locationRecord.Id;
        contactRecord.Pick_Record__c = false;
        contactRecord.is_Address_filled__c  = false;
        insert contactRecord;
        
        DepthOfRelationship__c depthRelRec = TestDataFactory.createDepthOfRelationship(contactRecord.Id);
        insert depthRelRec;
    }
    
    @isTest
    static void getClientContactTest(){
        Set<Id> setOfIds = new Set<Id>();
        Set<Id> setOfIdsNull = new Set<Id>();
        List<Contact> conList = [select id,name from Contact];
        
        for(Contact con : conList){
            setOfIds.Add(con.Id);
        }
        
        Test.StartTest();
        List<Contact> retrunConList;
        try{
            List<DepthOfRelationship__c> returnDepthList = ContactService.getDepOfRelRelatedContact( conList[0].Id , userInfo.getUserId());
            
            retrunConList = ContactService.getClientContact(setOfIds);
            //retrunConList[0].is_Address_filled__c = true;
            //update retrunConList;            
            
            System.assertNotEquals(null, retrunConList);
            
        }
        catch(Exception e){
            // Assertion for successful execution
            //System.assertNotEquals(null, retrunConList);
        }
        Test.StopTest();
        
    }
}