LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_Corridor__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Country_Corridor__c.field-meta.xml
<CustomField>
    <fullName>Country_Corridor__c</fullName>
    <label>Country HQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/DS_Team_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DS_Team_Approval_Status__c</fullName>
    <label>DS Team Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending with DS</fullName>
            </value>
            <value>
                <fullName>DS Approved</fullName>
            </value>
            <value>
                <fullName>DS Rejected</fullName>
            </value>
            <value>
                <fullName>DS Rework required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Entity_Type_Master__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Type</label>
    <referenceTo>Entity_Type_Master__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Pick_Record__c.field-meta.xml
<CustomField>
    <fullName>Pick_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pick Record</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/RelationshipOffice__c.field-meta.xml
<CustomField>
    <fullName>RelationshipOffice__c</fullName>
    <label>Relationship Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GT_Bengaluru</fullName>
            </value>
            <value>
                <fullName>GT_Bhopal</fullName>
            </value>
            <value>
                <fullName>GT_Chennai</fullName>
            </value>
            <value>
                <fullName>GT_Delhi</fullName>
            </value>
            <value>
                <fullName>GT_Hyderabad</fullName>
            </value>
            <value>
                <fullName>GT_Lucknow</fullName>
            </value>
            <value>
                <fullName>GT_Mumbai</fullName>
            </value>
            <value>
                <fullName>GT_Noida</fullName>
            </value>
            <value>
                <fullName>GT_One</fullName>
            </value>
            <value>
                <fullName>GT_Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status_DS_Team_Remark_Status__c.field-meta.xml
<CustomField>
    <fullName>Status_DS_Team_Remark_Status__c</fullName>
    <label>Status ( DS Team Remark Status)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/VerrifiedByDSTeam__c.field-meta.xml
<CustomField>
    <fullName>VerrifiedByDSTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verrified By DS Team</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/GT_Client_Group.recordType-meta.xml
<RecordType>
    <fullName>GT_Client_Group</fullName>
    <active>true</active>
    <label>GT Client Group</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Campaign/fields/Campaign_Owner__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Owner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Campaign Owner can only be T1 user.</errorMessage>
        <filterItems>
            <field>User.EMP_Tier__c</field>
            <operation>equals</operation>
            <value>T1</value>
        </filterItems>
        <infoMessage>User with T1 designation only.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CampaignsOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Contact_status__c.field-meta.xml
<CustomField>
    <fullName>Contact_status__c</fullName>
    <defaultValue>&apos;New Contact Creation&apos;</defaultValue>
    <label>Contact status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Contact Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Contact Creation</label>
            </value>
            <value>
                <fullName>Pending DS Team Approval</fullName>
                <color>#FFCC33</color>
                <label>Pending DS Team Approval</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Country_Corridor__c.field-meta.xml
<CustomField>
    <fullName>Country_Corridor__c</fullName>
    <formula>TEXT( Account.Country_Corridor__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Corridor</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/is_Address_filled__c.field-meta.xml
<CustomField>
    <fullName>is_Address_filled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is Address filled?</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/IsPardot__c.field-meta.xml
<CustomField>
    <fullName>IsPardot__c</fullName>
    <label>IsPardot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pardot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/KeyContactIdentifier__c.field-meta.xml
<CustomField>
    <fullName>KeyContactIdentifier__c</fullName>
    <label>Key Contact Identifier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>BOD</fullName>
            </value>
            <value>
                <fullName>KMP</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Linkedin_URL__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_URL__c</fullName>
    <label>Linkedin URL</label>
    <type>Url</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Pick_Record__c.field-meta.xml
<CustomField>
    <fullName>Pick_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pick Record</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT (Account.Gx_Platinum_Gx_Gold_Cx__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/RelationshipOffice__c.field-meta.xml
<CustomField>
    <fullName>RelationshipOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Office</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/VerrifiedByDSTeam__c.field-meta.xml
<CustomField>
    <fullName>VerrifiedByDSTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verrified by DS Team</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Entity_Type_Master__c/Entity_Type_Master__c.object-meta.xml
<CustomObject>
    <label>Entity Type Master</label>
    <nameField>
        <label>Entity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Type Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Location__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <externalId>true</externalId>
    <label>Location Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Base Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Corridor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Israel Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Japan Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United States Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>East Africa Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>GCC &amp; ME Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Germany Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <isActive>false</isActive>
        <label>Others</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk</label>
    </customValue>
    <customValue>
        <fullName>China</fullName>
        <isActive>false</isActive>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>Europe-Germany</fullName>
        <isActive>false</isActive>
        <label>Europe-Germany</label>
    </customValue>
    <customValue>
        <fullName>GCE &amp; ME</fullName>
        <isActive>false</isActive>
        <label>GCE &amp; ME</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk)</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk)</label>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
        <isActive>false</isActive>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <masterLabel>Corridor</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Antilles</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Ascension Island</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <masterLabel>Corridor Country</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/ContactTriggerHelperTest.cls
@isTest
public class ContactTriggerHelperTest {
    
    @isTest
    static void testSendDSTeamApprovalRequest() {
        
        // Create test data for Contact records
        List<Contact> testContacts = new List<Contact>();
        
        Entity_Type_Master__c entityTypeMasterRec = TestDataFactory.createEntityTypeMaster();
        insert entityTypeMasterRec;
        
        List<Account> accountList =new List<Account>();

        Account keyAccount = TestDataFactory.createAccountRecord();
        keyAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Key Account').getRecordTypeId();
        keyAccount.VerrifiedByDSTeam__c = false;
        keyAccount.DS_Team_Approval_Status__c = 'Pending with DS';
        accountList.add(keyAccount);
        
        Account gtClientGroupAccoount = TestDataFactory.createAccountRecord();
        gtClientGroupAccoount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('GT_Client_Group').getRecordTypeId();
        accountList.add(gtClientGroupAccoount);       

        Account acc = TestDataFactory.createAccountRecord();
        acc.Country_Corridor__c = 'Afghanistan';
        acc.Corridor__c ='NA';
        acc.Status_DS_Team_Remark_Status__c = 'Pending';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Client').getRecordTypeId();
        acc.DS_Team_Approval_Status__c ='DS Approved';
        acc.GT_Client_Group__c = accountList[1].Id;
        acc.Website ='WWW.google.com';
        acc.Industry__c ='Banking';
        acc.SubIndustry__c ='Investment banking';
        acc.Status__c ='Active';
        acc.is_Address_filled__c = false;
        accountList.add(acc);
        insert accountList;
        
        //insert acc;
        User user = TestDataFactory.createUserRecord();
        insert user;
        
        Location__c locationRecord = new Location__c();
        locationRecord.Region__c = 'WEST';
        locationRecord.Location_Id__c = 'LC000021';
        insert locationRecord;  
        
        Campaign campaign = TestDataFactory.createCampaign();    
        //campaign.Campaign_Owner__c = user.Id;
        insert campaign;
        
        Contact contactRecord = TestDataFactory.createContact();
        System.debug('Acc Industry : ' + accountList[2].Industry__c);
        contactRecord.AccountId = accountList[2].Id;
        contactRecord.Linkedin_URL__c = 'www.google.com';
        contactRecord.MobilePhone = '2233445566';
        contactRecord.Email = 'test@gmail.com';
        contactRecord.Designation__c = 'CEO';
        contactRecord.Salutation = 'Mr.';
        contactRecord.pi__campaign__c = 'Pratham campaign';
        contactRecord.Client_Location__City__s = 'TEST';
        contactRecord.Client_Location__CountryCode__s = 'US';
        contactRecord.Client_Location__PostalCode__s = '121002';
        contactRecord.Client_Location__StateCode__s = 'AL';
        contactRecord.Client_Location__Street__s = 'Test, street';
        contactRecord.OwnerId = user.Id;
        contactRecord.RelationshipOffice__c = locationRecord.Id;
        contactRecord.Pick_Record__c = false;
        contactRecord.is_Address_filled__c  = false;
        contactRecord.IsPardot__c = '';
        insert contactRecord;
                
        contactRecord.DS_Team_Approval_Status__c = 'DS Approved';
        //contactRecord.IsPardot__c = true;
        contactRecord.KeyContactIdentifier__c = 'BOD';
        contactRecord.Pick_Record__c = true;
        contactRecord.IsPardot__c = 'Pardot';
        contactRecord.Contact_status__c = 'Active';
        testContacts.add(contactRecord);
        
        upsert testContacts;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        //req1.setComments('Submitting request for approval.');
        req1.setObjectId(contactRecord.id);
        
        req1.setSubmitterId(user.Id); 
        
        req1.setProcessDefinitionNameOrId('DS_Team_Contact_Approval');
        req1.setSkipEntryCriteria(true);
        
        Approval.ProcessResult result = Approval.process(req1);
        
        try{
            List<ProcessInstanceWorkitem> workItems = [
                SELECT Id, ProcessInstanceId 
                FROM ProcessInstanceWorkitem 
                WHERE ProcessInstance.TargetObjectId = : contactRecord.Id
            ];
            List<Approval.ProcessWorkitemRequest> requests = new List<Approval.ProcessWorkitemRequest>();
            for(ProcessInstanceWorkitem workItem : workItems){
                Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                req.setWorkitemId(workItem.Id);
                //Valid values are: Approve, Reject, or Removed. 
                //Only system administrators can specify Removed.
                req.setAction('Approve');
                //req.setComments('Your Comment.');
                requests.add(req);
            }
            Approval.ProcessResult[] processResults = Approval.process(requests);
        }
        catch(Exception e){
            System.debug('Approval Error : ' + e.getMessage());
            // System.assertEquals(e.getMessage(), ConstantUtility.Comment_Mandatory_Message);
            
        }
        
        
    }
      
}