LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_Corridor__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Country_Corridor__c.field-meta.xml
<CustomField>
    <fullName>Country_Corridor__c</fullName>
    <label>Country HQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/DS_Team_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DS_Team_Approval_Status__c</fullName>
    <label>DS Team Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending with DS</fullName>
            </value>
            <value>
                <fullName>DS Approved</fullName>
            </value>
            <value>
                <fullName>DS Rejected</fullName>
            </value>
            <value>
                <fullName>DS Rework required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/New_Client__c.field-meta.xml
<CustomField>
    <fullName>New_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status_DS_Team_Remark_Status__c.field-meta.xml
<CustomField>
    <fullName>Status_DS_Team_Remark_Status__c</fullName>
    <label>Status ( DS Team Remark Status)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/GT_Client_Group.recordType-meta.xml
<RecordType>
    <fullName>GT_Client_Group</fullName>
    <active>true</active>
    <label>GT Client Group</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account_Requests__c/Account_Requests__c.object-meta.xml
<CustomObject>
    <label>Account Requests</label>
    <nameField>
        <displayFormat>AR-{000}</displayFormat>
        <label>Client Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Account_Requests__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account_Requests__c/fields/New_Client__c.field-meta.xml
<CustomField>
    <fullName>New_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Client</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Account_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account_Requests__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which Client has referred this Lead.</description>
    <inlineHelpText>Referral from existing clients</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Client)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <inlineHelpText>GT Business corridor</inlineHelpText>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Countries__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Corridor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Israel Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Japan Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United States Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>East Africa Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>GCC &amp; ME Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Germany Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <isActive>false</isActive>
        <label>Others</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk</label>
    </customValue>
    <customValue>
        <fullName>China</fullName>
        <isActive>false</isActive>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>Europe-Germany</fullName>
        <isActive>false</isActive>
        <label>Europe-Germany</label>
    </customValue>
    <customValue>
        <fullName>GCE &amp; ME</fullName>
        <isActive>false</isActive>
        <label>GCE &amp; ME</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk)</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk)</label>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
        <isActive>false</isActive>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <masterLabel>Corridor</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Antilles</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Ascension Island</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>Corridor Country</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/AccountRequestTriggerHelperTest.cls
/*
AUTHOR                   : Deepak joshi
VERSION                  : 1
MODIFICATION DATE        : 3 oct 2023
PROJECT NAME / TICKET #  : GT
DESCRIPTION              : AccountRequestTriggerHelper test class
*/
@isTest
public class AccountRequestTriggerHelperTest {
    @testSetup static void dataCreation() {
        Account gtClientGroupAccoount = TestDataFactory.createAccountRecord();
        gtClientGroupAccoount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('GT_Client_Group').getRecordTypeId();
        insert gtClientGroupAccoount ; 
        Account acc = TestDataFactory.createAccountRecord();
        acc.Country_Corridor__c = 'Afghanistan';
        acc.Corridor__c ='NA';
        acc.Status_DS_Team_Remark_Status__c = 'Pending';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Client').getRecordTypeId();
        acc.DS_Team_Approval_Status__c ='Pending with DS';
        acc.GT_Client_Group__c = gtClientGroupAccoount.Id;
        acc.Website ='WWW.google.com';
        acc.Industry__c ='Transportation & Logistics';
       // acc.SubIndustry__c ='Transportation & Logistics';
        insert acc;
        Lead leadRecord = TestDataFactory.createLeadRecord();
        insert leadRecord;

        List<Account_Requests__c> accountRequestsList = new List<Account_Requests__c>();
        
        Account_Requests__c accountRequestsRecordForAccount  = TestDataFactory.createAccountRequests();
        accountRequestsRecordForAccount.client__c= acc.Id;
        accountRequestsRecordForAccount.Status__c =  ConstantUtility.SUBMITTED;
        accountRequestsList.add(accountRequestsRecordForAccount);


        Account_Requests__c accountRequestsRecordForlead  = TestDataFactory.createAccountRequests();
        accountRequestsRecordForlead.Status__c =  ConstantUtility.SUBMITTED;
        accountRequestsRecordForlead.New_Client__c = leadRecord.Id;
        accountRequestsList.add(accountRequestsRecordForlead);
        insert accountRequestsList;

        
        
    }
    @isTest static void testAccount(){
        List<Account_Requests__c> accountReqList = [SELECT Id FROM Account_Requests__c];
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(accountReqList[0].id);
        app.setProcessDefinitionNameOrId(ConstantUtility.DS_APPROVAL_PROCESS);
        app.setComments('Approv');
        Approval.ProcessResult result = Approval.process(app);
        accountReqList[0].Status__c = ConstantUtility.APPROVED;
        update accountReqList[0];
        System.assertEquals(ConstantUtility.APPROVED ,accountReqList[0].Status__c);


    }
    @isTest static void testLead(){
        List<Account_Requests__c> accountReqList = [SELECT Id FROM Account_Requests__c];
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(accountReqList[1].id);
        app.setProcessDefinitionNameOrId(ConstantUtility.CNM_APPROVAL_PROCESS);
        app.setComments('Approv');

        Approval.ProcessResult result = Approval.process(app);
        accountReqList[1].Status__c = ConstantUtility.APPROVED;
        update accountReqList[1];
        System.assertEquals(ConstantUtility.APPROVED ,accountReqList[1].Status__c);

    }
    
}