LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_Corridor__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Country_Corridor__c.field-meta.xml
<CustomField>
    <fullName>Country_Corridor__c</fullName>
    <label>Country HQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/DS_Team_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DS_Team_Approval_Status__c</fullName>
    <label>DS Team Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending with DS</fullName>
            </value>
            <value>
                <fullName>DS Approved</fullName>
            </value>
            <value>
                <fullName>DS Rejected</fullName>
            </value>
            <value>
                <fullName>DS Rework required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Entity_Type_Master__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Type</label>
    <referenceTo>Entity_Type_Master__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Mid Market</fullName>
            </value>
            <value>
                <fullName>PIE Audit</fullName>
            </value>
            <value>
                <fullName>Channels - GCC</fullName>
            </value>
            <value>
                <fullName>Channels - Law Firms</fullName>
            </value>
            <value>
                <fullName>Channels - OPC</fullName>
            </value>
            <value>
                <fullName>Channels - PE/VC</fullName>
            </value>
            <value>
                <fullName>Digital Natives</fullName>
            </value>
            <value>
                <fullName>Large Corporates</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
                <isActive>false</isActive>
                <label>Channel</label>
            </value>
            <value>
                <fullName>DGC</fullName>
                <isActive>false</isActive>
                <label>DGC</label>
            </value>
            <value>
                <fullName>Large Corporate</fullName>
                <isActive>false</isActive>
                <label>Large Corporate</label>
            </value>
            <value>
                <fullName>Large Private</fullName>
                <isActive>false</isActive>
                <label>Large Private</label>
            </value>
            <value>
                <fullName>Largest Listed</fullName>
                <isActive>false</isActive>
                <label>Largest Listed</label>
            </value>
            <value>
                <fullName>Listed</fullName>
                <isActive>false</isActive>
                <label>Listed</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>PE Fund</fullName>
                <isActive>false</isActive>
                <label>PE Fund</label>
            </value>
            <value>
                <fullName>PE Investee</fullName>
                <isActive>false</isActive>
                <label>PE Investee</label>
            </value>
            <value>
                <fullName>S M Private</fullName>
                <isActive>false</isActive>
                <label>S M Private</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status_DS_Team_Remark_Status__c.field-meta.xml
<CustomField>
    <fullName>Status_DS_Team_Remark_Status__c</fullName>
    <label>Status ( DS Team Remark Status)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Sub_Segment__c.field-meta.xml
<CustomField>
    <fullName>Sub_Segment__c</fullName>
    <label>Sub-Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MNC</fullName>
            </value>
            <value>
                <fullName>LC - Large</fullName>
            </value>
            <value>
                <fullName>LC - Emerging</fullName>
            </value>
            <value>
                <fullName>Member Firms</fullName>
            </value>
            <value>
                <fullName>MM - Large</fullName>
            </value>
            <value>
                <fullName>MM - Mid</fullName>
            </value>
            <value>
                <fullName>MM - Small (SMEs)</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Not-for-Profit</fullName>
            </value>
            <value>
                <fullName>Startups</fullName>
            </value>
            <value>
                <fullName>DGC</fullName>
            </value>
            <value>
                <fullName>PIE Audit</fullName>
            </value>
            <value>
                <fullName>Law Firms</fullName>
            </value>
            <value>
                <fullName>PE/VC</fullName>
            </value>
            <value>
                <fullName>OPC</fullName>
            </value>
            <value>
                <fullName>GCC</fullName>
            </value>
            <value>
                <fullName>Academia</fullName>
                <isActive>false</isActive>
                <label>Academia</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
                <isActive>false</isActive>
                <label>Alumni</label>
            </value>
            <value>
                <fullName>BO &amp; family office</fullName>
                <isActive>false</isActive>
                <label>BO &amp; family office</label>
            </value>
            <value>
                <fullName>Banking</fullName>
                <isActive>false</isActive>
                <label>Banking</label>
            </value>
            <value>
                <fullName>CA Firms</fullName>
                <isActive>false</isActive>
                <label>CA Firms</label>
            </value>
            <value>
                <fullName>CFO</fullName>
                <isActive>false</isActive>
                <label>CFO</label>
            </value>
            <value>
                <fullName>CHRO</fullName>
                <isActive>false</isActive>
                <label>CHRO</label>
            </value>
            <value>
                <fullName>CIO CDO CISO</fullName>
                <isActive>false</isActive>
                <label>CIO CDO CISO</label>
            </value>
            <value>
                <fullName>CMO</fullName>
                <isActive>false</isActive>
                <label>CMO</label>
            </value>
            <value>
                <fullName>GLB Listed</fullName>
                <isActive>false</isActive>
                <label>GLB Listed</label>
            </value>
            <value>
                <fullName>Key Account Leaders</fullName>
                <isActive>false</isActive>
                <label>Key Account Leaders</label>
            </value>
            <value>
                <fullName>Law Firm</fullName>
                <isActive>false</isActive>
                <label>Law Firm</label>
            </value>
            <value>
                <fullName>MM - PE</fullName>
                <isActive>false</isActive>
                <label>MM - PE</label>
            </value>
            <value>
                <fullName>Member Firms Leaders</fullName>
                <isActive>false</isActive>
                <label>Member Firms Leaders</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/VerrifiedByDSTeam__c.field-meta.xml
<CustomField>
    <fullName>VerrifiedByDSTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verrified By DS Team</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/GT_Client_Group.recordType-meta.xml
<RecordType>
    <fullName>GT_Client_Group</fullName>
    <active>true</active>
    <label>GT Client Group</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <inlineHelpText>GT Business corridor</inlineHelpText>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Countries__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian PHB (Listed)</fullName>
            </value>
            <value>
                <fullName>MNC</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Large Private</fullName>
            </value>
            <value>
                <fullName>Largest Listed</fullName>
            </value>
            <value>
                <fullName>Listed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PE Fund</fullName>
            </value>
            <value>
                <fullName>PE Investee</fullName>
            </value>
            <value>
                <fullName>S M Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/Corridor__c.field-meta.xml
<CustomField>
    <fullName>Corridor__c</fullName>
    <label>Corridor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Corridor</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Corridor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Israel Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Japan Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>United States Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>East Africa Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>GCC &amp; ME Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>Germany Corridor</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <isActive>false</isActive>
        <label>Others</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
        <isActive>false</isActive>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk</label>
    </customValue>
    <customValue>
        <fullName>China</fullName>
        <isActive>false</isActive>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>Europe-Germany</fullName>
        <isActive>false</isActive>
        <label>Europe-Germany</label>
    </customValue>
    <customValue>
        <fullName>GCE &amp; ME</fullName>
        <isActive>false</isActive>
        <label>GCE &amp; ME</label>
    </customValue>
    <customValue>
        <fullName>Germany &amp; EU(desk)</fullName>
        <isActive>false</isActive>
        <label>Germany &amp; EU(desk)</label>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
        <isActive>false</isActive>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <masterLabel>Corridor</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Antilles</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Ascension Island</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>Corridor Country</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
        <isActive>false</isActive>
        <label>Government</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/TaskTriggerHandlerTest.cls
@isTest 
private class TaskTriggerHandlerTest {
    @testSetup static void createData(){
       /* Test.startTest();
        Job_TestDataFactory.Wrapper enquiryAndJob = Job_TestDataFactory.createJob();
        Test.stopTest();
       */
        User user1 = Job_TestDataFactory.createUserRecord('EM0001','partner','testjob@gamil.com');
        user1.FirstName = 'Linkreta';
        user1.LastName = 'GT';
        insert user1;
        
        Entity_Type_Master__c entityTypeMasterRec = TestDataFactory.createEntityTypeMaster();
        INSERT entityTypeMasterRec;
        List<Account> accountList =new List<Account>();

        Account keyAccount = TestDataFactory.createAccountRecord();
        keyAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Key Account').getRecordTypeId();
        keyAccount.VerrifiedByDSTeam__c = false;
        keyAccount.DS_Team_Approval_Status__c ='Pending with DS';
        keyAccount.Segment__c = 'Government';
        keyAccount.Sub_Segment__c = 'Government';
        accountList.add(keyAccount);
        Account gtClientGroupAccoount = TestDataFactory.createAccountRecord();
        gtClientGroupAccoount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('GT_Client_Group').getRecordTypeId();
        accountList.add(gtClientGroupAccoount);       

        Account acc = TestDataFactory.createAccountRecord();
        acc.Country_Corridor__c = 'Afghanistan';
        acc.Corridor__c ='NA';
        acc.Status_DS_Team_Remark_Status__c = 'Pending';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Client').getRecordTypeId();
        acc.DS_Team_Approval_Status__c ='Pending with DS';
        acc.GT_Client_Group__c = accountList[1].Id;
        acc.Website ='WWW.google.com';
        acc.Industry__c ='Agriculture';
        //acc.SubIndustry__c ='Agricultural productss';
        acc.Status__c ='Active';
        acc.ClientAddress__Street__s = 'test,test';
        acc.ClientAddress__City__s ='test';
        acc.ClientAddress__PostalCode__s ='12345';
        acc.ClientAddress__StateCode__s ='CT' ;
        acc.ClientAddress__CountryCode__s =  'IN';
       
        accountList.add(acc);
        Insert accountList;
        Lead leadObj = TestDataFactory.createLeadRecord();
        insert leadObj;
       
     /*   
        Job_Execution_Team__c job_execution_teamObj = new Job_Execution_Team__c(
            CurrencyIsoCode = 'INR',
            //Emp_Code__c = userRecord.EMP_ID__c,
            Grade__c = 'C1(AM)',
            Job__c = enquiryAndJob.job.Id,
            Rate__c = '10000',
            Active__c = true);
        insert job_execution_teamObj;

        List<String> eventNameList=new List<string>();
        // eventNameList.add('Pre Closure Checklist');
     //   eventNameList.add('CX Internal Meeting');
        // eventNameList.add('CX External Meeting');
        // eventNameList.add('Internal Kick-off Meeting');
        // eventNameList.add('Client Kick-off Meeting');
        
        List<Event> eventToInsert = new List<Event>();
        for(String eventRecord:eventNameList){        
            Event eventObj = new Event();
            eventObj.Subject = eventRecord;
            // eventObj.WhoId = enquiryAndJob.enquiry.ContactId;
            eventObj.Type = eventRecord;
            eventObj.DurationInMinutes = 10;
            eventObj.ActivityDateTime = System.Now();
            eventObj.WhatId = enquiryAndJob.job.id;
            eventToInsert.add(eventObj);
        }
        insert eventToInsert;
     */   
        List<String> taskNameList=new List<string>();
        taskNameList.add('Enrichment of Segmentation Details of New Client');
        taskNameList.add('New Client Owner based on NSL discussion');
        taskNameList.add('NSL Discussion Pending');
        taskNameList.add('Next steps & actions discussed with NSL');
        taskNameList.add('Client Engagement');
        taskNameList.add('Client Take-On Preparation Deck');
        taskNameList.add('Client Council Takeaways');
    /*    taskNameList.add('Pre Closure Checklist');
        taskNameList.add('CX Internal Meeting');
        taskNameList.add('CX External Meeting');
        taskNameList.add('Internal Kick-off Meeting');
        taskNameList.add('Client Kick-off Meeting');
       */ List<Task> taskToInsert = new List<Task>();
        for(String taskRecord:taskNameList){
            Task tskObj = new Task();
            tskObj.Subject = taskRecord;
            tskObj.Type = taskRecord;
            //  tskObj.ownerId = grpObj.Id;
            tskObj.WhatId = accountList[0].id;
            tskObj.ReminderDateTime = System.now()+10;
            tskObj.Comments__c = 'test comments';
            taskToInsert.add(tskObj);
        }
        insert taskToInsert; 
        
        System.debug('taskToInsert==>'+taskToInsert);
        
    }
    
    @isTest static void testIsBeforeInsert(){
        Test.startTest();
        List<Task> tskObj = [Select id from task];
        Test.stopTest();
    } 
    
    
    
    @isTest static void testRetrictTaskCreation(){
        Test.startTest();
        Lead leadObj = [Select id from Lead limit 1];
        Task tskObj = [Select id,ReminderDateTime,Type from task where type = 'Client Engagement' limit 1];
        System.debug('tskObjtestRetrictTaskCreation==>'+tskObj);
        tskObj.WhatId = null;
        tskObj.WhoId = leadObj.Id;
        update tskObj;
        List<Task> taskToUpdate = new List<Task>();
        taskToUpdate.add(tskObj);
        TaskTriggerHandler.retrictTaskCreation(taskToUpdate);
        Test.stopTest();
    }
    
    @isTest static void testCanNotEditReminderSet(){
        Test.startTest();
        Map<Id,Task> oldTaskMap  = new Map<Id,Task>();
        Task tskObj = [Select id,ReminderDateTime,Type from task where type = 'Client Engagement' limit 1];
        List<Task> taskToUpdate = new List<Task>();
        tskObj.ReminderDateTime = System.now()+16;
        update tskObj;
        taskToUpdate.add(tskObj);
        oldTaskMap.put(tskObj.Id,tskObj);
        TaskTriggerHandler.canNotEditReminderSet(taskToUpdate , oldTaskMap);
        Test.stopTest();
    }
    
    @isTest static void IsBeforeUpdate(){
        Test.startTest();
        List<Task> tskObj = [Select id,Subject,Type,Status,WhatId from task];
        List<Event> lstEventObj = [Select id,Subject,Type,Status__c,Meeting_notes__c,Meeting_agenda__c, WCGTStatus__c from Event];
        List<Event> eventToUpdate = new List<Event>();
        for(Event evnt : lstEventObj){
            evnt.Meeting_notes__c = 'Test Meet';
            evnt.Meeting_agenda__c = 'Test Meet';
            evnt.Status__c = 'Completed';
            evnt.WCGTStatus__c = 'Success';
            eventToUpdate.add(evnt);
        }
        update eventToUpdate;
      /*  
        Job__c jobObj = [Select id from Job__c];
        List<Task> taskToUpdate = new List<Task>();
        for(Task task : tskObj){
            if(  task.Type == 'CX Internal Meeting' ){
                task.Status = 'Completed';
                task.WhatId = jobObj.Id;
                taskToUpdate.add(task);
            }
        }
        update taskToUpdate;
*/
        Test.stopTest();
    } 
    
    @isTest  static void testIsBeforeUpdateForValidation(){
        Test.startTest();
        List<Event> lstEventObj = [Select id,Subject,Type,Status__c,Meeting_notes__c,Meeting_agenda__c, WCGTStatus__c from Event];
        List<Event> eventToUpdate = new List<Event>();
        for(Event evnt : lstEventObj){
            evnt.Meeting_notes__c = 'Test Meet';
            evnt.Meeting_agenda__c = 'Test Meet';
            evnt.Status__c = 'Completed';
            evnt.WCGTStatus__c = 'Success';
            eventToUpdate.add(evnt);
        }
        update eventToUpdate;
        
       // Job__c jobObj = [Select id from Job__c];
        List<Account> accountList =[SELECT Id,RecordTypeId FROM Account];
        Task tskObj = new Task();
        tskObj.Subject = 'Client';
        tskObj.Type = 'Client';
        //  tskObj.ownerId = grpObj.Id;
        tskObj.WhatId = accountList[0].id;
        tskObj.ReminderDateTime = System.now()+10;
        tskObj.Comments__c = 'test comments';
        insert tskObj;
        
        Group g = [Select Id from Group where type = 'Queue' AND DeveloperName = 'C_M_Team_Queue' limit 1];
        System.debug('Group==>'+g.Id);
        
        GroupMember gm = [Select id,UserorGroupId  from GroupMember where GroupId =: g.id limit 1];
        System.debug('Group==>'+gm.UserorGroupId);
        
        // User queueUser = [Select id from user where Id=:gm.UserorGroupId];
        // System.debug('queueUser==>'+queueUser);
        
        //  Task tskObj = [Select id,ReminderDateTime,Type,OwnerId from task where type = 'CX Internal Meeting' limit 1];
        //  System.debug('tskObj==>'+tskObj);
        tskObj.OwnerId = g.Id;
        update tskObj;
        //  System.runAs ( queueUser) {
        tskObj.Status = 'Completed';
        try{
            update tskObj; 
        }catch(Exception e){
            //  System.assertEquals(error, response.outputRecordCollection.size(), 'OutputRecordCollection size should be 5');    
        }
        
        //   }
        Test.stopTest();
    }
    
        @isTest  static void getSObjectName(){
        Test.startTest();
            List<Account> accountList =[SELECT Id,RecordTypeId FROM Account];
            Set<Id> accIds = new Set<Id>();
            for(account acc : accountList){
                accIds.add(acc.Id);
            }
            TaskTriggerHandler.getSObjectName(accIds);
        Test.stopTest();
        }
    
    @isTest  static void beforeUpdate(){
        Test.startTest();
        List<Account> accountList =[SELECT Id,RecordTypeId FROM Account];
        Task tskObj = new Task();
        tskObj.Subject = 'camp';
        tskObj.Type = 'Campaign Feedback';
        tskObj.Status = 'Open';
        tskObj.WhatId = accountList[0].id;
        tskObj.ReminderDateTime = System.now()+10;
        tskObj.Comments__c = 'test comments';
        insert tskObj;
        tskObj.Status = 'Completed';
        update tskObj;
        Test.stopTest();
        }
}