LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Country_Corridor__c.field-meta.xml
<CustomField>
    <fullName>Country_Corridor__c</fullName>
    <label>Country HQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/RelationshipOffice__c.field-meta.xml
<CustomField>
    <fullName>RelationshipOffice__c</fullName>
    <label>Relationship Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GT_Bengaluru</fullName>
            </value>
            <value>
                <fullName>GT_Bhopal</fullName>
            </value>
            <value>
                <fullName>GT_Chennai</fullName>
            </value>
            <value>
                <fullName>GT_Delhi</fullName>
            </value>
            <value>
                <fullName>GT_Hyderabad</fullName>
            </value>
            <value>
                <fullName>GT_Lucknow</fullName>
            </value>
            <value>
                <fullName>GT_Mumbai</fullName>
            </value>
            <value>
                <fullName>GT_Noida</fullName>
            </value>
            <value>
                <fullName>GT_One</fullName>
            </value>
            <value>
                <fullName>GT_Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/WCGTId__c.field-meta.xml
<CustomField>
    <fullName>WCGTId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>WCGT Id is updated when client is created</description>
    <externalId>true</externalId>
    <inlineHelpText>WCGT Id for Client</inlineHelpText>
    <label>WCGT Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Contact_status__c.field-meta.xml
<CustomField>
    <fullName>Contact_status__c</fullName>
    <defaultValue>&apos;New Contact Creation&apos;</defaultValue>
    <label>Contact status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Contact Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Contact Creation</label>
            </value>
            <value>
                <fullName>Pending DS Team Approval</fullName>
                <color>#FFCC33</color>
                <label>Pending DS Team Approval</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Country_Corridor__c.field-meta.xml
<CustomField>
    <fullName>Country_Corridor__c</fullName>
    <formula>TEXT( Account.Country_Corridor__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Corridor</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/RelationshipOffice__c.field-meta.xml
<CustomField>
    <fullName>RelationshipOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Office</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/WCGTId__c.field-meta.xml
<CustomField>
    <fullName>WCGTId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>WCGT Id is updated when Client Contact is created</description>
    <externalId>true</externalId>
    <inlineHelpText>WCGT Id for Client Contact</inlineHelpText>
    <label>WCGT Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/DepthOfRelationship__c/DepthOfRelationship__c.object-meta.xml
<CustomObject>
    <label>Depth Of Relationship</label>
    <nameField>
        <label>Depth Of Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depth Of Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/DepthOfRelationship__c/fields/ClientContact__c.field-meta.xml
<CustomField>
    <fullName>ClientContact__c</fullName>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Depth Of Relationships</relationshipLabel>
    <relationshipName>Depth_Of_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/DepthOfRelationship__c/fields/GTRL__c.field-meta.xml
<CustomField>
    <fullName>GTRL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT RL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Depth_Of_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Location__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <externalId>true</externalId>
    <label>Location Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/EMP_ID__c.field-meta.xml
<CustomField>
    <fullName>EMP_ID__c</fullName>
    <externalId>true</externalId>
    <label>Employee ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Antilles</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Ascension Island</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>Corridor Country</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/ContactService.cls
public class ContactService {
    public static List<Contact> getClientContact(Set<Id> clientContactIds){
        try{
            system.debug('clientContactIds:'+clientContactIds);
            List<Contact> clientContacts = new List<Contact>();
            if(clientContactIds != null && clientContactIds.size() > 0){
                clientContacts = [SELECT Id,Name,AccountId,Account.Name,Account.Country_Corridor__c,MobilePhone,Email,Designation__c,Contact_status__c,Salutation,
                                   FirstName,LastName,RelationshipOffice__r.Location_Id__c,Client_Location__Street__s,Client_Location__City__s,
                                  Client_Location__StateCode__s,Client_Location__PostalCode__s,Client_Location__CountryCode__s,
                                  LastModifiedById FROM Contact WHERE ID IN : clientContactIds];
            }
            return clientContacts;
        }catch(Exception e){
            system.debug('exception:'+e.getLineNumber()+' '+e.getMessage());
            return null;
        }
    }
    
    public static List<DepthOfRelationship__c> getDepOfRelRelatedContact(Id contactId,Id gtUser){
        try{
            List<DepthOfRelationship__c> contactTeam = new List<DepthOfRelationship__c>();
            if(String.isNotBlank(contactId) && String.isNotBlank(gtUser)){
                contactTeam = [SELECT Id,Name,ClientContact__c,ClientContact__r.WCGTId__c,GTRL__c,GTRL__r.EMP_ID__c FROM DepthOfRelationship__c
                               WHERE ClientContact__c =: contactId AND GTRL__c =: gtUser];
            }
            return contactTeam;
        }catch(Exception e){
            system.debug('exception:'+e.getLineNumber()+' '+e.getMessage());
            return null;
        }
    }
}