LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Customer_Experience_Index__c.field-meta.xml
<CustomField>
    <fullName>Customer_Experience_Index__c</fullName>
    <label>Client Experience Index</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Customer_Satisfaction_Index__c.field-meta.xml
<CustomField>
    <fullName>Customer_Satisfaction_Index__c</fullName>
    <label>Client Satisfaction Index</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Detractor__c.field-meta.xml
<CustomField>
    <fullName>Detractor__c</fullName>
    <inlineHelpText>Detractor percentage of survey related to this client.</inlineHelpText>
    <label>Detractor</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Key_Account_360__c.field-meta.xml
<CustomField>
    <fullName>Key_Account_360__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Key Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GT Client Groups</relationshipLabel>
    <relationshipName>Clients2</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Net_Promoter_Score__c.field-meta.xml
<CustomField>
    <fullName>Net_Promoter_Score__c</fullName>
    <inlineHelpText>Promoter % - Detractor %</inlineHelpText>
    <label>Net Promoter Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/New_Client__c.field-meta.xml
<CustomField>
    <fullName>New_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Promoter__c.field-meta.xml
<CustomField>
    <fullName>Promoter__c</fullName>
    <inlineHelpText>Promoter percentage of survey related to this client.</inlineHelpText>
    <label>Promoter</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/clientByGtClientGroup.cls
/*
* @Name: ClientByGtClientGroup
* @Author: Bhavishya Basantwani
* @Description: This class is used for LWC(ClientByGtClientGroup) to retrieve the data of Gt Client Group And Client By Key Account .
* @Date: 13-July-23
*/
public class clientByGtClientGroup {
    
    @AuraEnabled(cacheable=true)
    public static map<string,list<Account>> getRecord(id recordId){
        
        //Like '%GT%'
        Map<string,list<Account>> listOfMap = new Map<string,list<Account>>();
        system.debug('recordId'+recordId);
        list<Account> listOfAccount =   [select id,name, (select id,name,new_client__r.Name,Net_Promoter_Score__c,Promoter__c,Detractor__c,Industry__c,SubIndustry__c,Owner.Name,
                                                          Customer_Satisfaction_Index__c,Customer_Experience_Index__c from Clients1__r where RecordType.DeveloperName !='Bill_To_Client') from Account 
                                         where recordtype.name =:'GT Client Group' and key_Account_360__c =: recordId];
        system.debug('listOfAccount'+listOfAccount);
        
        for(Account Acc : listOfAccount){
            listOfMap.put(Acc.Name,Acc.Clients1__r);   
        }
        
        
        system.debug('listOfMap'+listOfMap);
        return listOfMap;
    }
    
    @AuraEnabled(cacheable=true)
    public static list<Account> getRecordFilter(id recordId , string SelectedValue){
        
        system.debug('indisee>>>$$');
        system.debug('SelectedValue'+SelectedValue);
        system.debug('recordId'+recordId);
        list<Account> listOfAccount =   [select id,Name,Industry__c,Owner.Name,GT_Client_Group__r.Name,new_client__r.Name from Account where GT_Client_Group__c =:SelectedValue AND RecordType.DeveloperName !='Bill_To_Client'];
        system.debug('listOfAccount'+listOfAccount);
        
        return listOfAccount;
    }
    
    
    
}