LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/DS_Team_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DS_Team_Approval_Status__c</fullName>
    <label>DS Team Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending with DS</fullName>
            </value>
            <value>
                <fullName>DS Approved</fullName>
            </value>
            <value>
                <fullName>DS Rejected</fullName>
            </value>
            <value>
                <fullName>DS Rework required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Last_Modified_By_for_WCGT__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By_for_WCGT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Modified By for WCGT</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clients4</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/RelationshipOffice__c.field-meta.xml
<CustomField>
    <fullName>RelationshipOffice__c</fullName>
    <label>Relationship Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GT_Bengaluru</fullName>
            </value>
            <value>
                <fullName>GT_Bhopal</fullName>
            </value>
            <value>
                <fullName>GT_Chennai</fullName>
            </value>
            <value>
                <fullName>GT_Delhi</fullName>
            </value>
            <value>
                <fullName>GT_Hyderabad</fullName>
            </value>
            <value>
                <fullName>GT_Lucknow</fullName>
            </value>
            <value>
                <fullName>GT_Mumbai</fullName>
            </value>
            <value>
                <fullName>GT_Noida</fullName>
            </value>
            <value>
                <fullName>GT_One</fullName>
            </value>
            <value>
                <fullName>GT_Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/WCGTId__c.field-meta.xml
<CustomField>
    <fullName>WCGTId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>WCGT Id is updated when client is created</description>
    <externalId>true</externalId>
    <inlineHelpText>WCGT Id for Client</inlineHelpText>
    <label>WCGT Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/objects/API_Logger__c/API_Logger__c.object-meta.xml
<CustomObject>
    <label>API Logger</label>
    <nameField>
        <displayFormat>API-{0000}</displayFormat>
        <label>API Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Contact_status__c.field-meta.xml
<CustomField>
    <fullName>Contact_status__c</fullName>
    <defaultValue>&apos;New Contact Creation&apos;</defaultValue>
    <label>Contact status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Contact Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Contact Creation</label>
            </value>
            <value>
                <fullName>Pending DS Team Approval</fullName>
                <color>#FFCC33</color>
                <label>Pending DS Team Approval</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Last_Modified_By_for_WCGT__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By_for_WCGT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Modified By for WCGT</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Contacts7</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/RelationshipOffice__c.field-meta.xml
<CustomField>
    <fullName>RelationshipOffice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Office</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/WCGTId__c.field-meta.xml
<CustomField>
    <fullName>WCGTId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>WCGT Id is updated when Client Contact is created</description>
    <externalId>true</externalId>
    <inlineHelpText>WCGT Id for Client Contact</inlineHelpText>
    <label>WCGT Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Location__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <externalId>true</externalId>
    <label>Location Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/EMP_ID__c.field-meta.xml
<CustomField>
    <fullName>EMP_ID__c</fullName>
    <externalId>true</externalId>
    <label>Employee ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/USER_ID__c.field-meta.xml
<CustomField>
    <fullName>USER_ID__c</fullName>
    <externalId>true</externalId>
    <label>WCGT User ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/WCGTEndPoint__mdt/WCGTEndPoint__mdt.object-meta.xml
<CustomObject>
    <description>Here all the endpoint of WCGT are stored. We can change the URL from here if required.</description>
    <label>WCGT Endpoint</label>
    <pluralLabel>WCGT Endpoints</pluralLabel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/WCGTEndPoint__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <inlineHelpText>The endpoint url of the WCGT.</inlineHelpText>
    <label>URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/SyncClientContactToWCGTHelper.cls
/*
    Created by : Suraj Kumar
    Date : 05-09-2023
    Description : This class is used to send Client Contact details to WCGT on creation or updation. 
*/

public class SyncClientContactToWCGTHelper {
    
    public static String getQuery(){
        String query = 'SELECT Id, Name, MiddleName, Last_Modified_By_for_WCGT__c, Last_Modified_By_for_WCGT__r.USER_ID__c, AccountId, Account.Name, Account.DS_Team_Approval_Status__c, Account.Client_s_Headquarter__Street__s, MobilePhone, Email,Designation__c, RelationshipOffice__c, CreatedBy.EMP_ID__c,LastModifiedBy.EMP_ID__c,Owner.EMP_ID__c, Contact_status__c, Salutation, FirstName, LastName, RelationshipOffice__r.Location_Id__c,  Client_Location__Street__s, Client_Location__City__s,  toLabel(Client_Location__StateCode__s), Client_Location__PostalCode__s,toLabel(Client_Location__CountryCode__s), LastModifiedById, LastModifiedBy.USER_ID__c,Owner.USER_ID__c,WcgtId__c,CreatedBy.USER_ID__c, Account.Client_s_Headquarter__City__s, toLabel(Account.Client_s_Headquarter__CountryCode__s), Account.Client_s_Headquarter__PostalCode__s, toLabel(Account.Client_s_Headquarter__StateCode__s) FROM Contact WHERE Id IN : contactIds' ;
        return query;
    }
    
    
    public Static List<API_Logger__c> syncClientContactToWCGT( Contact clientContact, String Flag ){
        
        try{
            List<Api_Logger__c> apiLoggerList = new List<Api_Logger__c>();
            WCGTEndPoint__mdt metaRecord = WCGTEndPoint__mdt.getInstance('Client_Contact_Insert');
            
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            // String token = SalesforceToWCGTAccess.getAuthenticationToken();
            SalesforceToWCGTAccess.TokenResponse tokenResp = SalesforceToWCGTAccess.getAuthentication(clientContact.Id);
            apiLoggerList.add(tokenResp.apiLog);
            String endpoint = metaRecord.URL__c + '?stoken=' + tokenResp.token;
            req.setEndpoint(endpoint);
            req.setMethod('POST');
            req.setHeader('Content-Type','application/json');        
            
            // Get Request Wrapper from Helper Class
            String reqBody = salesforceToWCGTHelper.getClientContactRequestBody(clientContact, Flag);
            System.debug('reqBody -->' + reqBody);            
            req.setBody(reqBody);
            
            HttpResponse resp;
            resp = http.send(req);
            System.debug('resp -->'+resp);
            System.debug('resp Body -->'+resp.getBody());
            API_Logger__c apiLog = API_LoggerCommonUtility.createAPILogger(clientContact.Id,reqBody,resp.getBody(),resp.getStatus(),'SyncClientContactToWCGTHelper',endpoint,resp.getStatusCode(),null,null);
            apiLoggerList.add(apiLog);

            if (!apiLoggerList.isEmpty()) {
                return apiLoggerList;
            } else {
                return null;
            }
            
        }
        catch(Exception e){
            System.debug('Error: ' + e.getMessage() + ' in line : ' + e.getLineNumber());
            ErrorLogCreater_cls.apexDebugLogger(e, 'SyncClientContactToWCGTHelper' , 'syncClientContactToWCGT' , clientContact.Id );
            return null;
            //ErrorLogCreater_cls.apexDebugLoggerForAPICallout(e, 'SyncClientContactToWCGTHelper' , 'syncClientContactToWCGT' , '' , reqBody,resp.getBody(), 'https://uat360.wcgt.in/GTSF/api/BDActivity/Insert' );
        }
    }
}