LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/DS_Team_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DS_Team_Approval_Status__c</fullName>
    <label>DS Team Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending with DS</fullName>
            </value>
            <value>
                <fullName>DS Approved</fullName>
            </value>
            <value>
                <fullName>DS Rejected</fullName>
            </value>
            <value>
                <fullName>DS Rework required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/IsNameChange__c.field-meta.xml
<CustomField>
    <fullName>IsNameChange__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for the Name change from update and sync button and restrict other</description>
    <label>Is Name Change</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Mid Market</fullName>
            </value>
            <value>
                <fullName>PIE Audit</fullName>
            </value>
            <value>
                <fullName>Channels - GCC</fullName>
            </value>
            <value>
                <fullName>Channels - Law Firms</fullName>
            </value>
            <value>
                <fullName>Channels - OPC</fullName>
            </value>
            <value>
                <fullName>Channels - PE/VC</fullName>
            </value>
            <value>
                <fullName>Digital Natives</fullName>
            </value>
            <value>
                <fullName>Large Corporates</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
                <isActive>false</isActive>
                <label>Channel</label>
            </value>
            <value>
                <fullName>DGC</fullName>
                <isActive>false</isActive>
                <label>DGC</label>
            </value>
            <value>
                <fullName>Large Corporate</fullName>
                <isActive>false</isActive>
                <label>Large Corporate</label>
            </value>
            <value>
                <fullName>Large Private</fullName>
                <isActive>false</isActive>
                <label>Large Private</label>
            </value>
            <value>
                <fullName>Largest Listed</fullName>
                <isActive>false</isActive>
                <label>Largest Listed</label>
            </value>
            <value>
                <fullName>Listed</fullName>
                <isActive>false</isActive>
                <label>Listed</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>PE Fund</fullName>
                <isActive>false</isActive>
                <label>PE Fund</label>
            </value>
            <value>
                <fullName>PE Investee</fullName>
                <isActive>false</isActive>
                <label>PE Investee</label>
            </value>
            <value>
                <fullName>S M Private</fullName>
                <isActive>false</isActive>
                <label>S M Private</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Sub_Segment__c.field-meta.xml
<CustomField>
    <fullName>Sub_Segment__c</fullName>
    <label>Sub-Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MNC</fullName>
            </value>
            <value>
                <fullName>LC - Large</fullName>
            </value>
            <value>
                <fullName>LC - Emerging</fullName>
            </value>
            <value>
                <fullName>Member Firms</fullName>
            </value>
            <value>
                <fullName>MM - Large</fullName>
            </value>
            <value>
                <fullName>MM - Mid</fullName>
            </value>
            <value>
                <fullName>MM - Small (SMEs)</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Not-for-Profit</fullName>
            </value>
            <value>
                <fullName>Startups</fullName>
            </value>
            <value>
                <fullName>DGC</fullName>
            </value>
            <value>
                <fullName>PIE Audit</fullName>
            </value>
            <value>
                <fullName>Law Firms</fullName>
            </value>
            <value>
                <fullName>PE/VC</fullName>
            </value>
            <value>
                <fullName>OPC</fullName>
            </value>
            <value>
                <fullName>GCC</fullName>
            </value>
            <value>
                <fullName>Academia</fullName>
                <isActive>false</isActive>
                <label>Academia</label>
            </value>
            <value>
                <fullName>Alumni</fullName>
                <isActive>false</isActive>
                <label>Alumni</label>
            </value>
            <value>
                <fullName>BO &amp; family office</fullName>
                <isActive>false</isActive>
                <label>BO &amp; family office</label>
            </value>
            <value>
                <fullName>Banking</fullName>
                <isActive>false</isActive>
                <label>Banking</label>
            </value>
            <value>
                <fullName>CA Firms</fullName>
                <isActive>false</isActive>
                <label>CA Firms</label>
            </value>
            <value>
                <fullName>CFO</fullName>
                <isActive>false</isActive>
                <label>CFO</label>
            </value>
            <value>
                <fullName>CHRO</fullName>
                <isActive>false</isActive>
                <label>CHRO</label>
            </value>
            <value>
                <fullName>CIO CDO CISO</fullName>
                <isActive>false</isActive>
                <label>CIO CDO CISO</label>
            </value>
            <value>
                <fullName>CMO</fullName>
                <isActive>false</isActive>
                <label>CMO</label>
            </value>
            <value>
                <fullName>GLB Listed</fullName>
                <isActive>false</isActive>
                <label>GLB Listed</label>
            </value>
            <value>
                <fullName>Key Account Leaders</fullName>
                <isActive>false</isActive>
                <label>Key Account Leaders</label>
            </value>
            <value>
                <fullName>Law Firm</fullName>
                <isActive>false</isActive>
                <label>Law Firm</label>
            </value>
            <value>
                <fullName>MM - PE</fullName>
                <isActive>false</isActive>
                <label>MM - PE</label>
            </value>
            <value>
                <fullName>Member Firms Leaders</fullName>
                <isActive>false</isActive>
                <label>Member Firms Leaders</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/VerrifiedByDSTeam__c.field-meta.xml
<CustomField>
    <fullName>VerrifiedByDSTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verrified By DS Team</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/UpdateClientNameTest.cls
@isTest 
private class UpdateClientNameTest {
    @testSetup static void setupData(){
        Account keyAccount = TestDataFactory.createAccountRecord();
        keyAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Key Account').getRecordTypeId();
        keyAccount.VerrifiedByDSTeam__c = false;
        keyAccount.DS_Team_Approval_Status__c ='Pending with DS';
        keyAccount.Segment__c = 'Government';
        keyAccount.Sub_Segment__c = 'Government';
        Insert keyAccount;
    }
    
    @isTest static void updateName() {
        Account accountObj =[SELECT Id,IsNameChange__c FROM Account LIMIT 1];
        UpdateClientName.updateName(accountObj);
    }
}