LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Formerly_Known_As__c.field-meta.xml
<CustomField>
    <fullName>Formerly_Known_As__c</fullName>
    <label>Formerly Known As</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Last_Modified_By_for_WCGT__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By_for_WCGT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Modified By for WCGT</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clients4</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/classes/AccountUpdateAndSyncName.cls
public  class AccountUpdateAndSyncName {  
    @InvocableMethod
    public static void invocable(List<Id> accountId){
        if(accountId != null && accountId.size() > 0){
            //sendWhenClientCreation(accountId[0]);
            //
            //Added by Rajat to sync Client name to WCGT
            List<Account> accList = [SELECT Id,Formerly_Known_As__c,Name,Last_Modified_By_for_WCGT__c FROM Account WHERE ID IN: accountId AND Status__c = 'Active'];
            if(accList != null && accList.size() > 0){
               SalesforceToWCGT.changeNameToWCGT(accList[0].Id,accList[0].Formerly_Known_As__c,accList[0].Name);
            }
        }
    }
}