LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/GT_Client_Group__c.field-meta.xml
<CustomField>
    <fullName>GT_Client_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GT Client Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not exist or is not a GT Client</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>GT Client Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/WCGTId__c.field-meta.xml
<CustomField>
    <fullName>WCGTId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>WCGT Id is updated when client is created</description>
    <externalId>true</externalId>
    <inlineHelpText>WCGT Id for Client</inlineHelpText>
    <label>WCGT Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

LinKreta_POC_Repository/force-app/main/default/classes/UpdateClientIdTest.cls
@isTest
public class UpdateClientIdTest {
    
    @isTest
    static void testUpdateClientIds(){
        
        Id clientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        Account testAccount = TestDataFactory.createAccountRecord();
        testAccount.Name = 'Deepak Sir';
        testAccount.RecordTypeId = clientRecordTypeId;
        testAccount.Status__c = 'Active';
        // acc1.GT_Client_Group__c = GtAcc.Id;
        testAccount.ClientAddress__City__s = 'Jaipur';
        testAccount.ClientAddress__CountryCode__s = 'IN';
        testAccount.ClientAddress__PostalCode__s = '789'; 
        testAccount.ClientAddress__StateCode__s = 'AS';
        testAccount.ClientAddress__Street__s = 'test,test';
        //acc1.Key_Account__c = True;
        insert testAccount;
         // Create a JSON string to simulate the request payload
        String jsonString = '{ "WCGTId": "CN058312", "SFDCRecordID": "' + testAccount.Id + '" }';

        // Simulate the HTTP request to the REST service
        Test.startTest();
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/updateClientId';
        request.httpMethod = 'PUT';
        request.requestBody = Blob.valueOf(jsonString);
        RestContext.request = request;

        String response = UpdateClientId.doPut();
        Test.stopTest();

        // Perform assertions on the response received
        System.assertEquals('The WCGT ID has been Successfully Updated', response);

        // Query the Account record to verify the update
        Account updatedAccount = [SELECT Id, WCGTId__c FROM Account WHERE Id = :testAccount.Id LIMIT 1];
        System.assertEquals('CN058312', updatedAccount.WCGTId__c);
    }
    
     @isTest
    static void testUpdateClientIds1() {
         Id clientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        Account testAccount = TestDataFactory.createAccountRecord();
        testAccount.Name = 'Deepak Sir';
        testAccount.RecordTypeId = clientRecordTypeId;
        testAccount.Status__c = 'Active';
        // acc1.GT_Client_Group__c = GtAcc.Id;
        testAccount.ClientAddress__City__s = 'Jaipur';
        testAccount.ClientAddress__CountryCode__s = 'IN';
        testAccount.ClientAddress__PostalCode__s = '789'; 
        testAccount.ClientAddress__StateCode__s = 'AS';
        testAccount.ClientAddress__Street__s = 'test,test';
        //acc1.Key_Account__c = True;
        insert testAccount;

        // Create a JSON string to simulate the request payload with SFDCRecordID as null
        String jsonStringNullSFDCRecordID = '{ "WCGTId": "CN058312", "SFDCRecordID": null }';

        // Simulate the HTTP request to the REST service with null SFDCRecordID
        Test.startTest();
        RestRequest requestNullSFDCRecordID = new RestRequest();
        requestNullSFDCRecordID.requestURI = '/services/apexrest/updateClientContactId';
        requestNullSFDCRecordID.httpMethod = 'PUT';
        requestNullSFDCRecordID.requestBody = Blob.valueOf(jsonStringNullSFDCRecordID);
        RestContext.request = requestNullSFDCRecordID;

        String responseNullSFDCRecordID = UpdateClientId.doPut();
        Test.stopTest();

        // Perform assertions on the response received for null SFDCRecordID
        System.assertEquals('The SFDC Record ID cannot be Blank or Empty', responseNullSFDCRecordID);
    
    }
    

}