LinKreta_POC_Repository/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Client Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Client Creation</label>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
                <color>#FFCC33</color>
                <label>Pending Verification</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>⛔ Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ExpertisePL__c/ExpertisePL__c.object-meta.xml
<CustomObject>
    <description>This object is part of the custom functionality for managing the dependency between the 3 Picklists on the Lead object namely Solution (Single Picklist), Expertise (Multi Picklist) and Sub Expertise (Multi Picklist). It stores the List of Values (LOV) configured for the field named Expertise.</description>
    <label>Expertise (PL)</label>
    <nameField>
        <displayFormat>EX - {000000}</displayFormat>
        <label>Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expertise (PL)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/ExpertisePL__c/fields/LOV__c.field-meta.xml
<CustomField>
    <fullName>LOV__c</fullName>
    <description>This stores the List of Value added to the field named Expertise (Expertise__c) on the Lead object.</description>
    <label>LOV</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/ExpertisePL__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <description>This stores and represents the dependency between the Solution (Controlling) field and the Expertise (Controlled) field.</description>
    <label>Solution</label>
    <referenceTo>SolutionPL__c</referenceTo>
    <relationshipLabel>Expertise</relationshipLabel>
    <relationshipName>Expertise</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Joint_Venture__c/Joint_Venture__c.object-meta.xml
<CustomObject>
    <label>Joint Venture</label>
    <nameField>
        <label>Joint Venture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Joint Ventures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Joint_Venture__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Venture</relationshipLabel>
    <relationshipName>Joint_Venture</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SME_PL__c/SME_PL__c.object-meta.xml
<CustomObject>
    <label>SME(PL)</label>
    <nameField>
        <displayFormat>SME-{000000}</displayFormat>
        <label>SME(PL) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SME(PL)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/SME_PL__c/fields/LOV__c.field-meta.xml
<CustomField>
    <fullName>LOV__c</fullName>
    <label>LOV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SME_PL__c/fields/Sub_Expertise_PL__c.field-meta.xml
<CustomField>
    <fullName>Sub_Expertise_PL__c</fullName>
    <label>Sub Expertise (PL)</label>
    <referenceTo>SubExpertisePL__c</referenceTo>
    <relationshipLabel>SME(PL)</relationshipLabel>
    <relationshipName>SME_PL</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SolutionPL__c/SolutionPL__c.object-meta.xml
<CustomObject>
    <description>This object is part of the custom functionality for managing the dependency between the 3 Picklists on the Lead object namely Solution (Single Picklist), Expertise (Multi Picklist) and Sub Expertise (Multi Picklist). It stores the List of Values (LOV) configured for the field named Solution.</description>
    <label>Solution (PL)</label>
    <nameField>
        <displayFormat>SN - {000000000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solutions (PL)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/SolutionPL__c/fields/LOV__c.field-meta.xml
<CustomField>
    <fullName>LOV__c</fullName>
    <description>This stores the List of Value added to the field named Solution (Solution__c) on the Lead object.</description>
    <label>LOV</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SubExpertisePL__c/SubExpertisePL__c.object-meta.xml
<CustomObject>
    <description>This object is part of the custom functionality for managing the dependency between the 3 Picklists on the Lead object namely Solution (Single Picklist), Expertise (Multi Picklist) and Sub Expertise (Multi Picklist). It stores the List of Values (LOV) configured for the field named Sub Expertise.</description>
    <label>Sub Expertise (PL)</label>
    <nameField>
        <displayFormat>SE - {000000}</displayFormat>
        <label>Sub Expertise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Expertise (PL)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/SubExpertisePL__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <description>This stores and represents the dependency between the Expertise (Controlling) field and Sub Expertise (Controlled) field.</description>
    <label>Expertise</label>
    <referenceTo>ExpertisePL__c</referenceTo>
    <relationshipLabel>Sub Expertise</relationshipLabel>
    <relationshipName>Sub_Expertise</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SubExpertisePL__c/fields/LOV__c.field-meta.xml
<CustomField>
    <fullName>LOV__c</fullName>
    <description>This stores the List of Value added to the field named Sub Expertise (SubExpertise__c) on the Lead object.</description>
    <label>LOV</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/SubExpertisePL__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <formula>Expertise__r.SolutionLOV__c</formula>
    <label>Solution</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/JointVentureTriggerTest.cls
@isTest
public class JointVentureTriggerTest {
    @isTest
    public static void unitTest1(){
        Test.setMock(HttpCalloutMock.class, new ELControllerTest_Mock());
        Account accountRecord = TestDataFactory.createAccountRecord(); 
        accountRecord.Status__c = 'Active';   
        insert accountRecord; 
		        
     //   IntegratedEnquiry__c IntegratedEnquiryRecord = TestDataFactory.createIntegratedEnquiryRecord();   
      //  insert IntegratedEnquiryRecord;
    /*    
        SolutionPL__c solution = new SolutionPl__c(LOV__c = 'NA');
        Insert solution;
        ExpertisePL__c expertise = new ExpertisePL__c(Solution__c = solution.Id, LOV__c = 'NA');
        Insert expertise;
        SubExpertisePL__c subExpertise = new SubExpertisePL__c(LOV__c = 'NA', Expertise__c = expertise.Id);
        Insert subExpertise;
        SME_PL__c smeLU = new SME_PL__c(Sub_Expertise_PL__c = subExpertise.Id);
        INSERT smeLU;  
*/
	//	list<opportunity> oppList = TestDataFactory.createEnquiryRecord(accountRecord.id,IntegratedEnquiryRecord.id,smeLU.id);       
    //    insert oppList;
        
        
        Joint_Venture__c jvObj = new Joint_Venture__c(Name = 'Test JV 1',Client__c = accountRecord.Id);
        insert jvObj;
    }
}