LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>New Client Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Contact_status__c.field-meta.xml
<CustomField>
    <fullName>Contact_status__c</fullName>
    <defaultValue>&apos;New Contact Creation&apos;</defaultValue>
    <label>Contact status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Contact Creation</fullName>
                <color>#FF6666</color>
                <default>true</default>
                <label>New Contact Creation</label>
            </value>
            <value>
                <fullName>Pending DS Team Approval</fullName>
                <color>#FFCC33</color>
                <label>Pending DS Team Approval</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#999999</color>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Industry_Leader__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/IsPardot__c.field-meta.xml
<CustomField>
    <fullName>IsPardot__c</fullName>
    <label>IsPardot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pardot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Enquiry Prioritization</inlineHelpText>
    <label>Prospect Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Hot</fullName>
                <default>true</default>
                <label>Hot</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/CCApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>CCApprovalRejectionRecommendation__c</fullName>
    <description>It depicts the Approval / Rejection recommendation status.</description>
    <inlineHelpText>Client Council Recommendations</inlineHelpText>
    <label>CC_Approval / Rejection Recommendation</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/CCApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>CCApprovalStatus__c</fullName>
    <description>It depicts the Approval status for particular lead.</description>
    <inlineHelpText>Client Take-On Approval Status</inlineHelpText>
    <label>CC_Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <inlineHelpText>Source of the Client</inlineHelpText>
    <label>Referral Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Channel_query_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_query_Request_Type__c</fullName>
    <label>Channel &amp; query Request Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/ClientBackground__c.field-meta.xml
<CustomField>
    <fullName>ClientBackground__c</fullName>
    <description>It depicts Client Background.</description>
    <label>Client Background</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/ClientContact__c.field-meta.xml
<CustomField>
    <fullName>ClientContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which Client Contact has referred this Lead.</description>
    <inlineHelpText>Referral from existing client contact</inlineHelpText>
    <label>Client Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Contact_status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <inlineHelpText>Country code of contact number</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code_Name</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/EntityId__c.field-meta.xml
<CustomField>
    <fullName>EntityId__c</fullName>
    <label>SIC Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Expertise_LT__c.field-meta.xml
<CustomField>
    <fullName>Expertise_LT__c</fullName>
    <label>Expertise</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/External_Database_Source__c.field-meta.xml
<CustomField>
    <fullName>External_Database_Source__c</fullName>
    <label>External Database Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CapIQ</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/GrowthPotential__c.field-meta.xml
<CustomField>
    <fullName>GrowthPotential__c</fullName>
    <label>Growth Potential Of Client</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/HowDidYouArriveAThisTentativeFee__c.field-meta.xml
<CustomField>
    <fullName>HowDidYouArriveAThisTentativeFee__c</fullName>
    <label>How did you arrive at this tentative fee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/IL_ApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>IL_ApprovalRejectionRecommendation__c</fullName>
    <label>IL Approval / Rejection Recommendation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry_Business_Partner__c.field-meta.xml
<CustomField>
    <fullName>Industry_Business_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Business Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>New_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry_Leader__c.field-meta.xml
<CustomField>
    <fullName>Industry_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which user has referred this lead.</description>
    <label>Industry Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads4</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/IndustryLeaderApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>IndustryLeaderApprovalStatus__c</fullName>
    <label>Industry Leader Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/MCA_ID__c.field-meta.xml
<CustomField>
    <fullName>MCA_ID__c</fullName>
    <label>MCA ID</label>
    <type>TextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low Recovery/ Low Fees</fullName>
            </value>
            <value>
                <fullName>Background check required</fullName>
            </value>
            <value>
                <fullName>Political connection</fullName>
            </value>
            <value>
                <fullName>Ambiguity regarding company</fullName>
            </value>
            <value>
                <fullName>Founder/Promoter reputation</fullName>
            </value>
            <value>
                <fullName>Channel 1 v/s Channel 2 conflict</fullName>
            </value>
            <value>
                <fullName>Market Fitment issue</fullName>
            </value>
            <value>
                <fullName>Not inline with GT way</fullName>
            </value>
            <value>
                <fullName>Other risk associated with entity</fullName>
            </value>
            <value>
                <fullName>Other Risk Concerns</fullName>
            </value>
            <value>
                <fullName>No response</fullName>
            </value>
            <value>
                <fullName>Lost client to competition</fullName>
            </value>
            <value>
                <fullName>Lost client due to pricing</fullName>
            </value>
            <value>
                <fullName>Lost client – other reasons</fullName>
            </value>
            <value>
                <fullName>Rejected by Client Council</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/ShortSummary__c.field-meta.xml
<CustomField>
    <fullName>ShortSummary__c</fullName>
    <inlineHelpText>Provide a short summary about the professional services required, or any additional remarks regarding the client</inlineHelpText>
    <label>Summary (Challenges, Opportunities etc)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/SMEG_LT__c.field-meta.xml
<CustomField>
    <fullName>SMEG_LT__c</fullName>
    <label>SMEG</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/TentativeFee__c.field-meta.xml
<CustomField>
    <fullName>TentativeFee__c</fullName>
    <label>Tentative Fee</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/WCGTStatus__c.field-meta.xml
<CustomField>
    <fullName>WCGTStatus__c</fullName>
    <label>WCGTStatus</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academia</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni – GT@Industry</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>BO &amp; family office</fullName>
    </customValue>
    <customValue>
        <fullName>Business development efforts</fullName>
    </customValue>
    <customValue>
        <fullName>CA Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>CFO</fullName>
    </customValue>
    <customValue>
        <fullName>Chamber</fullName>
        <label>Chambers</label>
    </customValue>
    <customValue>
        <fullName>CHRO</fullName>
    </customValue>
    <customValue>
        <fullName>CIO CDO CISO</fullName>
    </customValue>
    <customValue>
        <fullName>Client Past Relationships / Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>Client Referral</fullName>
    </customValue>
    <customValue>
        <fullName>CMO</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Calling / Business Development</fullName>
    </customValue>
    <customValue>
        <fullName>Corridors</fullName>
    </customValue>
    <customValue>
        <fullName>Cross Sell</fullName>
        <label>Cross Sell / Up Sell Enquiries</label>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>External Events</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>GCC</fullName>
    </customValue>
    <customValue>
        <fullName>Global Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>GT Employee</fullName>
    </customValue>
    <customValue>
        <fullName>GT Events</fullName>
    </customValue>
    <customValue>
        <fullName>GT Member Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Referrals - GT Firm Personnel</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Referrals - Intermediary Firm</fullName>
    </customValue>
    <description>It depicts the Lead Channel information, from where the Lead is coming.</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Country_Code_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Algeria (+213)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (+376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (+1264)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua &amp; Barbuda (+1268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia (+61)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (+1242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (+1246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (+1441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia Herzegovina (+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana (+267)</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil (+55)</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei (+673)</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria (+359)</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso (+226)</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi (+257)</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia (+855)</fullName>
    </customValue>
    <customValue>
        <fullName>India (+91)</fullName>
    </customValue>
    <masterLabel>Country Code Name</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/LeadTriggerHandlerTest.cls
@isTest
public class LeadTriggerHandlerTest {
  @TestSetup
    static void dataCreation() { 
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        List<Lead> leadList = new List<Lead>();
        Lead leadRecord =  TestDataFactory.createLeadRecord();
        leadRecord.Industry_Leader__c =UserInfo.getUserId();
        leadRecord.Industry__c ='Banking';
        leadRecord.Status = 'NotAccept';
        leadRecord.Reject_Reason__c = 'No response';
        leadRecord.Reject_Reason__c = 'No response';
        leadRecord.Email ='Test32@233test.com';
        leadRecord.CountryCode__c ='India (+91)';
        leadList.add(leadRecord);
        /*Lead leadRecord1 =  TestDataFactory.createLeadRecord();
        leadRecord1.Industry_Leader__c =UserInfo.getUserId();
        leadRecord1.Industry__c ='Banking';
        leadRecord1.LeadSource='Manual';
        leadRecord1.Channel__c  ='Client Referral';
        leadRecord1.IsPardot__c='Pardot';
        leadRecord1.pi__campaign__c ='Test campaignObj';
        leadList.add(leadRecord1);*/
       
        insert leadList;

        Campaign  campaignObj = TestDataFactory.createCampaign();
        campaignObj.Name ='Test campaignObj';
        insert campaignObj;

    } 
    @isTest static void testUpdate(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadObj = [SELECT Id FROM Lead LIMIT 1];  
        //leadObj.IndustryLeaderApprovalStatus__c ='Approved'; //Phase-1
        leadObj.WCGTStatus__c = 1;
        update leadObj;
        Test.stopTest();    
         
     } 
     @isTest static void testUpdate1(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadObj = [SELECT Id FROM Lead LIMIT 1];  
        leadObj.Category__c ='Cold';
        update leadObj;   
        Test.stopTest(); 
         
     } 
     @isTest static void testUpdate2(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadObj = [SELECT Id FROM Lead LIMIT 1];  
       // leadObj.IndustryLeaderApprovalStatus__c ='Approved'; //Phase-1
        leadObj.WCGTStatus__c = null;
        update leadObj;   
        Test.stopTest(); 
         
     } 
     @isTest static void testUpdatePardot(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadObj = [SELECT Id FROM Lead LIMIT 1];  
        leadObj.IsPardot__c='Pardot';
        leadObj.pi__campaign__c ='Test campaignObj';
        update leadObj;   
        Test.stopTest(); 
         
     } 
     @isTest static void testUpdate3(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadObj = [SELECT Id FROM Lead LIMIT 1];  
        leadObj.Status ='Accept Client';
        //leadObj.CCApprovalStatus__c ='Approved';
        update leadObj;   
        Test.stopTest(); 
         
     } 
     @isTest static void testUpdate4(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Contact contactObj = TestDataFactory.createContactRecord();
        contactObj.Contact_status__C = 'Active';
        insert contactObj;
        System.Debug('** Test contactObj   '+contactObj);
       // IntegratedEnquiry__c intg =  TestDataFactory.createIntegratedEnquiryRecord();
        //intg.ClientContact__c = contactObj.Id;
      //  insert intg ;
       
        //System.Debug('** Test intg   '+intg);
        Lead leadRecord1 =  TestDataFactory.createLeadRecord();
        leadRecord1.Industry_Leader__c =UserInfo.getUserId();
        leadRecord1.Industry__c ='Banking';
        leadRecord1.LeadSource='Manual';
        leadRecord1.Channel__c  ='Client Referral';
        leadRecord1.IsPardot__c='Pardot';
        leadRecord1.pi__campaign__c ='Test campaignObj';
        leadRecord1.ClientContact__c = contactObj.Id;
        leadRecord1.CountryCode__c ='India (+91)';
        insert leadRecord1;
        System.Debug('** Test leadRecord1   '+leadRecord1);
        //  IntegratedEnquiry__c ie = [SELECT Id,Name,ClientContact__c FROM IntegratedEnquiry__c WHERE ClientContact__c=:leadRecord1.ClientContact__c LIMIT 1];
        //System.Debug('** Test ie   '+ie);
       
        Campaign  campaignObj = TestDataFactory.createCampaign();
        campaignObj.Name ='Test campaignObj';
        insert campaignObj;
        Test.stopTest();
         
     } 

     @isTest static void testUpdateCapIQId(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadObj =  TestDataFactory.createLeadRecord();
        leadObj.Industry_Leader__c =UserInfo.getUserId();
        leadObj.Industry__c ='Banking';
        leadObj.Status = 'NotAccept';
        leadObj.Reject_Reason__c = 'No response';
        leadObj.Reject_Reason__c = 'No response';
        leadObj.Email ='Test32@233test.com';
        leadObj.capIQId__c='IQ314677034';
        leadObj.External_Database_Source__c = 'CapIQ'; 
        leadObj.CountryCode__c ='India (+91)';
        insert leadObj;
        leadObj.capIQId__c='IQ707966458';
        
        update leadObj;
        Test.stopTest();           
     } 
     @isTest static void testUpdateEntityId(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadObj =  TestDataFactory.createLeadRecord();
        leadObj.Industry_Leader__c =UserInfo.getUserId();
        leadObj.Industry__c ='Banking';
        leadObj.Status = 'NotAccept';
        leadObj.Reject_Reason__c = 'No response';
        leadObj.Reject_Reason__c = 'No response';
        leadObj.Email ='Test32@233test.com';
        leadObj.EntityId__c='L22210MH1995PLC084781';
        leadObj.External_Database_Source__c = 'MCA'; 
        leadObj.CountryCode__c ='India (+91)';
        insert leadObj;
        leadObj.EntityId__c='L27100MH1907PLC000260';
        
        update leadObj;
        Test.stopTest(); 
    } 
     @isTest static void testUpdateMCA_Id(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadObj =  TestDataFactory.createLeadRecord();
        leadObj.Industry_Leader__c =UserInfo.getUserId();
        leadObj.Industry__c ='Banking';
        leadObj.Status = 'NotAccept';
        leadObj.Reject_Reason__c = 'No response';
        leadObj.Reject_Reason__c = 'No response';
        leadObj.Email ='Test32@233test.com';
        leadObj.MCA_ID__c='KCO000008144326G';
        leadObj.External_Database_Source__c = 'MCA'; 
        leadObj.CountryCode__c ='India (+91)';
        insert leadObj;
        leadObj.MCA_ID__c='KCO000008871309H';
        update leadObj;
        Test.stopTest(); 
     } 

     @isTest static void testUpdateIndustryLeader(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        User user =TestDataFactory.createUser(pf.Id);
        insert user;
        Lead leadObj = [SELECT Id FROM Lead LIMIT 1];  
        leadObj.Industry_Leader__c = user.Id;
        leadObj.Industry_Business_Partner__c =user.Id;
        update leadObj;
        Test.stopTest();
    }
    @isTest static void testWebsite(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadRecord1 =  TestDataFactory.createLeadRecord();
        leadRecord1.Industry_Leader__c =UserInfo.getUserId();
        leadRecord1.Industry__c ='Banking';
        leadRecord1.LeadSource='Website';
        leadRecord1.Email ='Banking@te77st.com';
        leadRecord1.Channel_query_Request_Type__c = 'Services';
        leadRecord1.CountryCode__c ='India (+91)';
        insert leadRecord1;
        List<Lead> lstLead = new List<Lead>();
        lstLead.add(leadRecord1);
        LeadTriggerHandler.isBeforeDelete(lstLead);
        Test.stopTest();
         
     } 
     /*
     @isTest static void testUpdateIApprovalStatus(){
        Test.startTest();
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadRecord =  TestDataFactory.createLeadRecord();
        leadRecord.Industry_Leader__c =UserInfo.getUserId();
        leadRecord.Industry__c ='Banking';
        //leadRecord.Status = 'NotAccept';
        leadRecord.Email ='Test32@233test.com';
        //leadRecord.IndustryLeaderApprovalStatus__c = 'Approved'; //Phase-1
       // leadRecord.Expertise_LT__c = 'test';
        //leadRecord.SMEG_LT__c ='test';
        leadRecord.Company ='testyuong';
        leadRecord.ClientBackground__c = '1';
        leadRecord.GrowthPotential__c = '2';
        leadRecord.TentativeFee__c =  1;
        leadRecord.HowDidYouArriveAThisTentativeFee__c = 'testyuong';
        leadRecord.ShortSummary__c = 'testyuong';
        leadRecord.CountryCode__c ='India (+91)';
        leadRecord.MobilePhone = 
        
        insert  leadRecord;
        List<Task> taskList =new List<Task>();
        Task task =  TestDataFactory.createTaskRecord();
        task.WhoId =leadRecord.Id;
        task.Subject = 'Enrichment of Segmentation Details of New Client';
        taskList.add(task);
        Task task1 =  TestDataFactory.createTaskRecord();
        task1.WhoId =leadRecord.Id;
        task1.Subject = 'Next steps & actions discussed with NSL';
        taskList.add(task1);
        Task task2 =  TestDataFactory.createTaskRecord();
        task2.WhoId =leadRecord.Id;
        task2.Subject = 'NSL Discussion Pending';
        taskList.add(task2);

        Task task3 =  TestDataFactory.createTaskRecord();
        task3.WhoId =leadRecord.Id;
        task3.Subject = 'New Client Owner based on NSL discussion';
        taskList.add(task3);

        Task task4 =  TestDataFactory.createTaskRecord();
        task4.WhoId =leadRecord.Id;
        task4.Subject = 'Client Engagement';
        taskList.add(task4);

        Task task5 =  TestDataFactory.createTaskRecord();
        task5.WhoId =leadRecord.Id;
        task5.Subject = 'Client Take-On Preparation Deck';
        taskList.add(task5);
        


        
        insert taskList;
        leadRecord.Status = 'Internal / External Discussions';
        //leadRecord.IL_ApprovalRejectionRecommendation__c ='test';// Phase-1
        //leadRecord.CCApprovalRejectionRecommendation__c = 'test'; // Phase-1
        update leadRecord;
        Test.stopTest(); 
     } 
     */
   /*  @isTest static void testApprove(){
        GenericMockClass mock= new GenericMockClass (200,'success','{"statusCode":"200","statusMsg":"Record inserted Successfully","data":""}');
        Test.setMock(HttpCalloutMock.class,mock);
        Lead leadObj = [SELECT Id FROM Lead LIMIT 1]; 
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(leadObj.id);
       // app.setProcessDefinitionNameOrId('test');
        app.setComments('Approv');
        Approval.ProcessResult result = Approval.process(app);
    } */
     
}