LinKreta_POC_Repository/force-app/main/default/objects/Currency_Code__c/Currency_Code__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the Currency ISO codes and their relevant data</description>
    <label>Currency Code</label>
    <nameField>
        <label>Currency ISO Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currency Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Currency_Code__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <externalId>true</externalId>
    <label>Currency Code</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Currency_Code__c/fields/Currency_Name__c.field-meta.xml
<CustomField>
    <fullName>Currency_Name__c</fullName>
    <label>Currency Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/CurrencyConversionWCGT_clsTest.cls
@isTest
private class CurrencyConversionWCGT_clsTest {
    @isTest
    static void testcurrencyCode() {
        Test.setMock(HttpCalloutMock.class, new CurrencyConversionWCGTMockCallout());
        Currency_Code__c currency_codeObj = new Currency_Code__c(
            Name = 'RS',
            CurrencyIsoCode = 'INR',
            Currency_Code__c = 'CU000001',
            Currency_Name__c = 'Indian Rupee');
        insert currency_codeObj;
        
        List<Currency_Code__c> currencyId = new List<Currency_Code__c>();
        currencyId.add(currency_codeObj);
        
        CurrencyConversionWCGT_cls.currencyCode(currencyId);
        
    }
    
    @isTest
    static void testGetCurrencyRate() {
        Test.setMock(HttpCalloutMock.class, new CurrencyConversionWCGTMockCallout());
        Currency_Code__c currency_codeObj = new Currency_Code__c(
            Name = 'RS',
            CurrencyIsoCode = 'INR',
            Currency_Code__c = 'CU000001',
            Currency_Name__c = 'Indian Rupee');
        insert currency_codeObj;
        
        List<Currency_Code__c> currencyId = new List<Currency_Code__c>();
        currencyId.add(currency_codeObj);
        
        CurrencyConversionWCGT_cls.getCurrencyRate(currency_codeObj);
    }
    
     @isTest
    static void testUpdateCurrency() {
        Test.setMock(HttpCalloutMock.class, new CurrencyConversionWCGTMockCallout());
        Currency_Code__c currency_codeObj = new Currency_Code__c(
            Name = 'RS',
            CurrencyIsoCode = 'INR',
            Currency_Code__c = 'CU000001',
            Currency_Name__c = 'Indian Rupee');
        insert currency_codeObj;
        
        List<Currency_Code__c> currencyId = new List<Currency_Code__c>();
        currencyId.add(currency_codeObj);
        
        HttpResponse res = new HttpResponse();
        res.setStatus('OK');
        res.setStatusCode(200);
        res.setBody('{"rates":"82","up_Date":"20-20-2023"}');
        
        CurrencyConversionWCGT_cls.updateCurrency(currency_codeObj,res);
    }
    
}