LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/Client_Contact_Relationship_Team__c.object-meta.xml
<CustomObject>
    <label>Client Contact Relationship Team</label>
    <nameField>
        <displayFormat>CCRT-{0000}</displayFormat>
        <label>Client Contact Relationship Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Contact Relationship Team</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Relationship_Team__c/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Contact Relationship Team</relationshipLabel>
    <relationshipName>Client_Contact_Relationship_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains information of &quot;Client Contact&quot; of the new client on conversion of which contact record is created.</description>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/Batch_SyncClientContactTeam.cls
/*
    Created by : Suraj Kumar
    Date : 03-09-2023
    Description : This class is scheduled to run daily evening and send Client Contact Relationship Team details whenever they are created or 
    updated to WCGT.
*/

global class Batch_SyncClientContactTeam implements Database.Batchable<SObject>, Database.AllowsCallouts{
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(SyncClientContactTeamHandler.getQuery());
    }
    
    global void execute(Database.BatchableContext bc, List<Client_Contact_Relationship_Team__c> relationshipTeamList){
        try{
            Set<Id> clientContactIds = new Set<Id>();
            for(Client_Contact_Relationship_Team__c teamMember : relationshipTeamList){
                if(teamMember.Client_Contact__c != null){
                    clientContactIds.add(teamMember.Client_Contact__c );
                }
            }
            
            if(!clientContactIds.isEmpty()){
                SyncClientContactTeamHandler.getRelationshipTeamMembers(clientContactIds);
            }
            
        }
        catch(Exception e){
            System.debug('Exception : ' + e.getMessage() + ' in Line : ' + e.getLineNumber());
        }
    }
    
    global void finish(Database.BatchableContext bc){
        
    }
}