LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/Client_Contact_Directory__c.object-meta.xml
<CustomObject>
    <description>This object contains the information of Client Contact record.</description>
    <label>Client Contact Directory</label>
    <nameField>
        <displayFormat>CCD-{0000}</displayFormat>
        <label>Client Contact Directory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Contact Directory</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/fields/BOD_Flag__c.field-meta.xml
<CustomField>
    <fullName>BOD_Flag__c</fullName>
    <label>BOD Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Contact Directory</relationshipLabel>
    <relationshipName>Client_Contact_Directory</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/fields/Client_Contact_Source__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact_Source__c</fullName>
    <label>Client Contact Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CapIq</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
            <value>
                <fullName>Introhive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/fields/Key_Contact_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Key_Contact_Identifier__c</fullName>
    <label>Key Contact Identifier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>BOD</fullName>
            </value>
            <value>
                <fullName>KMP</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/fields/Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sector__c</fullName>
    <label>Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/BOD_Flag__c.field-meta.xml
<CustomField>
    <fullName>BOD_Flag__c</fullName>
    <label>BOD Flag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains information of &quot;Client Contact&quot; of the new client on conversion of which contact record is created.</description>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Client_Contact_Source__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact_Source__c</fullName>
    <label>Client Contact Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CapIq</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
            <value>
                <fullName>Introhive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sector__c</fullName>
    <description>This field contains value of sub sector of associated client record.</description>
    <formula>TEXT( Account.Industry__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/EAPartnerLogin_Mapper__c/EAPartnerLogin_Mapper__c.object-meta.xml
<CustomObject>
    <description>This object has been created as part of the LinKreta initiative and is a part of the function to support an EA to login as a Partner. The purpose of this object is to capture the Partners that a specific EA can login as.</description>
    <label>EA Partner Login Mapper</label>
    <nameField>
        <displayFormat>EA PL MID - {000000000}</displayFormat>
        <label>EA Partner Login Mapper ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EA Partner Login Mapper</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/EAPartnerLogin_Mapper__c/fields/EAUser__c.field-meta.xml
<CustomField>
    <fullName>EAUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EA User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select an Active Standard User that must have Employee Id</errorMessage>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.EMP_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>EA_Login_Mapper</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/EAPartnerLogin_Mapper__c/fields/Mapping_Id__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Id__c</fullName>
    <externalId>true</externalId>
    <label>Mapping Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/EAPartnerLogin_Mapper__c/fields/PartnerUser__c.field-meta.xml
<CustomField>
    <fullName>PartnerUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select an Active Standard User</errorMessage>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.EMP_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>EALoginMapper_PartnerUser</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <inlineHelpText>Country code of contact number</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code_Name</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Enquiry_Type__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Type__c</fullName>
    <description>This field contains the category information of enquiry.</description>
    <label>Enquiry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Type</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/EMP_ID__c.field-meta.xml
<CustomField>
    <fullName>EMP_ID__c</fullName>
    <externalId>true</externalId>
    <label>Employee ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/IS_DELETED__c.field-meta.xml
<CustomField>
    <fullName>IS_DELETED__c</fullName>
    <label>IS_DELETED</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Country_Code_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Algeria (+213)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (+376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (+1264)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua &amp; Barbuda (+1268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia (+61)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (+1242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (+1246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (+1441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia Herzegovina (+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana (+267)</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil (+55)</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei (+673)</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria (+359)</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso (+226)</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi (+257)</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia (+855)</fullName>
    </customValue>
    <masterLabel>Country Code Name</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Enquiry_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business as Usual (BAU)</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic (STR)</fullName>
    </customValue>
    <masterLabel>Enquiry Type</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/EAPartnerRecordAccessUtilsTest.cls
@isTest
public with sharing class EAPartnerRecordAccessUtilsTest {
    @testSetup static void dataCreation() {
        
        List<User> listUser = new List<User>();
        
        User userEA =   TestDataFactory.createUserRecord();
        userEA.EMP_ID__c = 'Test1';
        userEA.IsActive = true;
        userEA.Username='testx1.t@gmail.com';
        userEA.Alias ='tu2';
        User userEA2 =   TestDataFactory.createUserRecord();
        userEA2.EMP_ID__c = 'Test11';
        userEA2.IsActive = true;
        userEA2.Username='testx11.t@gmail.com';
        userEA2.Alias ='tu21';
        User userPartnerUser =   TestDataFactory.createUserRecord();
        userPartnerUser.EMP_ID__c = 'Test2';
        userPartnerUser.IsActive = true;
        
        listUser.add(userEA);
        listUser.add(userPartnerUser);
        listUser.add(userEA2);
        
        insert listUser;
        
        //Create Contact
        Contact cont = TestDataFactory.createContact();
        Insert cont;
    }
    
    @isTest static void createEAPartnerLoginMapper(){
        String contId = [SELECT Id FROM Contact LIMIT 1].Id;
        List<User> lstUser = [SELECT Id,EMP_ID__c FROM user where EMP_ID__c in('Test1','Test2','Test11') ];
        system.debug('lstUser>>>'+lstUser);
        
        Group grp = new Group();
        grp.DeveloperName = lstUser[1].EMP_ID__c+'_EA_Group';
        grp.Name = lstUser[1].EMP_ID__c+'_EA_Group';
        Insert grp;
        
        EAPartnerLogin_Mapper__c objEAPartnerLogin = new EAPartnerLogin_Mapper__c();
        objEAPartnerLogin.EAUser__c = lstUser[0].Id;
        objEAPartnerLogin.Mapping_Id__c = 'TestOnw';
        objEAPartnerLogin.PartnerUser__c = lstUser[1].Id;
        objEAPartnerLogin.Is_Deleted__c = false;
        
     
        lead leadObj = new lead();
        leadObj.FirstName = 'parle';
        leadObj.CountryCode__c = 'Algeria (+213)';
        leadObj.Email = 'rak@gmail.com';
        leadObj.Enquiry_Type__c = 'Business as Usual (BAU)';
        leadObj.LastName = 'India';
        leadObj.Industry__c = 'Asset Management';
        leadObj.Description = 'Test';  
        leadObj.ownerid = lstUser[1].Id;
        leadObj.Company = 'parle';
        List<Lead> leadlst = new List<Lead>();
        leadlst.add(leadObj);
        Insert leadlst;
        
        List<Client_Contact_Directory__c> ClientContactDirectorylst = new List<Client_Contact_Directory__c>();
        Client_Contact_Directory__c ClientContactDirectoryObj = new Client_Contact_Directory__c(
            BOD_Flag__c = 'No',
            Client_Contact_Source__c = 'None',
            Client_Contact__c = contId,
            Client_Location__CountryCode__s = 'IN',
            Country_Code__c = 'Algeria (+213)',
            Email__c = 'aortega@gcfund.org',
            Key_Contact_Identifier__c = 'None',
            Mailing_Address__CountryCode__s = 'IN',
            Mobile__c = '9999999999',
            Sub_Sector__c = 'Agriculture',
            OwnerId = lstUser[1].Id);
        ClientContactDirectorylst.add(ClientContactDirectoryObj);
        insert ClientContactDirectorylst;
        
        EAPartnerRecordAccessUtils.EAShareRecor(leadlst,'LeadShare','LeadId','LeadAccessLevel');
        EAPartnerRecordAccessUtils.EAShareRecor(ClientContactDirectorylst,'Client_Contact_Directory__Share');
        
    }
}