LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/Client_Contact_Directory__c.object-meta.xml
<CustomObject>
    <description>This object contains the information of Client Contact record.</description>
    <label>Client Contact Directory</label>
    <nameField>
        <displayFormat>CCD-{0000}</displayFormat>
        <label>Client Contact Directory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Contact Directory</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/fields/BOD_Flag__c.field-meta.xml
<CustomField>
    <fullName>BOD_Flag__c</fullName>
    <label>BOD Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Contact Directory</relationshipLabel>
    <relationshipName>Client_Contact_Directory</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/fields/Client_Contact_Source__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact_Source__c</fullName>
    <label>Client Contact Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CapIq</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
            <value>
                <fullName>Introhive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/fields/Key_Contact_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Key_Contact_Identifier__c</fullName>
    <label>Key Contact Identifier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>BOD</fullName>
            </value>
            <value>
                <fullName>KMP</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Client_Contact_Directory__c/fields/Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sector__c</fullName>
    <label>Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/BOD_Flag__c.field-meta.xml
<CustomField>
    <fullName>BOD_Flag__c</fullName>
    <label>BOD Flag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains information of &quot;Client Contact&quot; of the new client on conversion of which contact record is created.</description>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Contacts</relationshipLabel>
    <relationshipName>Client_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Client_Contact_Source__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact_Source__c</fullName>
    <label>Client Contact Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CapIq</fullName>
            </value>
            <value>
                <fullName>MCA</fullName>
            </value>
            <value>
                <fullName>Introhive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Contact/fields/Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sector__c</fullName>
    <description>This field contains value of sub sector of associated client record.</description>
    <formula>TEXT( Account.Industry__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/User/fields/EMP_ID__c.field-meta.xml
<CustomField>
    <fullName>EMP_ID__c</fullName>
    <externalId>true</externalId>
    <label>Employee ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/classes/ClientContactDirectoryTriggerHandlerTest.cls
@isTest
public with sharing class ClientContactDirectoryTriggerHandlerTest {
    @testSetup static void dataCreation() {
        
        List<User> listUser = new List<User>();
        
        User userEA =   TestDataFactory.createUserRecord();
        userEA.EMP_ID__c = 'Test1';
        userEA.IsActive = true;
        userEA.Username='testx1.t@gmail.com';
        userEA.Alias ='tu2';
        User userEA2 =   TestDataFactory.createUserRecord();
        userEA2.EMP_ID__c = 'Test11';
        userEA2.IsActive = true;
        userEA2.Username='testx11.t@gmail.com';
        userEA2.Alias ='tu21';
        User userPartnerUser =   TestDataFactory.createUserRecord();
        userPartnerUser.EMP_ID__c = 'Test2';
        userPartnerUser.IsActive = true;
        
        listUser.add(userEA);
        listUser.add(userPartnerUser);
        listUser.add(userEA2);
        
        insert listUser;
        
        //Create Contact
        Contact cont = TestDataFactory.createContact();
        Insert cont;
    }
    
     @isTest static void createEAPartnerLoginMapper(){
        String contId = [SELECT Id FROM Contact LIMIT 1].Id;
        List<User> lstUser = [SELECT Id,EMP_ID__c FROM user where EMP_ID__c in('Test1','Test2','Test11') ];
        system.debug('lstUser>>>'+lstUser);
         List<Client_Contact_Directory__c> ClientContactDirectorylst = new List<Client_Contact_Directory__c>();
        Client_Contact_Directory__c ClientContactDirectoryObj = new Client_Contact_Directory__c(
            BOD_Flag__c = 'No',
            Client_Contact_Source__c = 'None',
            Client_Contact__c = contId,
            Client_Location__CountryCode__s = 'IN',
            Country_Code__c = 'Algeria (+213)',
            Email__c = 'aortega@gcfund.org',
            Key_Contact_Identifier__c = 'None',
            Mailing_Address__CountryCode__s = 'IN',
            Mobile__c = '9999999999',
            Sub_Sector__c = 'Agriculture',
            OwnerId = lstUser[1].Id);
        ClientContactDirectorylst.add(ClientContactDirectoryObj);
        insert ClientContactDirectorylst;
         
         ClientContactDirectoryObj.OwnerId = lstUser[0].Id;
         update ClientContactDirectoryObj;
     }

}