LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Client Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algeria (+213)</fullName>
            </value>
            <value>
                <fullName>Andorra (+376)</fullName>
            </value>
            <value>
                <fullName>Angola (+244)</fullName>
            </value>
            <value>
                <fullName>Anguilla (+1264)</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda (+1268)</fullName>
            </value>
            <value>
                <fullName>Argentina (+54)</fullName>
            </value>
            <value>
                <fullName>Armenia (+374)</fullName>
            </value>
            <value>
                <fullName>Aruba (+297)</fullName>
            </value>
            <value>
                <fullName>Australia (+61)</fullName>
            </value>
            <value>
                <fullName>Austria (+43)</fullName>
            </value>
            <value>
                <fullName>Azerbaijan (+994)</fullName>
            </value>
            <value>
                <fullName>Bahamas (+1242)</fullName>
            </value>
            <value>
                <fullName>Bahrain (+973)</fullName>
            </value>
            <value>
                <fullName>Bangladesh (+880)</fullName>
            </value>
            <value>
                <fullName>Barbados (+1246)</fullName>
            </value>
            <value>
                <fullName>Belarus (+375)</fullName>
            </value>
            <value>
                <fullName>Belgium (+32)</fullName>
            </value>
            <value>
                <fullName>Belize (+501)</fullName>
            </value>
            <value>
                <fullName>Benin (+229)</fullName>
            </value>
            <value>
                <fullName>Bermuda (+1441)</fullName>
            </value>
            <value>
                <fullName>Bhutan (+975)</fullName>
            </value>
            <value>
                <fullName>Bolivia (+591)</fullName>
            </value>
            <value>
                <fullName>Bosnia Herzegovina (+387)</fullName>
            </value>
            <value>
                <fullName>Botswana (+267)</fullName>
            </value>
            <value>
                <fullName>Brazil (+55)</fullName>
            </value>
            <value>
                <fullName>Brunei (+673)</fullName>
            </value>
            <value>
                <fullName>Bulgaria (+359)</fullName>
            </value>
            <value>
                <fullName>Burkina Faso (+226)</fullName>
            </value>
            <value>
                <fullName>Burundi (+257)</fullName>
            </value>
            <value>
                <fullName>Cambodia (+855)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <label>Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Solution</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <inlineHelpText>Source of the Client</inlineHelpText>
    <label>Referral Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <inlineHelpText>Country code of contact number</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code_Name</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <description>This is having details of GT Expertise.</description>
    <label>Expertise - Old (Not To Be Used)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Preliminary_New_Clients__c.field-meta.xml
<CustomField>
    <fullName>Preliminary_New_Clients__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preliminary New Clients</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>New_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Choose an Integrated Solution or Bespoke Solution</inlineHelpText>
    <label>Solution</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SolutionValues</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academia</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni – GT@Industry</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>BO &amp; family office</fullName>
    </customValue>
    <customValue>
        <fullName>Business development efforts</fullName>
    </customValue>
    <customValue>
        <fullName>CA Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>CFO</fullName>
    </customValue>
    <customValue>
        <fullName>Chamber</fullName>
        <label>Chambers</label>
    </customValue>
    <customValue>
        <fullName>CHRO</fullName>
    </customValue>
    <customValue>
        <fullName>CIO CDO CISO</fullName>
    </customValue>
    <customValue>
        <fullName>Client Past Relationships / Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>Client Referral</fullName>
    </customValue>
    <customValue>
        <fullName>CMO</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Calling / Business Development</fullName>
    </customValue>
    <customValue>
        <fullName>Corridors</fullName>
    </customValue>
    <customValue>
        <fullName>Cross Sell</fullName>
        <label>Cross Sell / Up Sell Enquiries</label>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>External Events</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>GCC</fullName>
    </customValue>
    <customValue>
        <fullName>Global Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>GT Employee</fullName>
    </customValue>
    <customValue>
        <fullName>GT Events</fullName>
    </customValue>
    <customValue>
        <fullName>GT Member Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Referrals - GT Firm Personnel</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Referrals - Intermediary Firm</fullName>
    </customValue>
    <description>It depicts the Lead Channel information, from where the Lead is coming.</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Country_Code_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Algeria (+213)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (+376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (+1264)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua &amp; Barbuda (+1268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia (+61)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (+1242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (+1246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (+1441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia Herzegovina (+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana (+267)</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil (+55)</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei (+673)</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria (+359)</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso (+226)</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi (+257)</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia (+855)</fullName>
    </customValue>
    <masterLabel>Country Code Name</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/CaseTriggerHelper.cls
public without sharing class CaseTriggerHelper {
    public static void updateStatusOnCase(List<Case> caseList){
        try{
            for(Case caseObj:caseList){
                caseObj.Status = 'In Progress';
            }
        }
        catch(Exception e){
            System.debug('Error##'+e.getLineNumber());
        }
        
    }
    /*By :-Suresh gupta
    *Date:- 23 Feb 2023
    *Purpose:- Created New Client When Case Status is "Convert to New Client"
    */
    /*------------------------------------------------------*/   
    
    public static void afterUpdateMethod(List<Case> caseList){
        try{
            List<Lead> leadListToBeInserted = New List<Lead>();
            
            Group sectorAssignmentTeamQueue= [SELECT Id from Group WHERE Type = 'Queue' AND DeveloperName = 'SectorAssignmentTeam'];
            //Id readRecordTypeIdOfCase =Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Record_Type_For_Read_Only_cases').getRecordTypeId();
            List<Case> caseListToBeUpdated = new List<Case>();
            for(Case caseObj:caseList){
                system.debug('afterInsertMethod Method has been Called');
                if(String.isNotBlank(caseObj.Industry__c) && 
                   String.isNotBlank(caseObj.SuppliedName) && 
                   String.isNotBlank(caseObj.SuppliedEmail) && 
                   String.isNotBlank(caseObj.Client_Name__c) && 
                   caseObj.SuppliedPhone != null){
                       system.debug('Inside Loop');
                       Lead leadObj = new Lead();
                       leadObj.LastName = caseObj.SuppliedName!=null?caseObj.SuppliedName:caseObj.CaseNumber;//case number
                       System.debug('check sector'+caseObj.Industry__c);
                       leadObj.Industry__c= caseObj.Industry__c;
                       leadObj.Status = 'New';
                       //leadObj.Expertise__c = caseObj.Expertise__c;
                       //leadObj.Solution__c = caseObj.Solution__c;
                       leadObj.LeadSource = 'Email';
                       leadObj.Channel__c = 'Digital';
                       leadObj.CountryCode__c = caseObj.Country_Code__c; //Suraj Kumar(19-04-2023)  
                       leadObj.MobilePhone = caseObj.SuppliedPhone !=null ? caseObj.SuppliedPhone : '';
                       leadObj.Email = caseObj.SuppliedEmail !=null ? caseObj.SuppliedEmail : 'noemail@test.com';
                       leadObj.Company = caseObj.Client_Name__c;//email to case//new client source
                       //leadObj.OwnerId = sectorAssignmentTeamQueue.id;
                       leadObj.Website = caseObj.Website__c;
                       leadObj.Preliminary_New_Clients__c = caseObj.id;
                       leadListToBeInserted.add(leadObj);
                       //updating record type of Preliminary New Client
                   }
            }
            if(leadListToBeInserted.size()>0){
                insert leadListToBeInserted;
                
                system.debug('New Clients Created Successfully');
                
            }
            if(caseListToBeUpdated.size()>0){
                /*
                for(Case caseObj:[select id,RecordTypeId from Case where id IN:caseList]){
                    caseObj.RecordTypeId = readRecordTypeIdOfCase;
                    caseListToBeUpdated.add(caseObj);
                }
                */

                //update caseListToBeUpdated;
                system.debug('Case Updated Successfully');
            }
        }
        catch(exception ex){
            ErrorLogCreater_cls.apexDebugLogger(ex, 'CaseTriggerHelper', 'afterUpdateMethod', null);
       }
        
    }
}