LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Client Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algeria (+213)</fullName>
            </value>
            <value>
                <fullName>Andorra (+376)</fullName>
            </value>
            <value>
                <fullName>Angola (+244)</fullName>
            </value>
            <value>
                <fullName>Anguilla (+1264)</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda (+1268)</fullName>
            </value>
            <value>
                <fullName>Argentina (+54)</fullName>
            </value>
            <value>
                <fullName>Armenia (+374)</fullName>
            </value>
            <value>
                <fullName>Aruba (+297)</fullName>
            </value>
            <value>
                <fullName>Australia (+61)</fullName>
            </value>
            <value>
                <fullName>Austria (+43)</fullName>
            </value>
            <value>
                <fullName>Azerbaijan (+994)</fullName>
            </value>
            <value>
                <fullName>Bahamas (+1242)</fullName>
            </value>
            <value>
                <fullName>Bahrain (+973)</fullName>
            </value>
            <value>
                <fullName>Bangladesh (+880)</fullName>
            </value>
            <value>
                <fullName>Barbados (+1246)</fullName>
            </value>
            <value>
                <fullName>Belarus (+375)</fullName>
            </value>
            <value>
                <fullName>Belgium (+32)</fullName>
            </value>
            <value>
                <fullName>Belize (+501)</fullName>
            </value>
            <value>
                <fullName>Benin (+229)</fullName>
            </value>
            <value>
                <fullName>Bermuda (+1441)</fullName>
            </value>
            <value>
                <fullName>Bhutan (+975)</fullName>
            </value>
            <value>
                <fullName>Bolivia (+591)</fullName>
            </value>
            <value>
                <fullName>Bosnia Herzegovina (+387)</fullName>
            </value>
            <value>
                <fullName>Botswana (+267)</fullName>
            </value>
            <value>
                <fullName>Brazil (+55)</fullName>
            </value>
            <value>
                <fullName>Brunei (+673)</fullName>
            </value>
            <value>
                <fullName>Bulgaria (+359)</fullName>
            </value>
            <value>
                <fullName>Burkina Faso (+226)</fullName>
            </value>
            <value>
                <fullName>Burundi (+257)</fullName>
            </value>
            <value>
                <fullName>Cambodia (+855)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/CaseTriggerHelperTest.cls
@isTest
private class CaseTriggerHelperTest {
    
    @isTest
    static void testUpdateStatusOnCase() {
        
        List<Case> testCases = new List<Case>();
        for (Integer i = 0; i < 5; i++) {
            Case testCase = new Case(Status = 'New');
            testCase.Industry__c = 'Agriculture';
            testCase.SuppliedName = 'Test Name';
            testCase.SuppliedEmail = 'test@example.com';
            testCase.Website__c = 'www.example.com';
            testCase.Client_Name__c = 'Test Client';
            testCase.SuppliedPhone = '1234567890';
            testCase.Country_Code__c = 'Algeria (+213)';
            testCases.add(testCase);
        }
        
        Test.StartTest();
        insert testCases;
        update testCases;
        CaseTriggerHelper.updateStatusOnCase(testCases);
        Test.StopTest();
        for (Case testCase : testCases) {
            System.assertEquals('In Progress', testCase.Status);
        }
    }
    
    @isTest
    static void testAfterUpdateMethod() {
        
        List<Case> testCases = new List<Case>();
        for (Integer i = 0; i < 2; i++) {
            Case testCase = new Case(
                Status = 'New',
                Industry__c = 'Agriculture',
                SuppliedName = 'Test Name',
                SuppliedEmail = 'test@example.com',
                Website__c = 'www.example.com',
                Client_Name__c = 'Test Client',
                SuppliedPhone = '1234567890',
                Country_Code__c = 'Algeria (+213)'
            );
            testCases.add(testCase);
        }
        
        
        Test.startTest();
        insert testCases;
        update testCases;
        CaseTriggerHelper.afterUpdateMethod(testCases);
        Test.stopTest();
        
      //  List<Lead> insertedLeads = [SELECT Id FROM Lead];
     //   System.assertNotEquals(5, insertedLeads.size());
    }
}