LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Lead_Created__c.field-meta.xml
<CustomField>
    <fullName>Lead_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Created</label>
    <type>Checkbox</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <label>Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Solution</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Case/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <inlineHelpText>Source of the Client</inlineHelpText>
    <label>Referral Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <description>This is having details of GT Expertise.</description>
    <label>Expertise - Old (Not To Be Used)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Expertise_LT__c.field-meta.xml
<CustomField>
    <fullName>Expertise_LT__c</fullName>
    <label>Expertise</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>This has all the Industry details of GT.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Preliminary_New_Clients__c.field-meta.xml
<CustomField>
    <fullName>Preliminary_New_Clients__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preliminary New Clients</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>New_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Choose an Integrated Solution or Bespoke Solution</inlineHelpText>
    <label>Solution</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SolutionValues</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/objects/Lead/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <description>It contains the information of sub Industry related to particular Industry.</description>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academia</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni – GT@Industry</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>BO &amp; family office</fullName>
    </customValue>
    <customValue>
        <fullName>Business development efforts</fullName>
    </customValue>
    <customValue>
        <fullName>CA Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>CFO</fullName>
    </customValue>
    <customValue>
        <fullName>Chamber</fullName>
        <label>Chambers</label>
    </customValue>
    <customValue>
        <fullName>CHRO</fullName>
    </customValue>
    <customValue>
        <fullName>CIO CDO CISO</fullName>
    </customValue>
    <customValue>
        <fullName>Client Past Relationships / Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>Client Referral</fullName>
    </customValue>
    <customValue>
        <fullName>CMO</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Calling / Business Development</fullName>
    </customValue>
    <customValue>
        <fullName>Corridors</fullName>
    </customValue>
    <customValue>
        <fullName>Cross Sell</fullName>
        <label>Cross Sell / Up Sell Enquiries</label>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>External Events</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>GCC</fullName>
    </customValue>
    <customValue>
        <fullName>Global Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>GT Employee</fullName>
    </customValue>
    <customValue>
        <fullName>GT Events</fullName>
    </customValue>
    <customValue>
        <fullName>GT Member Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Referrals - GT Firm Personnel</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Referrals - Intermediary Firm</fullName>
    </customValue>
    <description>It depicts the Lead Channel information, from where the Lead is coming.</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Management</fullName>
    </customValue>
    <customValue>
        <fullName>Auto &amp; EV</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Education &amp; Ed tech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Renewables</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering &amp; Industrial Products</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>FMCG &amp; Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Food Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Metals &amp; Mining</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma Bio Tech &amp; Life Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Retail &amp; Ecommerce</fullName>
    </customValue>
    <customValue>
        <fullName>Speciality Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Sports</fullName>
    </customValue>
    <customValue>
        <fullName>Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Telecom</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Urban Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Not for profit</fullName>
        <isActive>false</isActive>
        <label>Not for profit</label>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
        <isActive>false</isActive>
        <label>Services</label>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Industry GVS</masterLabel>
</GlobalValueSet>

LinKreta_POC_Repository/force-app/main/default/classes/EmailtoCaseLWCController.cls
public without sharing class EmailtoCaseLWCController {
    @AuraEnabled(Cacheable = true)
    public static List<Case> getEmailtoCase(){
        List<Case> caseList = [select id,CaseNumber,Subject,SuppliedEmail,SuppliedName,Owner.Name,Lead_Created__c from Case
                               where Owner.Name='Email to Case Queue' AND Lead_Created__c=false ];
        
        return caseList;
    }
    @AuraEnabled
    public static void createLead(List<String> selectedCaseList){
        System.debug('Inside Method'+selectedCaseList);
        try {
            List<Case> caseList=[select id,CaseNumber,SuppliedName,Subject,Industry__c,SubIndustry__c,SuppliedEmail,
                                 Owner.Name,Lead_Created__c,Solution__c,Expertise__c,SuppliedPhone from Case
                                 where CaseNumber IN: selectedCaseList ];
            List<Group> queueName= [SELECT Id from Group WHERE Type = 'Queue' AND DeveloperName = 'SectorAssignmentTeam' ];
            List<Case> updateCaseList = new List<Case>();
            List<Lead> updateLeadList = new List<Lead>();
            System.debug('Queue Name'+queueName[0].id);
            if(!caseList.isEmpty()){
                System.debug('Case List is not Empty'+caseList);
                for(Case caseObj:caseList){
                    //if((String.isNotBlank(caseObj.Industry__c) || String.isNotBlank(caseObj.Expertise__c) || String.isNotBlank(caseObj.Solution__c))){
                    if((String.isNotBlank(caseObj.Industry__c) || String.isNotBlank(caseObj.Expertise__c))){
                        System.debug('Inside if');
                        String str=caseObj.SuppliedEmail;
                        String splitString = str.substringAfter('@');
                        String companyEmail = splitString.substringBefore('.');
                        caseObj.Lead_Created__c = true;
                        Lead leadObj = new Lead();
                        leadObj.LastName = caseObj.SuppliedName!=null?caseObj.SuppliedName:caseObj.CaseNumber;//case number
                        leadObj.Status = 'New';
                        System.debug('check sector'+caseObj.Industry__c);
                        leadObj.Industry__c= caseObj.Industry__c;
                        //leadObj.SubIndustry__c= caseObj.Sub_Sector__c; 
                        leadObj.Expertise_LT__c = caseObj.Expertise__c;
                        //leadObj.Solution__c = caseObj.Solution__c;
                        leadObj.LeadSource = 'Email';
                        leadObj.Channel__c = 'Digital';
                        leadObj.Preliminary_New_Clients__c = caseObj.id;
                        leadObj.MobilePhone = caseObj.SuppliedPhone!=null?caseObj.SuppliedPhone:'';
                        leadObj.Email = caseObj.SuppliedEmail!=null?caseObj.SuppliedEmail:'noemail@test.com';
                        leadObj.Company = companyEmail;//email to case//new client source
                        updateLeadList.add(leadObj);
                        updateCaseList.add(caseObj);
                    }
                    else{
                        System.debug('Inside else');
                        String str=caseObj.SuppliedEmail;
                        String splitString = str.substringAfter('@');
                        String companyEmail = splitString.substringBefore('.');
                        caseObj.Lead_Created__c = true;
                        Lead leadObj = new Lead();
                        leadObj.LastName = caseObj.SuppliedName!=null?caseObj.SuppliedName:caseObj.CaseNumber;//case number
                        leadObj.Status = 'New';
                        System.debug('above owner id');
                        leadObj.OwnerId = queueName[0].id;
                        System.debug('below Email');
                        leadObj.LeadSource = 'Email';
                        leadObj.Channel__c = 'Digital';
                        leadObj.Preliminary_New_Clients__c = caseObj.id;
                         leadObj.MobilePhone = caseObj.SuppliedPhone!=null?caseObj.SuppliedPhone:'';
                        leadObj.MobilePhone = caseObj.SuppliedPhone!=null?caseObj.SuppliedPhone:'';
                        leadObj.Email = caseObj.SuppliedEmail!=null?caseObj.SuppliedEmail:'noemail@test.com';
                        leadObj.Company = companyEmail;//email to case//new client source
                        updateLeadList.add(leadObj);
                        updateCaseList.add(caseObj);
                    }
                }
                try{
                    update updateCaseList;
                    insert updateLeadList; 
                }
                catch(Exception e){
                    System.debug('Error'+e.getLineNumber());
                }
                
            }            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}